/** Questions supplémentaires – accueil, secrétariat médical, transport sanitaire. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_ACCUEIL: Record<string, QuestionBrute[]> = {
  'Accueil et relation patient': [
    ["Au téléphone, la première phrase professionnelle comprend :", "Le nom de l'établissement ou du service, son prénom et une formule de politesse", 'Uniquement « Allô ? »', 'Le numéro de téléphone', 'Rien, on attend que l\'appelant parle'],
    ["Un patient ne parle ni arabe ni français. Vous :", 'Cherchez une solution (collègue, interprète, outil de traduction) en restant courtois', 'Refusez de le recevoir', 'Parlez plus fort', 'Le faites attendre jusqu\'à la fermeture'],
    ["Pour une personne en fauteuil roulant à l'accueil, on veille à :", 'Se placer à sa hauteur et lui faciliter l\'accès', 'Parler uniquement à l\'accompagnant', 'La laisser derrière le comptoir haut', 'Se pencher au-dessus d\'elle'],
    ["Un appel concerne une urgence vitale (enfant qui ne respire plus). Vous :", 'Orientez immédiatement vers le SAMU (190) et alertez un soignant', 'Prenez un rendez-vous', 'Demandez de rappeler plus tard', 'Raccrochez'],
    ["La gestion de la salle d'attente comprend :", "L'information des patients sur le temps d'attente et l'attention aux personnes fragiles", 'L\'ignorance des patients', 'La fermeture des fenêtres en permanence', 'Le tri selon la tenue vestimentaire'],
    ["Un patient mécontent menace de porter plainte. Vous :", "Restez calme, l'écoutez et l'orientez vers la procédure de réclamation", 'Le menacez à votre tour', 'L\'insultez', 'Ignorez sa demande'],
    ["Une bonne posture d'accueil inclut :", 'Regarder la personne, sourire, se présenter et rester disponible', 'Rester sur son téléphone personnel', 'Tourner le dos', 'Mâcher un chewing-gum'],
    ["Lorsqu'on doit faire patienter quelqu'un au téléphone :", 'On le prévient et on reprend l\'appel rapidement', 'On le met en attente sans prévenir pendant longtemps', 'On raccroche', 'On continue une autre conversation sans le dire'],
    ["Les informations médicales données à l'accueil :", 'Sont limitées : seuls les soignants donnent des informations médicales', 'Peuvent être données à tout le monde', 'Sont affichées publiquement', 'Sont données par téléphone à n\'importe qui'],
    ["Un patient âgé désorienté arrive seul. Vous :", 'Le mettez en sécurité, le rassurez et prévenez l\'équipe soignante', 'Le laissez repartir seul', 'Lui demandez de revenir avec quelqu\'un', 'L\'ignorez'],
    ["La prise de rendez-vous doit tenir compte :", "De l'urgence, des contraintes du patient et des consignes du médecin", 'Uniquement de vos préférences', 'Du hasard', 'Uniquement de l\'heure de pause'],
    ["En cas de retard important du médecin, l'accueil :", 'Informe les patients et propose si besoin un autre rendez-vous', 'Ne dit rien', 'Ferme le cabinet', 'Annule tous les rendez-vous sans prévenir'],
    ["Une réclamation écrite d'un patient doit être :", 'Enregistrée et transmise au responsable selon la procédure', 'Jetée', 'Cachée', 'Rendue au patient'],
    ["Le vouvoiement avec les patients est :", 'La règle par défaut, par respect', 'Interdit', 'Réservé aux médecins', 'Inutile'],
    ["Pour expliquer un trajet dans l'hôpital, il est utile de :", 'Donner des repères simples ou accompagner la personne si elle est perdue', 'Dire « c\'est par là » sans préciser', 'Refuser de répondre', 'Donner un plan illisible'],
    ["Un appelant agressif au téléphone insulte la secrétaire. Elle peut :", "Rester polie, poser une limite et mettre fin à l'appel si les insultes continuent, puis le signaler", 'Insulter en retour', 'Pleurer au téléphone', 'Donner des informations confidentielles pour le calmer'],
  ],
  'Gestion du dossier patient': [
    ["À l'admission, les documents demandés au patient sont notamment :", "Une pièce d'identité et les documents de prise en charge (assurance, carte de soins)", 'Uniquement son numéro de téléphone', 'Son diplôme', 'Aucun document'],
    ["Le numéro de dossier unique permet :", 'D\'éviter les doublons et les erreurs d\'identité', 'De calculer l\'âge', 'De fixer le prix', 'Rien'],
    ["Un doublon de dossier (même patient avec deux dossiers) doit être :", 'Signalé pour être fusionné selon la procédure', 'Laissé tel quel', 'Supprimé sans vérification', 'Utilisé alternativement'],
    ["Les documents papier contenant des données médicales sont :", 'Rangés sous clé et détruits de façon sécurisée (broyeur)', 'Jetés à la poubelle ordinaire', 'Laissés sur le comptoir', 'Recyclés comme brouillon'],
    ["Envoyer un compte rendu médical par email nécessite :", 'Une messagerie sécurisée et la vérification du destinataire', 'N\'importe quelle adresse email', 'Une copie à tout le service', 'Aucune précaution'],
    ["Un mot de passe de logiciel médical doit être :", 'Personnel, robuste et jamais partagé', 'Écrit sur un post-it sur l\'écran', 'Le même pour tout le service', 'Votre date de naissance'],
    ["La facturation d'un acte nécessite :", 'Le bon code de l\'acte, l\'identité exacte du patient et les justificatifs', 'Une estimation au hasard', 'Le nom d\'un autre patient', 'Aucune information'],
    ["Un patient demande une copie de son dossier :", "La demande est traitée selon la procédure légale de l'établissement, avec vérification de son identité", 'On refuse toujours', 'On donne le dossier à la personne qui appelle', 'On envoie le dossier sans vérifier'],
    ["La saisie de l'identité du patient se fait :", 'À partir d\'une pièce d\'identité, en respectant l\'orthographe exacte', 'Phonétiquement, à l\'oreille', 'Avec un surnom', 'Sans date de naissance'],
    ["Un courrier médical arrivé au secrétariat est :", 'Enregistré, transmis au médecin puis classé dans le bon dossier', 'Laissé dans une pile', 'Ouvert par n\'importe qui et commenté', 'Jeté'],
    ["La sauvegarde des données informatiques sert à :", 'Éviter la perte des dossiers en cas de panne', 'Ralentir l\'ordinateur', 'Partager les données sur internet', 'Rien'],
    ["Les résultats d'examens sont classés :", 'Dans le dossier du bon patient après vérification de l\'identité', 'Au hasard', 'Dans le dossier d\'un homonyme', 'Dans un tiroir sans nom'],
    ["Un écran affichant un dossier patient à l'accueil doit être :", 'Orienté pour ne pas être visible du public et verrouillé en cas d\'absence', 'Tourné vers la salle d\'attente', 'Laissé ouvert pendant la pause', 'Sans importance'],
    ["La durée de conservation des dossiers médicaux :", 'Est fixée par la réglementation et doit être respectée', 'Est d\'une semaine', 'Est libre', 'Est d\'un jour'],
    ["La planification des rendez-vous dans un agenda partagé exige :", 'Des informations exactes (motif, durée, coordonnées) et sa mise à jour', 'Uniquement le prénom', 'Des rendez-vous en double volontairement', 'Aucune mise à jour'],
    ["Une fuite de données (dossier envoyé à une mauvaise personne) doit être :", 'Signalée immédiatement au responsable', 'Cachée', 'Ignorée si personne ne s\'en rend compte', 'Corrigée en envoyant d\'autres dossiers'],
  ],
  'Terminologie médicale': [
    ["« Hypotension » signifie :", 'Tension artérielle basse', 'Tension artérielle élevée', 'Rythme cardiaque rapide', 'Fièvre'],
    ["« Dyspnée » signifie :", 'Difficulté à respirer', 'Difficulté à avaler', 'Douleur abdominale', 'Trouble du sommeil'],
    ["« Dysphagie » signifie :", 'Difficulté à avaler', 'Difficulté à respirer', 'Trouble de la vue', 'Perte de mémoire'],
    ["Le suffixe « -algie » signifie :", 'Douleur (ex. : névralgie)', 'Inflammation', 'Ablation', 'Écoulement'],
    ["Le suffixe « -scopie » signifie :", 'Examen visuel à l\'aide d\'un instrument (ex. : endoscopie)', 'Ablation', 'Douleur', 'Suture'],
    ["Le suffixe « -tomie » signifie :", 'Incision (ex. : laparotomie)', 'Ablation totale', 'Inflammation', 'Examen du sang'],
    ["« Hématurie » signifie :", 'Présence de sang dans les urines', 'Présence de sucre dans les urines', 'Absence d\'urines', 'Urines abondantes'],
    ["« Anurie » signifie :", 'Absence d\'urines', 'Urines abondantes', 'Sang dans les urines', 'Douleur en urinant'],
    ["Le préfixe « hémi- » signifie :", 'Moitié (ex. : hémiplégie)', 'Sang', 'Double', 'Autour'],
    ["« Néphrologie » est la spécialité :", 'Des reins', 'Du cœur', 'Du cerveau', 'De la peau'],
    ["« Gastro-entérologie » concerne :", 'Le tube digestif', 'Les poumons', 'Les os', 'Les yeux'],
    ["« Pneumologie » concerne :", 'Les poumons et la respiration', 'Les reins', 'Les dents', 'Les nerfs'],
    ["« IV » sur une prescription signifie :", 'Intraveineuse', 'Intramusculaire', 'Quatre fois par jour', 'Par la bouche'],
    ["« ATCD » dans un dossier signifie :", 'Antécédents', 'Analyse', 'Attestation', 'Autorisation'],
    ["« Bradypnée » signifie :", 'Respiration lente', 'Respiration rapide', 'Cœur rapide', 'Cœur lent'],
  ],
  'Transport sanitaire': [
    ["Avant de partir en intervention, l'ambulancier vérifie :", "Le véhicule, l'oxygène, le matériel de soins et de communication", 'Uniquement le carburant', 'La radio musicale', 'Rien'],
    ["La position demi-assise pendant le transport convient :", 'À un patient qui a du mal à respirer (selon l\'état et l\'avis médical)', 'À un patient en état de choc avec tension effondrée', 'À un traumatisé du rachis', 'À une victime inconsciente'],
    ["Une femme enceinte au 3e trimestre est transportée de préférence :", 'En position latérale gauche (ou inclinée à gauche)', 'Sur le dos à plat', 'Sur le ventre', 'Assise penchée en avant'],
    ["Un patient en état de choc est souvent installé :", 'Allongé, jambes éventuellement surélevées selon le contexte, et surveillé', 'Assis sur une chaise', 'Debout', 'Sur le ventre'],
    ["La bouteille d'oxygène doit être :", 'Fixée, manipulée sans graisse et éloignée de toute flamme', 'Posée libre sur le brancard', 'Graissée pour faciliter l\'ouverture', 'Placée près du chauffage'],
    ["Le bilan transmis au médecin régulateur comprend :", 'Conscience, respiration, circulation, plaintes et circonstances', 'Uniquement l\'adresse', 'Uniquement le nom du patient', 'Rien'],
    ["Pendant le transport, l'ambulancier :", 'Surveille en permanence le patient et rend compte de toute aggravation', 'Reste dans la cabine sans regarder', 'Laisse le patient seul à l\'arrière', 'Écoute de la musique forte'],
    ["L'usage des avertisseurs lumineux et sonores est :", "Réservé aux situations d'urgence, avec prudence", 'Permanent', 'Interdit en toutes circonstances', 'Utilisé pour éviter les bouchons sans urgence'],
    ["La ceinture de sécurité du patient et de l'accompagnant :", 'Doit être attachée pendant le transport', 'Est facultative', 'Est interdite', 'Gêne la surveillance donc on l\'enlève'],
    ["Un patient sous oxygène refuse son masque pendant le transport. On :", 'Explique, rassure, propose une lunette nasale si prescrite et informe le médecin', 'Force le masque sur le visage', 'Arrête l\'oxygène sans rien dire', 'Débranche le patient'],
    ["La fiche d'intervention ou de transport doit être :", 'Remplie et transmise à l\'équipe qui accueille le patient', 'Remplie le lendemain de mémoire', 'Jetée', 'Remise à un passant'],
    ["Le nettoyage du brancard et de la cellule sanitaire se fait :", 'Après chaque transport', 'Une fois par mois', 'Jamais', 'Uniquement s\'il est très sale'],
    ["Un patient dialysé transporté régulièrement : on veille surtout à :", 'Ne pas comprimer ni prendre la tension sur le bras de la fistule', 'Prendre la tension sur la fistule', 'Le transporter debout', 'Ne rien vérifier'],
    ["En arrivant sur un accident de la route, l'ambulancier commence par :", 'Sécuriser les lieux (balisage) pour éviter un sur-accident', 'Courir vers la première victime sans regarder', 'Prendre des photos', 'Déplacer les véhicules impliqués'],
    ["Le secret professionnel s'applique aux ambulanciers :", 'Oui, comme à tous les professionnels de santé', 'Non, jamais', 'Seulement la nuit', 'Seulement pour les enfants'],
    ["Un patient agité risque de se blesser pendant le transport. On :", 'Sécurise l\'installation, rassure et demande un renfort médical si besoin', 'Le laisse se lever dans le véhicule', 'Accélère pour arriver plus vite', 'Le laisse seul'],
  ],
  'Immobilisation et relevage': [
    ["Le collier cervical est posé :", 'Après maintien manuel de la tête dans l\'axe, avec une taille adaptée', 'Avant tout examen, en tournant la tête pour l\'ajuster', 'Sans maintien de la tête', 'Uniquement si le patient le demande'],
    ["Le relevage d'une victime suspecte de traumatisme du rachis nécessite :", 'Plusieurs sauveteurs coordonnés et un matériel adapté (brancard cuillère, plan dur)', 'Un seul sauveteur qui la soulève', 'De la faire marcher', 'De la tirer par les pieds'],
    ["Le brancard cuillère permet :", 'De soulever une victime en limitant ses mouvements', 'De la réanimer', 'De mesurer sa tension', 'De la réchauffer'],
    ["Un membre fracturé avec déformation doit être :", 'Immobilisé dans la position où il se trouve, sauf consigne médicale', 'Remis en place par l\'ambulancier', 'Massé', 'Laissé sans immobilisation'],
    ["Après l'immobilisation d'un membre, on vérifie à nouveau :", 'La circulation, la sensibilité et la motricité en dessous', 'La couleur du matériel', 'L\'heure', 'Rien'],
    ["Une victime casquée (moto) consciente et qui respire :", 'Ne se voit retirer le casque que selon une technique à deux, si nécessaire', 'Doit retirer elle-même son casque rapidement', 'Doit garder le casque en toutes circonstances même si elle vomit', 'Doit être secouée'],
    ["Le chef d'équipe lors d'un relevage :", 'Coordonne les gestes et donne les ordres de mouvement', 'Ne parle pas', 'Porte seul la victime', 'Filme l\'intervention'],
    ["Une écharpe (bras en écharpe) est utilisée pour immobiliser :", 'Une blessure du membre supérieur (épaule, bras, avant-bras)', 'Une fracture de la jambe', 'Une blessure de la colonne', 'Une plaie du crâne'],
    ["L'attelle à dépression se moule :", 'Autour du membre, puis l\'air est retiré pour la rigidifier', 'En gonflant fortement', 'Avec de l\'eau', 'Après l\'arrivée à l\'hôpital'],
    ["Une fracture ouverte (os visible) nécessite :", 'De protéger la plaie avec un pansement stérile, sans remettre l\'os en place', 'De remettre l\'os dans la plaie', 'De laver la plaie au savon', 'De la laisser à l\'air'],
    ["La position latérale de sécurité est contre-indiquée chez :", 'Une victime suspecte de traumatisme du rachis sans technique adaptée', 'Une victime inconsciente qui respire sans traumatisme', 'Une victime qui vomit', 'Une victime intoxiquée'],
    ["Le plan dur (planche) est utilisé :", "Pour immobiliser et déplacer une victime traumatisée de façon rigide", 'Pour faire la toilette', 'Pour réchauffer la victime', 'Pour transporter du matériel uniquement'],
    ["Avant de soulever une victime, les sauveteurs :", 'Se placent jambes fléchies, dos droit, et soulèvent au signal', 'Soulèvent dos courbé jambes tendues', 'Soulèvent chacun à leur rythme', 'Tirent la victime par les vêtements'],
    ["L'immobilisation du bassin (ceinture pelvienne) est indiquée :", 'En cas de suspicion de fracture grave du bassin avec risque hémorragique', 'Pour une entorse de la cheville', 'Pour une plaie du doigt', 'Jamais'],
    ["Le dégagement d'urgence d'une victime (sans immobilisation préalable) est réservé :", "À un danger réel, immédiat et non contrôlable (incendie, risque d'explosion)", 'À toutes les situations', 'Aux victimes conscientes uniquement', 'Aux victimes âgées'],
    ["Une victime en hypothermie doit être manipulée :", 'Avec douceur, protégée du froid et isolée du sol', 'Brusquement', 'Plongée dans un bain chaud', 'Massée énergiquement'],
  ],
};
