/** Questions supplémentaires – accueil, secrétariat médical, transport sanitaire. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_ACCUEIL: Record<string, QuestionBrute[]> = {
  'Accueil et relation patient': [
    ["Au téléphone, la première phrase professionnelle comprend :", 'Le service, son prénom, une salutation', 'Uniquement « Allô ? »', "Le numéro de téléphone du service et l'heure d'ouverture du secrétariat", 'Rien, on attend que l\'appelant parle'],
    ["Un patient ne parle ni arabe ni français. Vous :", 'Cherchez un interprète ou un outil', 'Refusez de le recevoir', "Lui parlez plus fort et plus lentement en français jusqu'à ce qu'il comprenne", 'Le faites attendre jusqu\'à la fermeture'],
    ["Pour une personne en fauteuil roulant à l'accueil, on veille à :", 'Se mettre à sa hauteur', "Parler uniquement à l'accompagnant, pour lui éviter de répondre", 'La laisser derrière le comptoir haut', 'Se pencher au-dessus d\'elle'],
    ["Un appel concerne une urgence vitale (enfant qui ne respire plus). Vous :", 'Orientez immédiatement vers le SAMU (190) et alertez un soignant', 'Prenez un rendez-vous', 'Demandez de rappeler plus tard, quand un médecin sera disponible', 'Lui demandez de rappeler plus tard'],
    ["La gestion de la salle d'attente comprend :", 'Informer et veiller aux fragiles', 'L\'ignorance des patients', 'La fermeture des fenêtres en permanence', "Le passage des patients strictement par ordre d'arrivée, sans exception"],
    ["Un patient mécontent menace de porter plainte. Vous :", "Restez calme, l'écoutez et l'orientez vers la procédure de réclamation", 'Le menacez à votre tour', "Lui demandez de quitter immédiatement l'établissement", "Lui dites qu'il n'a aucun droit de réclamer, pour clore la discussion"],
    ["Une bonne posture d'accueil inclut :", 'Regarder la personne, sourire, se présenter et rester disponible', 'Continuer sa saisie en écoutant la personne sans la regarder', 'Tourner le dos', 'Mâcher un chewing-gum'],
    ["Lorsqu'on doit faire patienter quelqu'un au téléphone :", 'On le prévient et on reprend l\'appel rapidement', 'On le met en attente sans prévenir pendant longtemps', 'On raccroche', 'On continue une autre conversation sans le dire'],
    ["Les informations médicales données à l'accueil :", 'Sont limitées', 'Peuvent être données à tout membre de la famille qui se présente', 'Sont affichées publiquement', 'Sont données par téléphone à n\'importe qui'],
    ["Un patient âgé désorienté arrive seul. Vous :", "Le rassurez et prévenez l'équipe", 'Le laissez repartir seul', "Lui demandez de rentrer chez lui et de revenir accompagné d'un proche", 'L\'ignorez'],
    ["La prise de rendez-vous doit tenir compte :", "De l'urgence et des consignes", "Uniquement de l'ordre des appels, sans considération de l'urgence", 'Du hasard', 'Uniquement de l\'heure de pause'],
    ["En cas de retard important du médecin, l'accueil :", 'Informe les patients', 'Ne dit rien', 'Ferme le cabinet', 'Annule tous les rendez-vous de la journée sans prévenir les patients'],
    ["Une réclamation écrite d'un patient doit être :", 'Enregistrée et transmise au responsable selon la procédure', 'Classée sans suite', 'Rendue au patient', 'Laissée sans réponse ni enregistrement'],
    ["Le vouvoiement avec les patients est :", 'La règle par défaut, par respect', "Inutile à l'hôpital", 'Réservé aux médecins', 'Réservé aux personnes âgées'],
    ["Pour expliquer un trajet dans l'hôpital, il est utile de :", 'Donner des repères simples', 'Dire « c\'est par là » sans préciser', 'Refuser de répondre', 'Lui conseiller de demander son chemin aux autres patients dans les couloirs'],
    ["Un appelant agressif au téléphone insulte la secrétaire. Elle peut :", 'Poser une limite, raccrocher, signaler', 'Insulter en retour', "Lui donner les informations demandées pour qu'il se calme", 'Lui donner les informations demandées, même confidentielles, pour le calmer'],
  ],
  'Gestion du dossier patient': [
    ["À l'admission, les documents demandés au patient sont notamment :", 'Identité et prise en charge', 'Uniquement son numéro de téléphone', 'Son dernier bulletin de salaire et une attestation de domicile', 'Aucun document'],
    ["Le numéro de dossier unique permet :", "D'éviter les erreurs d'identité", 'De calculer l\'âge', 'De fixer le prix', 'Rien'],
    ["Un doublon de dossier (même patient avec deux dossiers) doit être :", 'Signalé pour fusion', 'Laissé tel quel', 'Supprimé immédiatement par la secrétaire, sans autre vérification', 'Utilisé alternativement'],
    ["Les documents papier contenant des données médicales sont :", 'Sous clé, puis broyés', 'Jetés à la poubelle ordinaire', 'Laissés sur le comptoir', 'Recyclés comme brouillon au secrétariat après la fin de la consultation'],
    ["Envoyer un compte rendu médical par email nécessite :", 'Une messagerie sécurisée', 'N\'importe quelle adresse email', 'Une copie à tout le service, pour assurer la continuité des soins', 'Aucune précaution'],
    ["Un mot de passe de logiciel médical doit être :", 'Personnel et robuste', 'Écrit sur un post-it sur l\'écran', "Le même pour tout le service, pour dépanner en cas d'absence", 'Votre date de naissance'],
    ["La facturation d'un acte nécessite :", 'Le bon code et la bonne identité', 'Une estimation du tarif, corrigée plus tard si nécessaire par la comptabilité', 'Le nom d\'un autre patient', 'Aucune information'],
    ["Un patient demande une copie de son dossier :", "La demande est traitée selon la procédure légale de l'établissement, avec vérification de son identité", 'On refuse toujours de transmettre des copies au patient', 'On donne le dossier original à la personne qui appelle, sans délai', 'On envoie le dossier sans vérifier'],
    ["La saisie de l'identité du patient se fait :", "D'après la pièce d'identité", "Phonétiquement, d'après ce que dit le patient, pour aller plus vite", 'Avec un surnom', 'Sans date de naissance'],
    ["Un courrier médical arrivé au secrétariat est :", 'Enregistré, transmis, classé', 'Laissé dans une pile en attente de classement', "Ouvert et lu par l'accueil, puis rangé dans une pile en attente de classement", "Lu par l'accueil et rangé dans une pile"],
    ["La sauvegarde des données informatiques sert à :", 'Éviter la perte des dossiers', 'Partager les dossiers sur internet', "Partager les données avec d'autres établissements via internet", "Accélérer le démarrage de l'ordinateur"],
    ["Les résultats d'examens sont classés :", 'Dans le bon dossier, identité vérifiée', 'Au hasard', 'Par date de réception, dans un classeur commun à tous les patients', "Dans un tiroir commun, par ordre d'arrivée"],
    ["Un écran affichant un dossier patient à l'accueil doit être :", 'Non visible et verrouillé', 'Tourné vers la salle d\'attente', 'Laissé ouvert pendant la pause, pour reprendre plus vite le travail', 'Sans importance'],
    ["La durée de conservation des dossiers médicaux :", 'Est fixée par la réglementation et doit être respectée', 'Est d\'une semaine', 'Est libre', 'Est libre et décidée par le médecin'],
    ["La planification des rendez-vous dans un agenda partagé exige :", 'Des informations exactes (motif, durée, coordonnées) et sa mise à jour', 'Uniquement le prénom', 'Des rendez-vous en double, pour compenser les absences des patients', 'Aucune mise à jour une fois le rendez-vous fixé'],
    ["Une fuite de données (dossier envoyé à une mauvaise personne) doit être :", 'Signalée immédiatement au responsable', 'Cachée', 'Ignorée si personne ne s\'en rend compte', 'Corrigée en envoyant d\'autres dossiers'],
  ],
  'Terminologie médicale': [
    ["« Hypotension » signifie :", 'Tension artérielle basse', 'Tension artérielle élevée', 'Rythme cardiaque rapide', 'Fièvre'],
    ["« Dyspnée » signifie :", 'Gêne respiratoire', 'Difficulté à avaler les aliments solides', 'Douleur abdominale', 'Trouble du sommeil'],
    ["« Dysphagie » signifie :", 'Difficulté à avaler', 'Difficulté à respirer', 'Trouble de la vue', 'Perte de mémoire'],
    ["Le suffixe « -algie » signifie :", 'Douleur', 'Inflammation', 'Ablation', "Écoulement anormal d'un liquide"],
    ["Le suffixe « -scopie » signifie :", 'Examen visuel', 'Ablation', 'Douleur', "Suture chirurgicale d'un organe"],
    ["Le suffixe « -tomie » signifie :", 'Incision', "Ablation totale d'un organe", 'Inflammation', 'Examen du sang'],
    ["« Hématurie » signifie :", 'Présence de sang dans les urines', 'Présence de sucre dans les urines', 'Absence d\'urines', 'Urines abondantes'],
    ["« Anurie » signifie :", 'Absence d\'urines', 'Urines abondantes', 'Sang dans les urines', 'Douleur en urinant'],
    ["Le préfixe « hémi- » signifie :", 'Moitié', 'Sang', 'Double', 'Autour de, à proximité de'],
    ["« Néphrologie » est la spécialité :", 'Des reins', 'Du cœur', 'Du cerveau', 'De la peau'],
    ["« Gastro-entérologie » concerne :", 'Le tube digestif', 'Les poumons', 'Les os', 'Les yeux'],
    ["« Pneumologie » concerne :", 'Les poumons et la respiration', 'Le cœur, les artères et les vaisseaux', "Les reins et l'appareil urinaire", 'Le système nerveux et le cerveau'],
    ["« IV » sur une prescription signifie :", 'Intraveineuse', 'Intramusculaire', 'Quatre fois par jour', 'Par la bouche'],
    ["« ATCD » dans un dossier signifie :", 'Antécédents', 'Analyse', 'Attestation', 'Autorisation'],
    ["« Bradypnée » signifie :", 'Respiration lente', 'Respiration rapide', 'Cœur rapide', 'Cœur lent'],
  ],
  'Transport sanitaire': [
    ["Avant de partir en intervention, l'ambulancier vérifie :", "Le véhicule, l'oxygène, le matériel de soins et de communication", 'Uniquement le carburant et la pression des pneus', 'La radio musicale', 'Rien'],
    ["La position demi-assise pendant le transport convient :", 'À un patient dyspnéique', 'À un patient en état de choc, tension effondrée', 'À un traumatisé du rachis', 'À une victime inconsciente'],
    ["Une femme enceinte au 3e trimestre est transportée de préférence :", 'En position latérale gauche (ou inclinée à gauche)', 'Sur le dos à plat', 'Sur le ventre', 'Assise penchée en avant pour soulager le dos'],
    ["Un patient en état de choc est souvent installé :", 'Allongé, jambes éventuellement surélevées selon le contexte, et surveillé', 'Assis, buste penché en avant pour faciliter la respiration', 'Debout, soutenu par deux sauveteurs', 'Sur le ventre'],
    ["La bouteille d'oxygène doit être :", 'Fixée, manipulée sans graisse et éloignée de toute flamme', 'Posée libre sur le brancard', "Graissée au niveau du robinet pour faciliter l'ouverture", 'Placée près du chauffage'],
    ["Le bilan transmis au médecin régulateur comprend :", 'Conscience, respiration, circulation, plaintes et circonstances', "Uniquement l'adresse, le nom et l'âge du patient", 'Uniquement le nom du patient', 'Rien'],
    ["Pendant le transport, l'ambulancier :", 'Surveille le patient en permanence', "Reste dans la cabine et ne vérifie le patient qu'à l'arrivée", 'Laisse le patient seul à l\'arrière', "Reste dans la cabine et ne vérifie qu'à l'arrivée"],
    ["L'usage des avertisseurs lumineux et sonores est :", 'Réservé aux urgences', 'Permanent', 'Interdit en toutes circonstances', 'Autorisé pour tout transport sanitaire, même sans urgence'],
    ["La ceinture de sécurité du patient et de l'accompagnant :", 'Doit être attachée', "Est facultative pour l'accompagnant", 'Est interdite pour le patient allongé', 'Est retirée pendant le trajet, car elle gêne la surveillance du patient'],
    ["Un patient sous oxygène refuse son masque pendant le transport. On :", 'Explique, rassure et informe le médecin', 'Force le masque sur le visage', "Arrête l'oxygène jusqu'à l'arrivée, puisque le patient le refuse", 'Débranche le patient'],
    ["La fiche d'intervention ou de transport doit être :", "Remplie et transmise à l'équipe qui accueille le patient", 'Remplie le lendemain, de mémoire, au retour à la base', 'Jetée', 'Remise à un passant'],
    ["Le nettoyage du brancard et de la cellule sanitaire se fait :", 'Après chaque transport', 'Une fois par mois', 'Jamais', 'Uniquement s\'il est très sale'],
    ["Un patient dialysé transporté régulièrement : on veille surtout à :", 'Protéger le bras de la fistule', "Prendre la tension sur le bras de la fistule, plus facile d'accès", 'Le transporter debout', 'Ne rien vérifier'],
    ["En arrivant sur un accident de la route, l'ambulancier commence par :", 'Baliser les lieux', 'Courir vers la première victime sans regarder', 'Prendre des photos', 'Déplacer les véhicules impliqués pour dégager la route rapidement'],
    ["Le secret professionnel s'applique aux ambulanciers :", 'Oui', 'Non, jamais', 'Seulement la nuit', 'Seulement pour les mineurs et les patients sous tutelle'],
    ["Un patient agité risque de se blesser pendant le transport. On :", "Sécurise l'installation, rassure et demande un renfort médical si besoin", 'Le laisse se lever dans le véhicule', 'Accélère pour arriver plus vite et le confier aux urgences', "Le laisse seul à l'arrière pour ne pas l'énerver"],
  ],
  'Immobilisation et relevage': [
    ["Le collier cervical est posé :", 'Après maintien de la tête, taille adaptée', "Avant tout examen, en tournant la tête du blessé pour bien l'ajuster", 'Sans maintien de la tête', 'Uniquement si le patient le demande'],
    ["Le relevage d'une victime suspecte de traumatisme du rachis nécessite :", 'Plusieurs sauveteurs coordonnés et un matériel adapté (brancard cuillère, plan dur)', 'Un seul sauveteur qui la soulève en la tenant sous les aisselles', 'De la faire marcher', 'De la tirer par les pieds'],
    ["Le brancard cuillère permet :", 'De soulever sans bouger la victime', 'De la réanimer', 'De transporter la victime assise sur de longues distances', 'De la réchauffer et la couvrir pendant le trajet'],
    ["Un membre fracturé avec déformation doit être :", 'Immobilisé tel quel', "Remis dans l'axe par l'ambulancier avant toute immobilisation", 'Massé', 'Laissé sans immobilisation'],
    ["Après l'immobilisation d'un membre, on vérifie à nouveau :", 'Circulation, sensibilité, motricité', 'La couleur du matériel', "Uniquement la bonne fermeture des sangles de l'attelle", 'Rien'],
    ["Une victime casquée (moto) consciente et qui respire :", 'Garde son casque, retiré à deux si besoin', 'Doit retirer elle-même son casque rapidement pour mieux respirer', 'Doit garder le casque en toutes circonstances même si elle vomit', 'Doit être secouée'],
    ["Le chef d'équipe lors d'un relevage :", 'Coordonne et donne les ordres', 'Ne parle pas', 'Porte la tête de la victime et laisse chacun bouger à son rythme', 'Filme l\'intervention'],
    ["Une écharpe (bras en écharpe) est utilisée pour immobiliser :", 'Une blessure du membre supérieur', 'Une fracture de la jambe', 'Une blessure de la colonne', 'Une plaie du crâne'],
    ["L'attelle à dépression se moule :", 'Autour du membre, puis on fait le vide', 'En gonflant fortement', 'Avec de l\'eau', 'Après l\'arrivée à l\'hôpital'],
    ["Une fracture ouverte (os visible) nécessite :", 'De protéger la plaie stérilement', 'De remettre l\'os dans la plaie', "De laver la plaie au savon et de remettre l'os dans l'axe", "De la laisser à l'air pour éviter la macération"],
    ["La position latérale de sécurité est contre-indiquée chez :", 'Un traumatisé du rachis, sans technique adaptée', 'Une victime inconsciente qui respire, sans aucun traumatisme', 'Une victime inconsciente qui vomit, sans traumatisme', 'Une victime intoxiquée qui respire normalement'],
    ["Le plan dur (planche) est utilisé :", 'Pour immobiliser un traumatisé', 'Pour faire la toilette', 'Pour réchauffer la victime', 'Pour transporter le matériel de réanimation uniquement'],
    ["Avant de soulever une victime, les sauveteurs :", 'Dos droit, et soulèvent au signal', 'Soulèvent dos courbé jambes tendues', 'Soulèvent chacun à leur rythme, sans attendre de signal commun', 'Tirent la victime par les vêtements'],
    ["L'immobilisation du bassin (ceinture pelvienne) est indiquée :", 'Fracture grave du bassin suspectée', 'Pour toute douleur de hanche, même légère, chez la personne âgée', 'Pour une plaie du doigt', 'Pour toute douleur de hanche, même légère'],
    ["Le dégagement d'urgence d'une victime (sans immobilisation préalable) est réservé :", "À un danger réel, immédiat et non contrôlable (incendie, risque d'explosion)", 'À toutes les situations', 'Aux victimes conscientes qui peuvent aider les sauveteurs', 'Aux victimes âgées'],
    ["Une victime en hypothermie doit être manipulée :", 'Avec douceur, isolée du froid', 'Frictionnée vivement pour la réchauffer', 'Plongée rapidement dans un bain chaud', 'Massée énergiquement et frictionnée pour la réchauffer vite'],
  ],
};
