/** Questions supplémentaires – aide-soignant(e) / auxiliaire. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_AIDE: Record<string, QuestionBrute[]> = {
  "Soins d'hygiène et de confort": [
    ["La température de l'eau pour une toilette est vérifiée :", 'Avec le coude ou un thermomètre', "Avec le bout des doigts, l'eau devant être bien chaude pour le confort", 'En demandant au patient après coup', 'Elle n\'a pas d\'importance'],
    ["Pour la toilette intime, on utilise :", "Un gant et une serviette dédiés, du haut vers le bas (de l'avant vers l'arrière)", 'Le même gant que pour le reste du corps, en terminant par le visage', 'De l\'alcool', 'Un gant d\'un autre patient'],
    ["Les soins de bouche d'un patient porteur d'une prothèse dentaire comprennent :", 'Le nettoyage de la prothèse et de la bouche', 'Le port de la prothèse jour et nuit sans nettoyage', 'Le rangement de la prothèse dans un mouchoir', 'Rien'],
    ["Le shampoing au lit nécessite :", 'Protéger le lit, bien installer', 'De mouiller tout le lit', "De faire asseoir le patient au bord du lit, même s'il ne tient pas assis", "Aucune préparation particulière, l'eau étant absorbée par le matelas"],
    ["La réfection d'un lit occupé se fait :", 'En tournant le patient de côté', "En faisant lever le patient au fauteuil, même s'il ne peut pas se tenir debout", 'Sans prévenir le patient', 'En secouant les draps'],
    ["Le linge sale est :", 'Mis directement dans le sac, sans le secouer', 'Posé sur le lit d\'à côté', 'Posé par terre dans la chambre puis ramassé en fin de tournée', 'Posé au sol dans la chambre puis ramassé en fin de tournée'],
    ["Un patient incontinent doit bénéficier :", 'De changes réguliers', "D'une limitation des boissons pour réduire le nombre de changes", 'D\'un change une fois par jour', 'D\'aucun soin particulier'],
    ["Le rasage d'un patient sous anticoagulant se fait de préférence :", 'Au rasoir électrique', 'Au rasoir à lame', 'Avec des ciseaux', 'Ce n\'est jamais possible'],
    ["Pendant la toilette, l'aide-soignant observe notamment :", 'Peau, autonomie, humeur, douleur', 'Uniquement la couleur des draps', "Uniquement l'heure et la durée de la toilette", 'Uniquement la propreté du patient à la fin de la toilette'],
    ["Les ongles d'un patient diabétique :", 'Ne sont pas coupés sans avis', "Sont coupés très court et arrondis pour éviter qu'ils ne s'incarnent", 'Sont limés avec une lime métallique agressive', 'Ne nécessitent aucune attention'],
    ["L'installation au fauteuil d'un patient comprend :", 'Confort, pieds posés, sonnette à portée', 'Le laisser glisser', "L'installer plusieurs heures sans changer de position pour qu'il se repose", 'Le laisser plusieurs heures sans changer de position'],
    ["La pudeur d'un patient pendant le change est respectée en :", 'Porte fermée, corps couvert', 'Laissant la porte ouverte', 'Faisant le soin devant les visiteurs', "Faisant le soin rapidement, porte entrouverte pour pouvoir appeler de l'aide"],
    ["Un patient en fin de vie a besoin en priorité :", 'De confort et de présence', 'D\'une toilette complète toutes les heures', "D'une toilette complète plusieurs fois par jour pour qu'il soit toujours propre", 'D\'être réveillé souvent'],
    ["L'hygiène des mains de l'aide-soignant est réalisée :", 'Avant et après chaque soin', 'Uniquement en fin de journée', 'Uniquement si les mains sont sales', 'Uniquement si les mains sont visiblement sales, les gants protégeant le reste du temps'],
    ["Un bain ou une douche chez un patient âgé fragile impose :", 'Une surveillance', 'De le laisser seul', 'Une eau très chaude et une durée prolongée pour bien le détendre', 'Une durée la plus longue possible'],
  ],
  'Prévention des escarres': [
    ["Une escarre est due principalement à :", 'Une pression prolongée', 'Une réaction allergique aux draps ou aux produits de toilette', 'Une infection virale', 'Un manque de soleil'],
    ["Un matelas anti-escarres :", 'Répartit les pressions, sans dispenser des retournements', 'Supprime le besoin de changer de position et de surveiller la peau du patient', 'Est inutile chez un patient qui change de position seul et surveillé', 'Doit être recouvert de plusieurs couches de draps'],
    ["Pour un patient assis au fauteuil, la zone la plus exposée est :", 'Les ischions', 'Le front', 'Les mains', 'Les genoux et la face antérieure des cuisses'],
    ["La position semi-latérale à 30° est recommandée car :", "Elle évite l'appui sur trochanter et sacrum", 'Elle augmente la pression sur la hanche', 'Elle empêche de respirer', 'Elle est plus rapide à installer'],
    ["L'humidité (urine, transpiration) favorise les escarres car :", 'Elle fragilise la peau', 'Elle hydrate la peau et la rend plus résistante aux frottements', 'Elle n\'a aucun effet', 'Elle protège la peau'],
    ["Les frottements et le cisaillement surviennent notamment quand :", 'On fait glisser le patient sur le drap', 'On utilise un drap de glisse', "On soulève le patient à deux à l'aide d'un drap de glisse", "Le patient marche seul jusqu'au fauteuil"],
    ["Masser une rougeur persistante au niveau d'un point d'appui :", 'Est déconseillé', 'Est recommandé fortement', 'Est obligatoire', "Est recommandé avec de l'alcool pour stimuler la circulation sanguine"],
    ["Une bonne alimentation et une hydratation suffisante :", 'Font partie de la prévention', "N'ont aucun rôle", 'Augmentent le risque', 'Sont réservées aux sportifs'],
    ["Les talons d'un patient alité peuvent être protégés en :", 'Les mettant en décharge', 'Les posant directement sur le matelas', "Les entourant de bandes serrées et d'une épaisse couche de coton", 'Les laissant hors du lit'],
    ["L'évaluation du risque d'escarre se fait :", "Dès l'admission, puis régulièrement", 'Une seule fois à la sortie', 'Uniquement si une plaie apparaît à la peau', "Uniquement si une rougeur ou une plaie apparaît sur un point d'appui"],
    ["Les changements de position doivent être :", 'Planifiés et notés', 'Faits sans noter', 'Faits une fois par semaine', 'Évités la nuit dans tous les cas, pour préserver le sommeil du patient'],
    ["Le drap du lit doit être :", 'Tendu, sans plis', "Plié en plusieurs épaisseurs sous le bassin pour absorber l'humidité", 'Rugueux', 'Mouillé pour rafraîchir'],
    ["Un patient très maigre a un risque d'escarre :", 'Augmenté', 'Diminué, car son poids exerce moins de pression sur le matelas', 'Nul', 'Identique à tous'],
    ["L'aide-soignant qui découvre une phlyctène au talon :", 'La signale et met le talon en décharge', 'La perce avec une aiguille stérile puis applique un pansement sec', 'Applique du talc', 'N\'en parle pas'],
    ["L'immobilité prolongée favorise :", 'Escarres, phlébites, enraidissement', 'Uniquement la perte de poids', 'Une meilleure circulation sanguine grâce au repos des muscles', 'La guérison rapide'],
    ["Un coussin en forme de « bouée » au fauteuil :", 'Est déconseillé', 'Est le meilleur dispositif pour répartir la pression au niveau du sacrum', 'Est obligatoire', 'Prévient toutes les escarres'],
  ],
  'Manutention des patients': [
    ["Avant de mobiliser un patient lourd seul(e), il faut :", "Évaluer la situation et demander de l'aide ou utiliser une aide technique", 'Le porter seul(e) rapidement', 'Le tirer par les bras en gardant le dos bien droit pour ne pas se blesser', 'Attendre qu\'il tombe'],
    ["Le drap de glisse sert à :", 'Déplacer le patient sans frottement', 'Couvrir le patient', 'Faire la toilette', "Protéger le matelas de l'urine et de la transpiration du patient"],
    ["Le lit doit être réglé, pour un soin, à une hauteur :", 'Permettant au soignant de travailler le dos droit', 'La plus basse possible', 'La plus haute possible', "Peu importe, le soignant s'adapte en se penchant"],
    ["Pour aider un patient à se lever du lit, on l'encourage d'abord à :", "S'asseoir au bord du lit un moment", 'Se lever directement en une fois, pour éviter de le fatiguer', 'Sauter du lit', 'Se lever les yeux fermés'],
    ["Un patient qui fait un malaise lors du lever doit être :", 'Recouché ou assis en sécurité et surveillé', 'Laissé debout', 'Tiré par le bras', 'Maintenu debout en le soutenant'],
    ["Le verticalisateur est utile pour un patient :", 'Qui peut prendre appui sur ses jambes', 'Totalement autonome', 'Qui ne peut pas du tout porter son poids ni tenir sa tête', 'Qui marche seul'],
    ["Pendant un transfert, il est important de :", 'Expliquer et faire participer', 'Faire vite et sans parler pour ne pas le stresser inutilement', 'Le surprendre', 'Le tirer par le cou'],
    ["Le fauteuil roulant est approché du lit :", 'Freins serrés, repose-pieds relevés', 'Freins desserrés', 'Freins desserrés et repose-pieds baissés pour poser les pieds du patient', 'Le plus loin possible du lit, freins desserrés'],
    ["Les troubles musculo-squelettiques du soignant sont favorisés par :", 'Les postures penchées et le port de charges', "L'utilisation d'aides techniques et le travail en binôme lors des transferts", 'Le travail à deux', 'Le lit à bonne hauteur'],
    ["Pour tourner un patient sur le côté, on :", "Le fait rouler vers soi, après l'avoir prévenu", 'Le pousse loin de soi, au bord opposé du lit, sans le prévenir pour aller vite', 'Le tire par un bras', 'Le soulève seul à bout de bras'],
    ["Avant d'utiliser un lève-personne, on vérifie :", 'Sangle, charge maximale, fonctionnement', 'Uniquement la propreté de la sangle et la charge de la batterie', 'Uniquement la couleur et la propreté de la sangle', 'Que le patient est debout et peut marcher seul'],
    ["Un patient opéré de la hanche doit être mobilisé :", 'En respectant les consignes de mouvements interdits données par le chirurgien', "Comme n'importe quel patient, la prothèse étant solide dès la pose", 'Jamais avant trois semaines', 'En lui croisant les jambes'],
    ["La marche accompagnée d'un patient fragile se fait :", 'À côté, en retrait, côté faible', 'Devant lui, en le tenant par les deux mains tendues pour le guider', 'Derrière lui à plusieurs mètres', 'En le laissant seul pour stimuler son autonomie'],
    ["Le chariot de soins ou de linge se pousse plutôt :", 'Dos droit, bras près du corps', 'En le tirant derrière soi, penché en avant pour avoir plus de force', "D'une seule main, en se penchant sur le côté", 'En le tirant derrière soi, dos penché'],
    ["La mobilisation précoce des patients sert à prévenir :", "Les complications de l'immobilité", 'La guérison', 'L\'autonomie', 'Les chutes, en limitant les déplacements du patient au maximum'],
    ["Un patient au sol après une chute ne doit être relevé :", "Qu'après évaluation de son état", 'Immédiatement en le tirant par les bras', 'Jamais', "Immédiatement par un seul soignant, pour qu'il ne prenne pas froid au sol"],
  ],
  'Aide aux repas et hydratation': [
    ["Avant le repas, on installe le patient :", 'Assis, mains lavées, prothèses en place', 'Allongé à plat, la tête tournée sur le côté pour éviter les fausses routes', 'Sans ses lunettes', 'Sans lui laver les mains'],
    ["Le régime alimentaire prescrit (sans sel, diabétique, mixé) doit être :", 'Vérifié pour chaque plateau', 'Changé selon les goûts du soignant', 'Ignoré', 'Remplacé par le régime du voisin'],
    ["Une personne qui a des difficultés pour couper ses aliments :", 'Est aidée en favorisant son autonomie (couverts adaptés, aide partielle)', 'Reçoit uniquement des repas liquides ou mixés', 'Est nourrie entièrement par le soignant pour gagner du temps', 'Doit attendre la famille pour être aidée au repas'],
    ["Aider un patient à manger se fait :", 'Assis, à son rythme', "Debout à côté du lit, par grosses bouchées pour qu'il ne se fatigue pas", 'En parlant au téléphone', 'En le pressant'],
    ["Les signes de fausse route sont :", 'Toux, voix mouillée, gêne respiratoire pendant le repas', 'Bon appétit et repas terminé rapidement', 'Somnolence et digestion lente après le repas', 'Somnolence et digestion lente après le repas uniquement'],
    ["Pour une personne âgée qui boit peu, on peut :", 'Proposer régulièrement des boissons variées, gélifiées si besoin', 'Attendre qu\'elle réclame', "Lui faire boire un grand verre d'eau le soir, avant le coucher", 'Supprimer les boissons le soir pour éviter les levers nocturnes'],
    ["Le relevé des ingesta consiste à :", "Noter ce qu'il a bu et mangé", 'Peser le plateau vide', 'Noter le menu affiché', 'Noter le nom du cuisinier'],
    ["Un patient à jeun pour un examen :", 'Ne reçoit ni repas ni boisson', 'Peut manger léger', 'Peut boire un café', 'Peut manger s\'il a faim'],
    ["Après le repas, le patient qui a des troubles de la déglutition reste :", 'Assis environ 30 minutes', 'Allongé à plat immédiatement pour faciliter la digestion', 'Allongé à plat immédiatement après', 'Allongé sur le ventre pour digérer'],
    ["Une alimentation enrichie consiste à :", 'Plus de calories et protéines, même volume', 'Ajouter de l\'eau', 'Supprimer les protéines', 'Augmenter les portions servies, en doublant le volume de chaque plat'],
    ["Un patient qui ne mange pas plusieurs repas de suite :", 'Est signalé', "Est laissé tranquille : l'appétit revient toujours spontanément", 'Est forcé à manger', 'Est privé de dessert'],
    ["L'eau gélifiée est utile pour :", 'Les fausses routes aux liquides', 'Les patients déshydratés qui ne peuvent pas avoir de perfusion', 'Remplacer les repas', 'Les nourrissons de moins d\'un mois'],
    ["Les plateaux repas sont distribués :", "En respectant les règles d'hygiène et en vérifiant le nom et le régime", 'Au hasard', "Dans l'ordre des chambres sans vérifier", 'Après les avoir posés au sol'],
    ["Le respect des habitudes et des convictions alimentaires du patient :", 'Fait partie de la qualité des soins', 'N\'a aucune importance', "Est impossible à l'hôpital, où un menu unique est servi à tous", 'Est impossible à respecter dans un établissement de santé'],
    ["Une bouche sèche chez un patient en fin de vie se soulage par :", 'Des soins de bouche fréquents', 'Une perfusion systématique', 'Rien', 'Un jeûne'],
    ["La surveillance de l'hydratation chez la personne âgée inclut :", 'Diurèse, urines, muqueuses, comportement', 'Uniquement la couleur des cheveux', 'Uniquement la pesée annuelle et la mesure de la tension artérielle', 'Uniquement le poids annuel et la tension artérielle'],
  ],
};
