/** Questions supplémentaires – aide-soignant(e) / auxiliaire. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_AIDE: Record<string, QuestionBrute[]> = {
  "Soins d'hygiène et de confort": [
    ["La température de l'eau pour une toilette est vérifiée :", 'Avec le coude ou un thermomètre, pour éviter les brûlures', 'Uniquement au toucher de la main', 'En demandant au patient après coup', 'Elle n\'a pas d\'importance'],
    ["Pour la toilette intime, on utilise :", 'Un gant et une serviette dédiés, du haut vers le bas (de l\'avant vers l\'arrière)', 'Le même gant que pour le visage', 'De l\'alcool', 'Un gant d\'un autre patient'],
    ["Les soins de bouche d'un patient porteur d'une prothèse dentaire comprennent :", 'Le nettoyage de la prothèse et de la bouche', 'Le port de la prothèse jour et nuit sans nettoyage', 'Le rangement de la prothèse dans un mouchoir', 'Rien'],
    ["Le shampoing au lit nécessite :", 'Une protection du lit et une installation confortable du patient', 'De mouiller tout le lit', 'De faire asseoir un patient qui ne peut pas', 'Aucune préparation'],
    ["La réfection d'un lit occupé se fait :", 'En tournant le patient de côté, avec deux soignants si besoin', 'En faisant lever un patient qui ne le peut pas', 'Sans prévenir le patient', 'En secouant les draps'],
    ["Le linge sale est :", 'Déposé directement dans le sac à linge, sans le poser au sol ni le secouer', 'Posé sur le lit d\'à côté', 'Jeté par terre', 'Secoué dans le couloir'],
    ["Un patient incontinent doit bénéficier :", 'De changes réguliers et d\'une toilette pour préserver la peau', 'D\'une limitation des boissons', 'D\'un change une fois par jour', 'D\'aucun soin particulier'],
    ["Le rasage d'un patient sous anticoagulant se fait de préférence :", 'Au rasoir électrique', 'Au rasoir à lame', 'Avec des ciseaux', 'Ce n\'est jamais possible'],
    ["Pendant la toilette, l'aide-soignant observe notamment :", 'L\'état de la peau, l\'autonomie, l\'humeur et la douleur', 'Uniquement la couleur des draps', 'Uniquement l\'heure', 'Rien'],
    ["Les ongles d'un patient diabétique :", 'Ne sont pas coupés par l\'aide-soignant sans avis (risque de plaie)', 'Sont coupés très court avec des ciseaux pointus', 'Sont limés avec une lime métallique agressive', 'Ne nécessitent aucune attention'],
    ["L'installation au fauteuil d'un patient comprend :", 'Une position confortable, des pieds bien posés et la sonnette à portée', 'Le laisser glisser', 'Le laisser sans sonnette', 'Le laisser plusieurs heures sans changer de position'],
    ["La pudeur d'un patient pendant le change est respectée en :", 'Fermant la porte, en tirant le rideau et en couvrant le corps', 'Laissant la porte ouverte', 'Faisant le soin devant les visiteurs', 'Ne lui parlant pas'],
    ["Un patient en fin de vie a besoin en priorité :", 'De soins de confort, de soins de bouche et d\'une présence', 'D\'une toilette complète toutes les heures', 'De rester seul', 'D\'être réveillé souvent'],
    ["L'hygiène des mains de l'aide-soignant est réalisée :", 'Avant et après chaque soin, et après avoir retiré les gants', 'Uniquement en fin de journée', 'Uniquement si les mains sont sales', 'Jamais avec des gants'],
    ["Un bain ou une douche chez un patient âgé fragile impose :", 'Une surveillance pour prévenir les chutes et les malaises', 'De le laisser seul', 'Une eau très chaude', 'Une durée la plus longue possible'],
  ],
  'Prévention des escarres': [
    ["Une escarre est due principalement à :", 'Une pression prolongée sur une zone d\'appui', 'Une allergie', 'Une infection virale', 'Un manque de soleil'],
    ["Un matelas anti-escarres :", 'Répartit les pressions mais ne remplace pas les changements de position', 'Supprime le besoin de surveiller la peau', 'Est inutile', 'Doit être recouvert de plusieurs couches de draps'],
    ["Pour un patient assis au fauteuil, la zone la plus exposée est :", 'Les ischions (fesses)', 'Le front', 'Les mains', 'Les genoux'],
    ["La position semi-latérale à 30° est recommandée car :", 'Elle évite l\'appui direct sur le trochanter et le sacrum', 'Elle augmente la pression sur la hanche', 'Elle empêche de respirer', 'Elle est plus rapide à installer'],
    ["L'humidité (urine, transpiration) favorise les escarres car :", 'Elle fragilise la peau', 'Elle hydrate la peau', 'Elle n\'a aucun effet', 'Elle protège la peau'],
    ["Les frottements et le cisaillement surviennent notamment quand :", 'On fait glisser le patient sur le drap au lieu de le soulever', 'On utilise un drap de glisse', 'On soulève le patient à deux', 'Le patient marche'],
    ["Masser une rougeur persistante au niveau d'un point d'appui :", 'Est déconseillé : cela peut aggraver les lésions', 'Est recommandé fortement', 'Est obligatoire', 'Se fait avec de l\'alcool'],
    ["Une bonne alimentation et une hydratation suffisante :", 'Font partie de la prévention des escarres', 'N\'ont aucun rôle', 'Augmentent le risque', 'Sont réservées aux sportifs'],
    ["Les talons d'un patient alité peuvent être protégés en :", 'Les mettant en décharge (coussin sous les mollets)', 'Les posant directement sur le matelas', 'Les entourant de bandes serrées', 'Les laissant hors du lit'],
    ["L'évaluation du risque d'escarre se fait :", "Dès l'admission puis régulièrement", 'Une seule fois à la sortie', 'Jamais', 'Uniquement si une plaie apparaît'],
    ["Les changements de position doivent être :", 'Planifiés, réalisés et notés (traçabilité)', 'Faits sans noter', 'Faits une fois par semaine', 'Évités la nuit dans tous les cas'],
    ["Le drap du lit doit être :", 'Bien tendu, sans plis ni miettes', 'Plié en plusieurs épaisseurs', 'Rugueux', 'Mouillé pour rafraîchir'],
    ["Un patient très maigre a un risque d'escarre :", 'Augmenté (saillies osseuses plus exposées)', 'Diminué', 'Nul', 'Identique à tous'],
    ["L'aide-soignant qui découvre une phlyctène au talon :", 'La signale à l\'infirmier et met le talon en décharge', 'La perce avec une aiguille', 'Applique du talc', 'N\'en parle pas'],
    ["L'immobilité prolongée favorise :", 'Les escarres, mais aussi les phlébites et l\'enraidissement', 'Uniquement la perte de poids', 'Une meilleure circulation', 'La guérison rapide'],
    ["Un coussin en forme de « bouée » au fauteuil :", 'Est déconseillé car il crée une zone de compression', 'Est le meilleur dispositif', 'Est obligatoire', 'Prévient toutes les escarres'],
  ],
  'Manutention des patients': [
    ["Avant de mobiliser un patient lourd seul(e), il faut :", 'Évaluer la situation et demander de l\'aide ou utiliser une aide technique', 'Le porter seul(e) rapidement', 'Le tirer par les bras', 'Attendre qu\'il tombe'],
    ["Le drap de glisse sert à :", 'Remonter ou tourner un patient dans le lit en limitant les frottements', 'Couvrir le patient', 'Faire la toilette', 'Protéger le matelas de l\'urine'],
    ["Le lit doit être réglé, pour un soin, à une hauteur :", 'Permettant au soignant de travailler le dos droit', 'La plus basse possible', 'La plus haute possible', 'Peu importe'],
    ["Pour aider un patient à se lever du lit, on l'encourage d'abord à :", 'S\'asseoir au bord du lit, pieds au sol, quelques instants', 'Se lever brusquement', 'Sauter du lit', 'Se lever les yeux fermés'],
    ["Un patient qui fait un malaise lors du lever doit être :", 'Recouché ou assis en sécurité et surveillé', 'Laissé debout', 'Tiré par le bras', 'Laissé seul'],
    ["Le verticalisateur est utile pour un patient :", 'Qui peut prendre appui sur ses jambes mais pas se lever seul', 'Totalement autonome', 'Qui ne peut pas du tout porter son poids', 'Qui marche seul'],
    ["Pendant un transfert, il est important de :", 'Expliquer chaque étape au patient et le faire participer', 'Faire vite sans parler', 'Le surprendre', 'Le tirer par le cou'],
    ["Le fauteuil roulant est approché du lit :", 'Freins serrés, repose-pieds relevés ou retirés', 'Freins desserrés', 'Repose-pieds baissés pendant le transfert', 'Le plus loin possible'],
    ["Les troubles musculo-squelettiques du soignant sont favorisés par :", 'Les postures penchées et le port de charges lourdes répété', 'L\'utilisation d\'aides techniques', 'Le travail à deux', 'Le lit à bonne hauteur'],
    ["Pour tourner un patient sur le côté, on :", 'Le fait rouler vers soi en plaçant ses bras et jambes, après avoir prévenu', 'Le pousse loin de soi en bout de lit', 'Le tire par un bras', 'Le soulève seul à bout de bras'],
    ["Avant d'utiliser un lève-personne, on vérifie :", 'La sangle adaptée, la charge maximale et le bon fonctionnement', 'Uniquement la couleur de la sangle', 'Rien', 'Que le patient est debout'],
    ["Un patient opéré de la hanche doit être mobilisé :", 'En respectant les consignes de mouvements interdits données par le chirurgien', 'Comme n\'importe quel patient', 'Jamais', 'En lui croisant les jambes'],
    ["La marche accompagnée d'un patient fragile se fait :", 'À côté de lui, légèrement en retrait, du côté le plus faible', 'En le tenant par la main tendue devant lui', 'Derrière lui à plusieurs mètres', 'En le laissant seul'],
    ["Le chariot de soins ou de linge se pousse plutôt :", 'En gardant le dos droit, bras près du corps', 'En le tirant penché en avant', 'D\'une seule main', 'En courant'],
    ["La mobilisation précoce des patients sert à prévenir :", 'Les complications de l\'immobilité (phlébite, escarre, pneumopathie)', 'La guérison', 'L\'autonomie', 'L\'appétit'],
    ["Un patient au sol après une chute ne doit être relevé :", "Qu'après évaluation de son état (douleur, conscience) et avec des moyens adaptés", 'Immédiatement en le tirant par les bras', 'Jamais', 'Par un seul soignant sans évaluation'],
  ],
  'Aide aux repas et hydratation': [
    ["Avant le repas, on installe le patient :", 'Assis, confortablement, mains lavées, prothèses dentaires et lunettes en place', 'Allongé à plat', 'Sans ses lunettes', 'Sans lui laver les mains'],
    ["Le régime alimentaire prescrit (sans sel, diabétique, mixé) doit être :", 'Vérifié pour chaque plateau', 'Changé selon les goûts du soignant', 'Ignoré', 'Remplacé par le régime du voisin'],
    ["Une personne qui a des difficultés pour couper ses aliments :", 'Est aidée en favorisant son autonomie (couverts adaptés, aide partielle)', 'Ne mange pas', 'Est nourrie entièrement sans lui demander', 'Doit attendre la famille'],
    ["Aider un patient à manger se fait :", 'Assis à sa hauteur, à son rythme, par petites quantités', 'Debout, rapidement', 'En parlant au téléphone', 'En le pressant'],
    ["Les signes de fausse route sont :", 'Toux, voix mouillée, gêne respiratoire pendant le repas', 'Bon appétit', 'Sourire', 'Somnolence après le repas uniquement'],
    ["Pour une personne âgée qui boit peu, on peut :", 'Proposer régulièrement des boissons variées, gélifiées si besoin', 'Attendre qu\'elle réclame', 'Lui donner un seul grand verre le soir', 'Supprimer les boissons'],
    ["Le relevé des ingesta consiste à :", 'Noter ce que le patient a bu et mangé', 'Peser le plateau vide', 'Noter le menu affiché', 'Noter le nom du cuisinier'],
    ["Un patient à jeun pour un examen :", 'Ne reçoit ni repas ni boisson, selon la consigne médicale', 'Peut manger léger', 'Peut boire un café', 'Peut manger s\'il a faim'],
    ["Après le repas, le patient qui a des troubles de la déglutition reste :", 'Assis ou demi-assis environ 30 minutes', 'Allongé à plat immédiatement', 'Debout pendant 2 heures', 'Sur le ventre'],
    ["Une alimentation enrichie consiste à :", 'Augmenter les calories et protéines sans augmenter le volume (fromage, œuf, poudre de lait)', 'Ajouter de l\'eau', 'Supprimer les protéines', 'Diminuer les portions sans compenser'],
    ["Un patient qui ne mange pas plusieurs repas de suite :", 'Est signalé à l\'infirmier et à la diététicienne', 'Est laissé tranquille sans rien dire', 'Est forcé à manger', 'Est privé de dessert'],
    ["L'eau gélifiée est utile pour :", 'Les patients qui font des fausses routes aux liquides', 'Les patients qui ont soif après le sport', 'Remplacer les repas', 'Les nourrissons de moins d\'un mois'],
    ["Les plateaux repas sont distribués :", 'En respectant les règles d\'hygiène et en vérifiant le nom et le régime', 'Au hasard', 'Sans se laver les mains', 'Après les avoir posés au sol'],
    ["Le respect des habitudes et des convictions alimentaires du patient :", 'Fait partie d\'une prise en charge de qualité', 'N\'a aucune importance', 'Est interdit à l\'hôpital', 'Est réservé aux enfants'],
    ["Une bouche sèche chez un patient en fin de vie se soulage par :", 'Des soins de bouche fréquents et une humidification', 'Une perfusion systématique', 'Rien', 'Un jeûne'],
    ["La surveillance de l'hydratation chez la personne âgée inclut :", 'La diurèse, l\'aspect des urines et des muqueuses, le comportement', 'Uniquement la couleur des cheveux', 'Uniquement le poids annuel', 'Rien'],
  ],
};
