/** Questions supplémentaires – anesthésie-réanimation. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_ANESTHESIE: Record<string, QuestionBrute[]> = {
  'Anesthésie générale': [
    ["Les trois composantes classiques de l'anesthésie générale sont :", 'Hypnose, analgésie, curarisation si besoin', 'Fièvre, toux et douleur', 'Hydratation, nutrition et marche', 'Sédation légère, anesthésie locale et ventilation spontanée sans surveillance'],
    ["Un curare provoque :", 'Une paralysie musculaire', 'Un sommeil profond et une analgésie, sans effet sur la respiration', 'Une analgésie seule', 'Une augmentation de la vigilance'],
    ["L'induction en « séquence rapide » est indiquée chez un patient :", "À l'estomac plein", 'À jeun depuis la veille sans risque', 'Uniquement chez les enfants, pour raccourcir le temps passé au bloc', 'Uniquement pour une anesthésie locale'],
    ["La vérification de l'appareil d'anesthésie se fait :", 'Avant chaque programme', 'Une fois par an, lors de la maintenance réalisée par le fabricant', 'Uniquement en cas de panne', 'Par le patient'],
    ["L'hyperthermie maligne est une complication rare déclenchée notamment par :", 'Halogénés et succinylcholine', 'Le paracétamol injectable et les antibiotiques administrés au bloc', 'Le sérum physiologique', 'L\'oxygène'],
    ["Le traitement spécifique de l'hyperthermie maligne est :", 'Le dantrolène', 'L\'insuline', 'La naloxone', 'La vitamine K'],
    ["Un patient à risque de nausées et vomissements postopératoires peut recevoir :", 'Une prophylaxie antiémétique', 'Un repas avant l\'intervention', 'Une dose de morphine plus élevée, pour éviter que la douleur ne provoque des nausées', 'Aucune prévention'],
    ["La sévoflurane est :", 'Un halogéné inhalé', "Un curare d'action rapide utilisé pour l'intubation", 'Un morphinique de synthèse', 'Un curare non dépolarisant'],
    ["La kétamine a pour particularité de :", 'Préserver la ventilation spontanée', 'Provoquer une paralysie musculaire nécessitant toujours une intubation', "Être un curare de courte durée d'action", 'Être un antiémétique utilisé en salle de réveil'],
    ["Le score ASA sert à évaluer :", "L'état de santé général du patient avant l'anesthésie (risque anesthésique)", 'La douleur postopératoire prévisible', "La difficulté prévisible de l'intubation à partir de l'ouverture de bouche", 'La durée de l\'intervention'],
    ["Avant l'induction, l'équipe vérifie notamment :", 'Identité, jeûne, allergies, matériel', 'La couleur de la blouse', 'Le menu du soir', "Rien de plus : la consultation d'anesthésie a déjà tout vérifié quelques jours avant"],
    ["L'anesthésie locorégionale (rachianesthésie, péridurale) consiste à :", 'Anesthésier une région du corps', 'Endormir le patient par voie intraveineuse, sans intubation, pour une courte intervention', 'Bloquer tous les muscles du corps', 'Donner un antalgique par la bouche'],
    ["Une complication possible de la rachianesthésie est :", 'Une hypotension artérielle', 'Une hyperglycémie systématique', 'Une fracture', 'Une perte de cheveux'],
    ["La toxicité des anesthésiques locaux peut se manifester par :", 'Des signes neurologiques et cardiaques', 'Une fièvre isolée', 'Une diarrhée et des vomissements répétés', "Une simple rougeur au point d'injection, sans autre conséquence"],
  ],
  'Intubation et ventilation': [
    ["La laryngoscopie permet de :", 'Visualiser la glotte', 'Mesurer la tension', "Aspirer le contenu de l'estomac avant l'induction de l'anesthésie", 'Prendre la température'],
    ["Une intubation sélective dans la bronche souche droite se manifeste par :", 'Un murmure vésiculaire diminué à gauche', 'Une hypertension isolée', 'Une fièvre', 'Une diminution du bruit respiratoire à droite et un thorax qui se soulève mieux à gauche'],
    ["Le ballonnet de la sonde d'intubation sert à :", "Assurer l'étanchéité", 'Maintenir la sonde en place dans la trachée, la fixation externe devenant inutile', 'Mesurer la température', 'Humidifier l\'air'],
    ["La pression du ballonnet est contrôlée pour éviter :", 'Les lésions de la trachée', 'Les allergies', 'La fièvre', 'L\'hypoglycémie'],
    ["Le masque laryngé est :", 'Un dispositif supraglottique utilisé pour ventiler sans intubation trachéale', 'Un masque à oxygène simple', 'Un masque chirurgical', "Une sonde introduite dans la trachée, plus courte qu'une sonde d'intubation"],
    ["Une intubation difficile imprévue nécessite :", "D'appeler de l'aide et de suivre l'algorithme", "De multiplier rapidement les tentatives de laryngoscopie avant d'appeler de l'aide", "D'arrêter l'oxygène et de retirer la sonde d'intubation", 'De réveiller le chirurgien'],
    ["Le volume courant habituellement réglé chez l'adulte en ventilation protectrice est d'environ :", '6 à 8 mL/kg de poids idéal', '20 mL/kg', '12 à 15 mL/kg', '2 à 3 mL/kg'],
    ["La PEP (pression expiratoire positive) sert à :", 'Maintenir les alvéoles ouvertes', 'Augmenter la fréquence cardiaque', 'Endormir le patient', "Diminuer la pression dans les voies aériennes pendant l'inspiration"],
    ["Une alarme de pression haute sur le respirateur peut indiquer :", 'Sonde coudée, sécrétions, bronchospasme', 'Une déconnexion du circuit ou une fuite au niveau du ballonnet', 'Une batterie chargée', 'Un patient qui dort bien'],
    ["Une alarme de pression basse sur le respirateur évoque en premier :", 'Une déconnexion ou une fuite', 'Un bronchospasme ou une sonde coudée par la morsure du patient', 'Un patient trop sédaté', 'Une fièvre'],
    ["L'aspiration trachéale chez un patient intubé se fait :", 'Aseptique, sonde adaptée, durée courte', 'Avec la même sonde pour plusieurs patients', 'Pendant plusieurs minutes, pour retirer toutes les sécrétions en une seule fois', 'Sans oxygénation préalable même si le patient désature'],
    ["La position de la sonde d'intubation est notée en centimètres :", 'Aux dents ou à la commissure', 'Au niveau du sternum, sur la ligne médiane', "Au niveau du lobe de l'oreille du patient", "Au niveau de la narine, quelle que soit la voie d'intubation"],
    ["Le bronchospasme se manifeste par :", 'Des sifflements, une difficulté à ventiler et une baisse de la saturation', "Une baisse des pressions d'insufflation et une augmentation du CO2 expiré", 'Une diarrhée et des douleurs abdominales aiguës', 'Une augmentation de la diurèse'],
    ["Avant l'extubation, on vérifie notamment :", 'Réveil, ventilation efficace, décurarisation', 'Uniquement l\'heure', 'Que le patient a mangé', 'Uniquement que la saturation est supérieure à 90 % sous oxygène pur'],
    ["La fraction inspirée en oxygène (FiO2) de l'air ambiant est d'environ :", '21 %', '50 %', '100 %', '5 %'],
  ],
  'Monitorage hémodynamique': [
    ["La pression artérielle invasive est mesurée grâce à :", 'Un cathéter artériel', 'Un brassard au bras automatique', 'Un thermomètre tympanique', 'Un brassard automatique gonflé toutes les minutes au bras opposé'],
    ["Le capteur de pression d'une ligne artérielle doit être placé :", "Au niveau de l'oreillette droite", 'Au niveau du sol', 'Au-dessus de la tête', 'Au niveau du point de ponction artérielle, au poignet du patient'],
    ["Une pression artérielle moyenne inférieure à 65 mmHg chez l'adulte en réanimation est en général :", 'Insuffisante pour perfuser les organes', 'Idéale', 'Élevée', 'Sans importance'],
    ["La capnographie mesure :", 'Le CO2 dans l\'air expiré', "L'oxygène dans le sang veineux", 'La glycémie', 'La température'],
    ["Une chute brutale du CO2 expiré pendant une anesthésie peut signaler :", 'Une déconnexion, une embolie, un arrêt', 'Une amélioration de l\'état du patient', 'Une hyperventilation volontaire du patient en cours de réveil, sans gravité', 'Un réveil normal et une reprise de la respiration'],
    ["Le monitorage de la curarisation (train de quatre) sert à :", 'Évaluer la curarisation', 'Mesurer la tension', 'Évaluer la profondeur du sommeil anesthésique', 'Mesurer la diurèse'],
    ["La pression veineuse centrale se mesure à l'aide :", "D'un cathéter veineux central", 'D\'un cathéter périphérique au pied', 'D\'un brassard', 'D\'une sonde urinaire'],
    ["Sur l'ECG, une fibrillation ventriculaire est :", 'Un rythme choquable', 'Un rythme normal', 'Une tachycardie rapide mais bien tolérée, à surveiller sans traitement', 'Une bradycardie sans gravité'],
    ["Une asystolie est :", "Une absence d'activité électrique cardiaque (rythme non choquable)", 'Une tachycardie', 'Une tachycardie rapide et régulière', 'Une hypertension'],
    ["La température centrale se surveille au bloc pour prévenir :", "L'hypothermie", "Les réactions allergiques aux produits d'anesthésie", 'Le diabète insulinodépendant', 'La fracture du col'],
    ["La diurèse horaire est un reflet :", 'De la perfusion rénale', 'De la douleur', 'De la profondeur du sommeil', 'De la fonction respiratoire'],
    ["L'index bispectral (BIS) sert à évaluer :", "La profondeur de l'hypnose", 'Le niveau de curarisation des muscles', 'La fréquence respiratoire du patient', 'Le débit urinaire horaire en salle'],
    ["Les alarmes du scope doivent être :", 'Adaptées au patient, jamais coupées', 'Toujours désactivées pour le calme', 'Réglées avec les mêmes seuils pour tous les patients du service', 'Ignorées la nuit pour ne pas réveiller les patients'],
    ["Une hypotension après l'induction est souvent traitée en première intention par :", 'Remplissage et/ou vasopresseur', 'Un arrêt de l\'oxygène', 'Un antibiotique', "Un diurétique pour éliminer l'excès de liquide perfusé pendant l'induction"],
    ["Les électrodes de l'ECG à 3 brins se placent classiquement :", 'Rouge à droite, jaune à gauche, verte en bas à gauche', 'Rouge à gauche sous la clavicule, jaune à droite sous la clavicule, verte en bas à droite', 'Sur le dos uniquement', 'Sur le visage'],
    ["Une saturation qui chute alors que la courbe de pouls est de mauvaise qualité doit faire :", 'Vérifier capteur et patient', "Ignorer l'alarme si le patient paraît bien", "Augmenter l'oxygène sans regarder le patient, la valeur affichée faisant foi", 'Arrêter l\'oxygène'],
  ],
  'Surveillance post-interventionnelle': [
    ["En salle de surveillance post-interventionnelle (SSPI), la surveillance porte sur :", 'Conscience, respiration, circulation, douleur', 'Uniquement la douleur et la température cutanée', 'Uniquement la tension artérielle et la diurèse', 'Uniquement la tension et la saturation, le reste étant surveillé dans le service'],
    ["Un patient ronfle bruyamment en SSPI avec une saturation qui baisse. Il faut penser à :", 'Une obstruction des voies aériennes (subluxer la mâchoire, oxygène, alerter)', "Un sommeil réparateur normal après l'anesthésie, sans action particulière", "Une simple fatigue liée à l'anesthésie", "Une diurèse abondante après l'intervention"],
    ["Des nausées et vomissements en SSPI exposent à :", "Un risque d'inhalation", 'Une meilleure récupération', 'Un réveil plus rapide, car les vomissements éliminent les produits anesthésiques', 'Une baisse de la douleur'],
    ["Un globe vésical en SSPI se manifeste par :", 'Agitation, douleur, masse sus-pubienne', "Une diarrhée et des nausées après l'anesthésie", 'Une diarrhée et des douleurs abdominales diffuses, sans masse palpable', 'Une baisse de la température et des frissons'],
    ["La morphine titrée en SSPI consiste à :", 'Donner de petites doses répétées', 'Donner une forte dose unique sans surveillance', 'Ne jamais traiter la douleur', "Donner une forte dose unique dès l'arrivée, pour éviter de réveiller le patient ensuite"],
    ["Un saignement important sur le pansement en SSPI doit faire :", "Prévenir l'anesthésiste et le chirurgien", "Renforcer le pansement par-dessus et surveiller jusqu'au retour dans le service", 'Attendre le lendemain', 'Retirer les drains et refaire un pansement compressif'],
    ["La surveillance après une rachianesthésie comprend notamment :", 'La motricité et la sensibilité des jambes', 'Uniquement la température et la couleur des pieds', "Uniquement la température, la rachianesthésie n'ayant pas d'effet sur la tension", 'La glycémie capillaire et la diurèse uniquement'],
    ["Le frisson postopératoire augmente :", "La consommation d'oxygène", 'La glycémie uniquement', 'La diurèse et la température centrale de façon durable', "La vision et l'audition du patient"],
    ["Les critères de sortie de SSPI reposent sur :", "Un score validé et l'avis de l'anesthésiste", "Une durée fixe de 30 minutes en SSPI, quelle que soit l'intervention", 'La demande de la famille', 'Le nombre de lits disponibles uniquement'],
    ["Une décurarisation incomplète peut se manifester par :", 'Faiblesse musculaire, gêne respiratoire', 'Une hyperactivité', 'Une fièvre', 'Une hypertension isolée'],
    ["Un patient agité et confus au réveil : avant tout, on recherche :", 'Une hypoxie, une douleur, un globe vésical ou une hypoglycémie', 'Un problème administratif ou une contrariété familiale', 'Un problème administratif', 'Rien, on le sédate sans chercher'],
    ["La surveillance de l'enfant en SSPI nécessite :", "Des normes adaptées à l'âge", "Les mêmes normes que l'adulte, sans présence des parents pour éviter de les inquiéter", 'Aucune surveillance particulière', 'Un jeûne prolongé'],
    ["Les drains chirurgicaux sont surveillés pour :", "La quantité et l'aspect de ce qui s'écoule", 'Leur couleur décorative', 'Leur prix', "Le bruit qu'ils font et leur longueur"],
    ["Un patient opéré sous anesthésie générale peut en général boire :", 'Une fois bien réveillé, selon la prescription', 'Immédiatement à l\'arrivée en SSPI, encore endormi', "Jamais avant 24 heures, quelle que soit l'intervention et l'état de réveil", 'Uniquement de l\'alcool'],
    ["Les transmissions à la sortie de SSPI comprennent :", 'Intervention, anesthésie, antalgiques, constantes, consignes', "Le nom du patient et l'intervention, le reste figurant dans le dossier informatique", 'Uniquement l\'heure', 'Rien si tout s\'est bien passé'],
    ["Une SpO2 à 88 % en SSPI chez un patient sans pathologie respiratoire impose :", 'Stimuler, oxygéner, vérifier les voies aériennes', 'Couper l\'alarme', 'Attendre 30 minutes', 'Faire sortir le patient de SSPI'],
  ],
};
