/** Questions supplémentaires – anesthésie-réanimation. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_ANESTHESIE: Record<string, QuestionBrute[]> = {
  'Anesthésie générale': [
    ["Les trois composantes classiques de l'anesthésie générale sont :", 'Hypnose (sommeil), analgésie et, si besoin, curarisation (relâchement musculaire)', 'Fièvre, toux et douleur', 'Hydratation, nutrition et marche', 'Sédation, vomissement et hypertension'],
    ["Un curare provoque :", 'Une paralysie des muscles, nécessitant une ventilation', 'Un sommeil sans effet sur la respiration', 'Une analgésie seule', 'Une augmentation de la vigilance'],
    ["L'induction en « séquence rapide » est indiquée chez un patient :", "À l'estomac plein (risque d'inhalation)", 'À jeun depuis la veille sans risque', 'Uniquement chez les enfants', 'Uniquement pour une anesthésie locale'],
    ["La vérification de l'appareil d'anesthésie se fait :", 'Avant chaque programme opératoire, selon une check-list', 'Une fois par an', 'Uniquement en cas de panne', 'Par le patient'],
    ["L'hyperthermie maligne est une complication rare déclenchée notamment par :", 'Les halogénés et la succinylcholine', 'Le paracétamol', 'Le sérum physiologique', 'L\'oxygène'],
    ["Le traitement spécifique de l'hyperthermie maligne est :", 'Le dantrolène', 'L\'insuline', 'La naloxone', 'La vitamine K'],
    ["Un patient à risque de nausées et vomissements postopératoires peut recevoir :", 'Une prophylaxie antiémétique selon le protocole', 'Un repas avant l\'intervention', 'Plus de morphine', 'Aucune prévention'],
    ["La sévoflurane est :", 'Un agent anesthésique halogéné inhalé', 'Un curare', 'Un antibiotique', 'Un anticoagulant'],
    ["La kétamine a pour particularité de :", 'Préserver en général la ventilation spontanée et la tension artérielle', 'Bloquer la respiration de façon certaine', 'Être un curare', 'Être un antiémétique'],
    ["Le score ASA sert à évaluer :", "L'état de santé général du patient avant l'anesthésie (risque anesthésique)", 'La douleur', 'La profondeur du coma', 'La durée de l\'intervention'],
    ["Avant l'induction, l'équipe vérifie notamment :", 'Identité, jeûne, allergies, matériel d\'intubation et d\'aspiration', 'La couleur de la blouse', 'Le menu du soir', 'Rien, tout a été vu en consultation'],
    ["L'anesthésie locorégionale (rachianesthésie, péridurale) consiste à :", 'Anesthésier une région du corps en injectant un anesthésique local près des nerfs', 'Endormir complètement le patient par inhalation', 'Bloquer tous les muscles du corps', 'Donner un antalgique par la bouche'],
    ["Une complication possible de la rachianesthésie est :", 'Une hypotension artérielle', 'Une hyperglycémie systématique', 'Une fracture', 'Une perte de cheveux'],
    ["La toxicité des anesthésiques locaux peut se manifester par :", 'Des signes neurologiques (goût métallique, convulsions) et cardiaques', 'Une fièvre isolée', 'Une diarrhée', 'Une éruption sans gravité uniquement'],
  ],
  'Intubation et ventilation': [
    ["La laryngoscopie permet de :", 'Visualiser la glotte pour introduire la sonde d\'intubation', 'Mesurer la tension', 'Aspirer l\'estomac', 'Prendre la température'],
    ["Une intubation sélective dans la bronche souche droite se manifeste par :", 'Une asymétrie du murmure vésiculaire (bruit respiratoire diminué à gauche)', 'Une hypertension isolée', 'Une fièvre', 'Une bradycardie isolée sans autre signe'],
    ["Le ballonnet de la sonde d'intubation sert à :", "Assurer l'étanchéité et limiter l'inhalation", 'Fixer la sonde à la joue', 'Mesurer la température', 'Humidifier l\'air'],
    ["La pression du ballonnet est contrôlée pour éviter :", 'Les lésions de la trachée par une pression trop élevée', 'Les allergies', 'La fièvre', 'L\'hypoglycémie'],
    ["Le masque laryngé est :", 'Un dispositif supraglottique utilisé pour ventiler sans intubation trachéale', 'Un masque à oxygène simple', 'Un masque chirurgical', 'Une sonde gastrique'],
    ["Une intubation difficile imprévue nécessite :", "D'appeler de l'aide et de suivre l'algorithme du service (vidéolaryngoscope, masque laryngé…)", 'De multiplier les tentatives seul', 'D\'arrêter l\'oxygène', 'De réveiller le chirurgien'],
    ["Le volume courant habituellement réglé chez l'adulte en ventilation protectrice est d'environ :", '6 à 8 mL/kg de poids idéal', '20 mL/kg', '1 mL/kg', '50 mL/kg'],
    ["La PEP (pression expiratoire positive) sert à :", 'Maintenir les alvéoles ouvertes et améliorer l\'oxygénation', 'Augmenter la fréquence cardiaque', 'Endormir le patient', 'Faire tousser'],
    ["Une alarme de pression haute sur le respirateur peut indiquer :", 'Une sonde coudée, des sécrétions ou un bronchospasme', 'Une déconnexion', 'Une batterie chargée', 'Un patient qui dort bien'],
    ["Une alarme de pression basse sur le respirateur évoque en premier :", 'Une déconnexion ou une fuite du circuit', 'Un bronchospasme', 'Un patient trop sédaté', 'Une fièvre'],
    ["L'aspiration trachéale chez un patient intubé se fait :", 'Avec une technique aseptique, une sonde adaptée et une durée courte', 'Avec la même sonde pour plusieurs patients', 'Pendant plusieurs minutes', 'Sans oxygénation préalable même si le patient désature'],
    ["La position de la sonde d'intubation est notée en centimètres :", 'Au niveau des dents ou de la commissure labiale', 'Au niveau du nombril', 'Au niveau de l\'oreille', 'Elle n\'est jamais notée'],
    ["Le bronchospasme se manifeste par :", 'Des sifflements, une difficulté à ventiler et une baisse de la saturation', 'Une hypertension isolée', 'Une diarrhée', 'Une augmentation de la diurèse'],
    ["Avant l'extubation, on vérifie notamment :", 'Le réveil, la ventilation spontanée efficace et la décurarisation', 'Uniquement l\'heure', 'Que le patient a mangé', 'Que le chirurgien est parti'],
    ["La fraction inspirée en oxygène (FiO2) de l'air ambiant est d'environ :", '21 %', '50 %', '100 %', '5 %'],
  ],
  'Monitorage hémodynamique': [
    ["La pression artérielle invasive est mesurée grâce à :", 'Un cathéter artériel relié à un capteur de pression', 'Un brassard au bras', 'Un thermomètre', 'Un oxymètre'],
    ["Le capteur de pression d'une ligne artérielle doit être placé :", 'Au niveau de l\'oreillette droite (zéro de référence)', 'Au niveau du sol', 'Au-dessus de la tête', 'À n\'importe quelle hauteur'],
    ["Une pression artérielle moyenne inférieure à 65 mmHg chez l'adulte en réanimation est en général :", 'Insuffisante pour une bonne perfusion des organes', 'Idéale', 'Élevée', 'Sans importance'],
    ["La capnographie mesure :", 'Le CO2 dans l\'air expiré', "L'oxygène dans le sang veineux", 'La glycémie', 'La température'],
    ["Une chute brutale du CO2 expiré pendant une anesthésie peut signaler :", 'Une déconnexion, une embolie ou un arrêt circulatoire', 'Une amélioration de l\'état du patient', 'Une fièvre', 'Un réveil normal'],
    ["Le monitorage de la curarisation (train de quatre) sert à :", 'Évaluer le relâchement musculaire et la décurarisation', 'Mesurer la tension', 'Mesurer la douleur', 'Mesurer la diurèse'],
    ["La pression veineuse centrale se mesure à l'aide :", "D'un cathéter veineux central", 'D\'un cathéter périphérique au pied', 'D\'un brassard', 'D\'une sonde urinaire'],
    ["Sur l'ECG, une fibrillation ventriculaire est :", 'Un rythme d\'arrêt cardiaque nécessitant une défibrillation', 'Un rythme normal', 'Une simple tachycardie sinusale', 'Une bradycardie sans gravité'],
    ["Une asystolie est :", 'Une absence d\'activité électrique cardiaque (rythme non choquable)', 'Une tachycardie', 'Un rythme normal', 'Une hypertension'],
    ["La température centrale se surveille au bloc pour prévenir :", "L'hypothermie peropératoire", 'Les allergies', 'Le diabète', 'La fracture'],
    ["La diurèse horaire est un reflet :", 'De la perfusion rénale', 'De la douleur', 'De la profondeur du sommeil', 'De la fonction respiratoire'],
    ["L'index bispectral (BIS) sert à évaluer :", "La profondeur de l'hypnose", 'La saturation', 'La fréquence respiratoire', 'Le débit urinaire'],
    ["Les alarmes du scope doivent être :", 'Réglées selon le patient et jamais coupées sans surveillance', 'Toujours désactivées pour le calme', 'Réglées au maximum pour tous', 'Ignorées la nuit'],
    ["Une hypotension après l'induction est souvent traitée en première intention par :", 'Un remplissage et/ou un vasopresseur selon la prescription', 'Un arrêt de l\'oxygène', 'Un antibiotique', 'Un diurétique'],
    ["Les électrodes de l'ECG à 3 brins se placent classiquement :", 'Rouge à droite sous la clavicule, jaune à gauche sous la clavicule, verte en bas à gauche', 'Toutes sur la jambe droite', 'Sur le dos uniquement', 'Sur le visage'],
    ["Une saturation qui chute alors que la courbe de pouls est de mauvaise qualité doit faire :", 'Vérifier le capteur et l\'état du patient avant de conclure', 'Ignorer l\'alarme', 'Couper le moniteur', 'Arrêter l\'oxygène'],
  ],
  'Surveillance post-interventionnelle': [
    ["En salle de surveillance post-interventionnelle (SSPI), la surveillance porte sur :", 'Conscience, respiration, circulation, douleur, température et pansements', 'Uniquement la douleur', 'Uniquement la tension', 'Uniquement le confort'],
    ["Un patient ronfle bruyamment en SSPI avec une saturation qui baisse. Il faut penser à :", 'Une obstruction des voies aériennes (subluxer la mâchoire, oxygène, alerter)', 'Un sommeil réparateur sans risque', 'Une hypertension', 'Une diurèse abondante'],
    ["Des nausées et vomissements en SSPI exposent à :", "Un risque d'inhalation chez un patient encore somnolent", 'Une meilleure récupération', 'Aucun risque', 'Une baisse de la douleur'],
    ["Un globe vésical en SSPI se manifeste par :", 'Une agitation, une douleur et une masse au-dessus du pubis', 'Une diarrhée', 'Une toux', 'Une baisse de la température'],
    ["La morphine titrée en SSPI consiste à :", 'Administrer de petites doses répétées en réévaluant la douleur et la vigilance', 'Donner une forte dose unique sans surveillance', 'Ne jamais traiter la douleur', 'Donner la morphine par voie rectale'],
    ["Un saignement important sur le pansement en SSPI doit faire :", 'Prévenir immédiatement l\'anesthésiste et le chirurgien', 'Changer simplement le pansement sans rien dire', 'Attendre le lendemain', 'Retirer les drains'],
    ["La surveillance après une rachianesthésie comprend notamment :", 'La récupération de la motricité et de la sensibilité des membres inférieurs', 'Uniquement la température', 'La vision des couleurs', 'La glycémie uniquement'],
    ["Le frisson postopératoire augmente :", "La consommation d'oxygène", 'La glycémie uniquement', 'La diurèse', 'La vision'],
    ["Les critères de sortie de SSPI reposent sur :", 'Un score validé (par exemple Aldrete) et l\'avis de l\'anesthésiste', "L'heure de fin de garde", 'La demande de la famille', 'Le nombre de lits disponibles uniquement'],
    ["Une décurarisation incomplète peut se manifester par :", 'Une faiblesse musculaire et une difficulté respiratoire', 'Une hyperactivité', 'Une fièvre', 'Une hypertension isolée'],
    ["Un patient agité et confus au réveil : avant tout, on recherche :", 'Une hypoxie, une douleur, un globe vésical ou une hypoglycémie', 'Un manque de télévision', 'Un problème administratif', 'Rien, on le sédate sans chercher'],
    ["La surveillance de l'enfant en SSPI nécessite :", 'Des valeurs normales adaptées à l\'âge et la présence rassurante des parents si possible', 'Les mêmes valeurs que l\'adulte', 'Aucune surveillance particulière', 'Un jeûne prolongé'],
    ["Les drains chirurgicaux sont surveillés pour :", 'La quantité et l\'aspect de ce qui s\'écoule', 'Leur couleur décorative', 'Leur prix', 'Le bruit qu\'ils font'],
    ["Un patient opéré sous anesthésie générale peut en général boire :", 'Lorsqu\'il est bien réveillé, selon la prescription et l\'intervention', 'Immédiatement à l\'arrivée en SSPI, encore endormi', 'Jamais pendant 3 jours', 'Uniquement de l\'alcool'],
    ["Les transmissions à la sortie de SSPI comprennent :", 'Intervention, anesthésie, antalgiques donnés, constantes, consignes de surveillance', 'Uniquement le nom du patient', 'Uniquement l\'heure', 'Rien si tout s\'est bien passé'],
    ["Une SpO2 à 88 % en SSPI chez un patient sans pathologie respiratoire impose :", "Stimuler le patient, oxygéner, vérifier les voies aériennes et alerter", 'Couper l\'alarme', 'Attendre 30 minutes', 'Faire sortir le patient de SSPI'],
  ],
};
