/** Questions supplémentaires – bloc opératoire et stérilisation. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_BLOC: Record<string, QuestionBrute[]> = {
  'Instrumentation chirurgicale': [
    ["L'écarteur de Farabeuf sert à :", 'Écarter les berges de l\'incision', 'Couper les tissus', 'Clamper une artère', 'Tenir l\'aiguille'],
    ["Les ciseaux de Mayo sont plutôt utilisés pour :", 'Couper les tissus résistants et les fils', 'Saisir un vaisseau', 'Écarter la paroi', 'Aspirer le sang'],
    ["Les ciseaux de Metzenbaum sont des ciseaux :", 'Fins, pour disséquer les tissus délicats', 'Pour couper les os', 'Pour couper les plâtres', 'Pour couper les pansements'],
    ["Une pince à disséquer « à griffes » est utilisée pour :", 'Saisir des tissus résistants comme la peau', 'Saisir l\'intestin fragile', 'Clamper l\'aorte', 'Tenir une compresse dans l\'abdomen'],
    ["Le bistouri électrique en mode « coagulation » sert à :", 'Arrêter les petits saignements', 'Couper le fil de suture', 'Écarter les tissus', 'Aspirer la fumée'],
    ["Quand le chirurgien tend la main ouverte, l'instrumentiste :", 'Dépose fermement l\'instrument dans la paume, prêt à l\'emploi', 'Lance l\'instrument', 'Pose l\'instrument sur le patient', 'Attend qu\'il le prenne sur la table'],
    ["Les lames de bistouri usagées sont :", 'Retirées avec une pince ou un dispositif adapté et jetées dans le collecteur piquant-coupant', 'Retirées avec les doigts', 'Laissées sur la table', 'Réutilisées pour le patient suivant'],
    ["Un fil résorbable est utilisé :", 'Pour les plans profonds qui ne seront pas retirés', 'Uniquement pour la peau du visage', 'Jamais au bloc', 'Pour fixer les drains de façon définitive'],
    ["La table d'instrumentation est préparée :", 'Juste avant l\'intervention, par une personne habillée stérilement', 'La veille au soir', 'Par le brancardier', 'Sans champ stérile'],
    ["Un instrument défectueux (mors abîmés) découvert pendant l'intervention doit être :", 'Écarté, remplacé et signalé à la stérilisation', 'Utilisé quand même', 'Réparé sur place avec du ruban adhésif', 'Remis dans la boîte sans rien dire'],
    ["Les compresses utilisées dans le champ opératoire sont :", 'Radio-opaques et comptées', 'Ordinaires et non comptées', 'Découpées à la main', 'Réutilisables'],
    ["Le porte-aiguille se tient en général avec l'aiguille montée :", 'Au tiers postérieur de l\'aiguille, à l\'extrémité des mors', 'Par la pointe', 'Au milieu du chas', 'N\'importe comment'],
    ["En fin d'intervention, les instruments souillés doivent être :", 'Pré-désinfectés rapidement pour éviter que les salissures ne sèchent', 'Laissés secs jusqu\'au lendemain', 'Rincés au lavabo des mains', 'Jetés à la poubelle'],
    ["Le comptage final ne correspond pas (une compresse manque). Il faut :", 'Prévenir immédiatement le chirurgien et rechercher la compresse avant la fermeture', 'Fermer quand même', 'Noter un chiffre au hasard', 'Ne rien dire'],
    ["Le rôle de l'infirmier « circulant » est notamment de :", 'Servir l\'équipe stérile en matériel et assurer la traçabilité', 'Toucher le champ opératoire', 'Instrumenter à la place du chirurgien', 'Rester assis hors de la salle'],
  ],
  'Asepsie et stérilisation': [
    ["La différence entre désinfection et stérilisation :", 'La stérilisation élimine tous les micro-organismes, y compris les spores', 'Il n\'y a aucune différence', 'La désinfection est plus efficace', 'La stérilisation ne concerne que les virus'],
    ["Un dispositif « critique » (qui pénètre un tissu stérile) doit être :", 'Stérile', 'Simplement propre', 'Désinfecté à bas niveau', 'Lavé à l\'eau'],
    ["L'indicateur de passage sur un emballage indique :", 'Que le paquet est passé dans un stérilisateur (et non qu\'il est forcément stérile)', 'Que l\'objet est stérile pour toujours', 'La date de fabrication', 'Le nom du patient'],
    ["La date de péremption d'un dispositif stérile dépend surtout :", "De l'emballage et des conditions de stockage", 'De la couleur de l\'instrument', 'Du chirurgien', 'De la saison'],
    ["Les produits stériles sont stockés :", 'Dans un endroit propre, sec, à l\'abri de la lumière directe et de la poussière', 'Au sol dans le couloir', 'Près d\'un évier', 'Dans les vestiaires'],
    ["Le principe « premier périmé, premier utilisé » s'applique aux stocks stériles pour :", 'Éviter d\'utiliser des produits périmés', 'Ranger par couleur', 'Faire des économies d\'électricité', 'Rien de particulier'],
    ["Le nettoyage des instruments avant stérilisation est indispensable car :", 'La vapeur ne stérilise pas correctement un instrument encore sale', 'Il donne une belle couleur', 'Il remplace la stérilisation', 'Il n\'est pas indispensable'],
    ["Un laveur-désinfecteur sert à :", 'Nettoyer et désinfecter les instruments avant le conditionnement', 'Stériliser les implants', 'Laver les blouses', 'Laver les mains du personnel'],
    ["Les dispositifs à usage unique :", 'Ne doivent jamais être restérilisés ni réutilisés', 'Peuvent être restérilisés deux fois', 'Peuvent être réutilisés pour le même patient le lendemain', 'Sont toujours réutilisables'],
    ["La traçabilité en stérilisation permet de retrouver :", 'Le cycle de stérilisation utilisé pour chaque dispositif et le patient concerné', 'Le prix de l\'instrument', 'L\'âge du chirurgien', 'La marque de la blouse'],
    ["Un emballage stérile tombé au sol :", 'Est considéré comme non stérile s\'il est abîmé ou selon le protocole', 'Est toujours stérile', 'Doit être ouvert pour vérifier', 'Peut être utilisé après avoir été essuyé'],
    ["Le lavage chirurgical des mains peut se faire par :", 'Friction chirurgicale avec un produit hydro-alcoolique sur des mains propres et sèches', 'Simple rinçage à l\'eau froide', 'Port de gants sans hygiène des mains', 'Application de crème'],
    ["Dans la zone stérile, on évite :", 'De tourner le dos au champ stérile et de passer entre deux zones stériles', 'De parler à voix basse', 'De porter un masque', 'De garder les mains au-dessus de la taille'],
    ["Les mains d'une personne habillée stérilement doivent rester :", 'Au-dessus de la taille et devant soi', 'Dans les poches', 'Sous les aisselles', 'Derrière le dos'],
    ["Le contrôle de la stérilisation par vapeur comprend notamment :", 'La vérification des paramètres du cycle (température, pression, durée) et des indicateurs', 'Uniquement l\'odeur', 'Uniquement la couleur des instruments', 'Aucun contrôle'],
  ],
  'Bloc opératoire': [
    ["Avant une intervention programmée, le patient doit en général :", 'Avoir respecté le jeûne, la préparation cutanée et retiré bijoux et prothèses amovibles', 'Avoir pris un repas copieux', 'Garder ses bijoux', 'Venir maquillé'],
    ["Le marquage du site opératoire (côté) est fait :", 'Avant l\'arrivée au bloc, en présence du patient conscient si possible', 'Après l\'incision', 'Par le brancardier seul', 'Jamais'],
    ["La position opératoire doit être :", 'Vérifiée par l\'équipe pour éviter compressions, étirements et brûlures', 'Choisie par le patient', 'Toujours la même pour toutes les interventions', 'Modifiée sans prévenir l\'anesthésiste'],
    ["Pourquoi protège-t-on les points d'appui (talons, coudes) au bloc ?", 'Pour prévenir les lésions cutanées et nerveuses', 'Pour réchauffer la salle', 'Pour le confort du chirurgien', 'Pour gagner du temps'],
    ["L'hypothermie au bloc opératoire est prévenue par :", 'Le réchauffement du patient (couverture chauffante, solutés réchauffés)', 'Une salle froide', 'Un patient découvert', 'La suppression des perfusions'],
    ["Le circuit propre/sale au bloc vise à :", 'Éviter de croiser le matériel stérile et les déchets ou le matériel souillé', 'Faire gagner du temps au personnel', 'Séparer les hommes et les femmes', 'Organiser les pauses'],
    ["La tenue de bloc comprend :", 'Tenue dédiée, coiffe couvrant les cheveux, masque, chaussures réservées au bloc', 'La tenue de ville sous une blouse', 'Des bijoux sous la tenue', 'Des chaussures de ville'],
    ["Le nombre de personnes et les allers-retours en salle d'opération doivent être :", 'Limités pour réduire le risque infectieux', 'Augmentés pour former les étudiants', 'Sans importance', 'Encouragés pendant l\'incision'],
    ["Les pièces opératoires (prélèvements) doivent être :", 'Identifiées, placées dans un récipient adapté et accompagnées de la demande d\'examen', 'Jetées avec les déchets', 'Gardées sans étiquette', 'Remises à la famille'],
    ["Le bistouri électrique et les solutions alcooliques exposent au risque :", "D'incendie au bloc : il faut laisser sécher l'antiseptique", 'D\'hypoglycémie', 'D\'allergie alimentaire', 'De fracture'],
    ["Le bionettoyage de la salle entre deux interventions sert à :", 'Remettre la salle dans un état de propreté adapté pour le patient suivant', 'Changer la décoration', 'Stériliser l\'air', 'Remplacer la stérilisation des instruments'],
    ["Un patient porteur d'un pacemaker opéré au bistouri électrique :", 'Nécessite une vigilance particulière (avis de l\'anesthésiste, position de la plaque)', 'Ne pose aucun problème', 'Ne peut jamais être opéré', 'Doit retirer son pacemaker'],
    ["La feuille d'écologie ou de traçabilité du bloc recense :", "L'équipe, les horaires, les dispositifs implantés et les événements", 'Le menu du jour', 'Les congés du personnel', 'Uniquement le nom du chirurgien'],
    ["En salle de surveillance post-interventionnelle, le patient est transféré :", 'Avec les transmissions de l\'équipe d\'anesthésie et du bloc', 'Seul, sans informations', 'Directement à domicile', 'Après avoir mangé'],
    ["Une rupture d'asepsie constatée pendant l'intervention doit être :", 'Signalée immédiatement pour être corrigée', 'Cachée', 'Corrigée après la fin de l\'intervention', 'Ignorée si elle est petite'],
  ],
};
