/** Questions supplémentaires – imagerie médicale. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_IMAGERIE: Record<string, QuestionBrute[]> = {
  'Radioprotection': [
    ["L'unité de dose efficace utilisée en radioprotection est :", 'Le sievert (Sv), souvent exprimé en millisievert (mSv)', 'Le becquerel (Bq)', 'Le gray (Gy)', 'Le décibel'],
    ["Doubler la distance à une source de rayons X divise la dose reçue environ par :", '4', '2, la dose étant proportionnelle à la distance', '10', 'Elle ne change pas'],
    ["Le tablier plombé protège :", 'Du rayonnement diffusé', 'Contre les infections', 'Contre le bruit de l\'appareil', 'Contre le rayonnement direct du faisceau principal, même en se plaçant dans le champ'],
    ["Le cache-thyroïde est utile car la thyroïde est :", 'Un organe radiosensible', 'Insensible aux rayons', 'Un organe de protection', 'Un organe qui fixe le produit de contraste iodé pendant les radiographies standard'],
    ["La zone contrôlée d'un service d'imagerie est :", 'Signalée et à accès réglementé', 'Une salle d\'attente libre d\'accès', "Une zone libre d'accès pour le personnel, sans signalisation particulière", 'Un vestiaire'],
    ["La collimation du faisceau consiste à :", 'Limiter le champ à la zone utile', "Augmenter la dose pour améliorer la qualité de l'image", 'Augmenter la dose pour obtenir une image plus contrastée de la zone étudiée', 'Ouvrir au maximum le champ pour ne rien manquer'],
    ["Chez l'enfant, la radioprotection est renforcée car :", 'Ses tissus sont plus sensibles et son espérance de vie plus longue', "Il ne bouge jamais pendant l'examen radiologique", 'Les doses n\'ont aucun effet', 'Les appareils sont différents'],
    ["Le parent qui maintient un enfant pendant une radiographie doit :", 'Porter un tablier, ne pas être enceinte', 'Se placer dans le faisceau', "Se placer derrière le paravent et laisser l'enfant seul sur la table pendant l'exposition", 'Tenir l\'enfant à mains nues dans le champ'],
    ["Le principe de justification signifie :", 'Un bénéfice supérieur au risque', 'Qu\'on justifie la facture', 'Qu\'on refait toujours l\'examen deux fois', "Que chaque examen doit utiliser la dose la plus faible, même si l'image est inexploitable"],
    ["Le dosimètre passif doit être porté :", 'Sur la poitrine, sous le tablier plombé selon les consignes', "Dans le vestiaire, à l'abri des rayonnements", 'Sur le poignet du patient', 'Seulement à la maison'],
    ["Un examen de remplacement non irradiant est à privilégier quand c'est possible, par exemple :", "L'échographie ou l'IRM", 'Un scanner', 'Une radiographie de plus', 'Une scintigraphie'],
    ["Pendant une exposition en salle de radiologie, le manipulateur se place :", 'Derrière le paravent', 'À côté du patient sans protection', 'Dans le faisceau', "À côté du patient avec un tablier plombé, pour le rassurer pendant l'exposition"],
    ["Le voyant lumineux « rayons X en cours » à l'entrée de la salle signifie :", 'Ne pas entrer', 'Que la salle est libre', 'Que le patient est sorti', 'Que la salle est prête et que le patient suivant peut entrer'],
    ["L'effet des rayonnements ionisants à faible dose est surtout un risque :", 'Probabiliste, à long terme', 'De brûlure immédiate systématique', 'Une brûlure cutanée immédiate, visible quelques heures après chaque examen', 'D\'allergie'],
    ["Les doses reçues par le personnel exposé sont :", 'Suivies et limitées', 'Sans limite pour les patients', "Jamais contrôlées chez l'adulte", 'Mesurées une fois par an lors de la visite médicale, sans limite réglementaire'],
  ],
  'Radiologie conventionnelle': [
    ["L'air apparaît sur une radiographie :", 'Noir', 'Blanc', 'Blanc, comme les structures osseuses denses', 'Invisible'],
    ["Une radiographie de thorax « de profil » permet notamment :", 'De mieux localiser une lésion vue de face', 'De remplacer le scanner dans tous les cas', 'De mesurer la tension', 'D\'étudier les dents'],
    ["Avant une radiographie, le manipulateur vérifie :", 'Identité, prescription, zone à radiographier', "Uniquement la couleur des vêtements et l'absence de bijoux", "Uniquement le nom inscrit sur la prescription, l'identité étant vérifiée à l'accueil", 'Uniquement le nom du médecin prescripteur et la date'],
    ["Pour une radiographie du bassin chez une femme jeune, on interroge sur :", 'Une possible grossesse', 'Son groupe sanguin', 'Ses allergies alimentaires uniquement', 'Ses horaires de travail'],
    ["La radiographie au lit du patient (mobile) est utilisée :", "Quand le patient n'est pas transportable", "Pour tous les patients hospitalisés, afin d'éviter les brancardages", 'Jamais', 'Uniquement pour les radios dentaires programmées'],
    ["Le flou cinétique sur une image est dû :", 'Aux mouvements du patient', 'À une dose trop faible ou à un mauvais réglage de la tension du tube', 'À la couleur de la peau', 'À la température de la salle'],
    ["L'incidence « face » d'une main se réalise :", 'Paume à plat sur le détecteur', 'Main de profil, pouce vers le haut, doigts écartés', 'Main dans le dos', "Main en l'air, au-dessus de la tête"],
    ["Les objets métalliques dans la zone examinée :", 'Sont retirés', 'Améliorent l\'image', 'Sont obligatoires', "N'ont aucune influence avec les détecteurs numériques actuels"],
    ["La mammographie est un examen utilisant :", 'Des rayons X avec compression', 'Des ultrasons uniquement', 'Un champ magnétique et des ondes radio', 'Des ultrasons, sans aucune irradiation, avec un gel de contact'],
    ["Une radiographie de l'abdomen sans préparation (ASP) peut montrer :", 'Des niveaux hydro-aériques', 'Le fonctionnement du cerveau', 'La tension artérielle', 'Le fonctionnement des reins et la présence de sang dans les urines'],
    ["Le contrôle de qualité de l'image vérifie :", "Centrage, exposition, absence d'artéfact", 'La couleur de l\'écran uniquement', "La signature du patient sur le bon d'examen", "Uniquement la présence du nom du patient et la date sur l'image"],
    ["Le PACS est :", "Le système d'archivage et de transmission des images", 'Un produit de contraste', 'Un logiciel de facturation des actes de radiologie', 'Un type de scanner'],
    ["En traumatologie du rachis cervical, le manipulateur :", 'Mobilise en bloc, axe maintenu, sur avis médical', 'Fait tourner la tête du patient pour mieux voir', 'Retire le collier cervical sans avis', 'Fait asseoir le patient rapidement'],
    ["Une radiographie de thorax de face est réalisée de préférence :", 'Postéro-antérieure (dos au tube)', 'Allongé sur le ventre, face au détecteur', 'En antéro-postérieure, dos contre le détecteur, pour tous les patients', 'En expiration forcée'],
    ["Les clichés comparatifs (côté sain) sont parfois utiles :", "Chez l'enfant (cartilages de croissance)", 'Jamais', 'Pour la facturation', "Pour remplacer l'examen clinique"],
    ["L'identification de chaque image comprend :", 'Nom, date, repère droite/gauche', "Le nom du manipulateur et la référence de l'appareil utilisé", 'Rien', 'Le prix de l\'examen'],
  ],
  'Scanner et IRM': [
    ["Avant une IRM, le patient doit retirer :", 'Tous les objets métalliques', "Uniquement ses bijoux en or, les autres métaux n'étant pas attirés", 'Rien', 'Ses lunettes de vue uniquement'],
    ["Le questionnaire de sécurité avant IRM recherche notamment :", 'Pacemaker, implants, éclats métalliques', 'Les préférences alimentaires', 'Le groupe sanguin', 'Le niveau d\'études'],
    ["Le produit de contraste utilisé en IRM est le plus souvent :", 'À base de gadolinium', 'À base d\'iode', 'Du baryum', 'De l\'air'],
    ["Le bruit pendant une IRM impose de :", "Protéger l'audition du patient", 'Augmenter le volume de la musique', 'Ne rien prévoir', 'Laisser la porte de la salle ouverte pour que le patient se sente moins enfermé'],
    ["Un patient claustrophobe avant une IRM peut être aidé par :", 'Explications, contact verbal, prémédication si prescrite', 'Une contention forcée', 'Un examen sans le prévenir', 'Le laisser seul sans information'],
    ["Un objet métallique ferromagnétique introduit en salle d'IRM peut :", "Être violemment attiré par l'aimant", "Améliorer la qualité des images de l'examen", "Être sans danger s'il est petit, comme un stylo ou une paire de ciseaux", 'Arrêter le champ magnétique'],
    ["Le champ magnétique d'une IRM est :", 'Toujours actif', 'Actif uniquement pendant l\'examen', 'Coupé entre deux patients et rallumé au début de chaque examen', 'Inexistant'],
    ["Pour un scanner avec injection d'iode, on demande souvent :", 'Un bilan de la fonction rénale récent selon les facteurs de risque', 'Un électroencéphalogramme', "Un test d'effort et une échographie cardiaque", 'Un bilan ophtalmologique'],
    ["Une réaction allergique à l'iode pendant l'injection se manifeste par :", 'Urticaire, gêne respiratoire, hypotension', 'Une faim soudaine', 'Une meilleure qualité d\'image', 'Une sensation de chaleur généralisée et un goût métallique, toujours graves'],
    ["Après une injection de produit de contraste iodé, on conseille en général :", 'De bien s\'hydrater', 'De jeûner 3 jours', 'De ne pas boire', 'De faire du sport intense immédiatement'],
    ["Une extravasation de produit de contraste au point d'injection impose :", "D'arrêter, surélever le membre, prévenir", 'D\'augmenter le débit', "De masser fortement la zone et d'appliquer de la chaleur pour disperser le produit", 'De ne rien faire'],
    ["Le scanner est particulièrement utile en urgence pour :", 'Rechercher un saignement intracrânien', 'Étudier un fœtus en première intention chez une femme enceinte traumatisée', 'Remplacer l\'échographie cardiaque', 'Mesurer la glycémie'],
    ["Le coroscanner ou l'angioscanner nécessitent souvent :", 'Une voie veineuse de bon calibre', "Aucune voie veineuse, l'injection étant intramusculaire", 'Un jeûne de 48 heures', 'Une anesthésie générale et une intubation chez tous les patients'],
    ["Les patients diabétiques sous metformine doivent signaler leur traitement avant :", "Une injection d'iode", 'Une radiographie du doigt', 'Une prise de tension', "Une radiographie standard du thorax ou d'un membre"],
    ["Un implant « compatible IRM sous conditions » signifie :", 'Un examen possible sous conditions', 'Que tout examen est interdit pendant six mois', "Que l'examen est possible uniquement sur les appareils les plus puissants", "Qu'il n'y a aucune précaution particulière à prendre"],
  ],
};
