/** Questions supplémentaires – imagerie médicale. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_IMAGERIE: Record<string, QuestionBrute[]> = {
  'Radioprotection': [
    ["L'unité de dose efficace utilisée en radioprotection est :", 'Le sievert (Sv), souvent exprimé en millisievert (mSv)', 'Le kilogramme', 'Le watt', 'Le décibel'],
    ["Doubler la distance à une source de rayons X divise la dose reçue environ par :", '4 (loi de l\'inverse du carré de la distance)', '2', '10', 'Elle ne change pas'],
    ["Le tablier plombé protège :", 'Le tronc et les organes sensibles du rayonnement diffusé', 'Contre les infections', 'Contre le bruit de l\'appareil', 'Contre le champ magnétique de l\'IRM'],
    ["Le cache-thyroïde est utile car la thyroïde est :", 'Un organe sensible aux rayonnements', 'Insensible aux rayons', 'Un organe de protection', 'Sans lien avec l\'imagerie'],
    ["La zone contrôlée d'un service d'imagerie est :", 'Signalée, à accès réglementé, où l\'exposition peut dépasser certains seuils', 'Une salle d\'attente libre d\'accès', 'Le bureau administratif', 'Un vestiaire'],
    ["La collimation du faisceau consiste à :", "Limiter le champ d'irradiation à la zone utile", 'Augmenter la dose', 'Refroidir le tube', 'Mesurer la tension du patient'],
    ["Chez l'enfant, la radioprotection est renforcée car :", 'Ses tissus sont plus sensibles et son espérance de vie plus longue', 'Il ne bouge jamais', 'Les doses n\'ont aucun effet', 'Les appareils sont différents'],
    ["Le parent qui maintient un enfant pendant une radiographie doit :", 'Porter un tablier de protection et ne pas être enceinte', 'Se placer dans le faisceau', 'Ne prendre aucune précaution', 'Tenir l\'enfant à mains nues dans le champ'],
    ["Le principe de justification signifie :", 'Qu\'un examen irradiant doit apporter un bénéfice supérieur au risque', 'Qu\'on justifie la facture', 'Qu\'on refait toujours l\'examen deux fois', 'Qu\'on choisit la dose la plus forte'],
    ["Le dosimètre passif doit être porté :", 'Sur la poitrine, sous le tablier plombé selon les consignes', 'Dans le vestiaire', 'Sur le poignet du patient', 'Seulement à la maison'],
    ["Un examen de remplacement non irradiant est à privilégier quand c'est possible, par exemple :", "L'échographie ou l'IRM", 'Un scanner', 'Une radiographie de plus', 'Une scintigraphie'],
    ["Pendant une exposition en salle de radiologie, le manipulateur se place :", 'Derrière le paravent ou dans le pupitre protégé', 'À côté du patient sans protection', 'Dans le faisceau', 'Dans le couloir porte ouverte'],
    ["Le voyant lumineux « rayons X en cours » à l'entrée de la salle signifie :", "Qu'il ne faut pas entrer pendant l'émission", 'Que la salle est libre', 'Que le patient est sorti', 'Que l\'appareil est en panne'],
    ["L'effet des rayonnements ionisants à faible dose est surtout un risque :", 'Probabiliste (augmentation du risque de cancer à long terme)', 'De brûlure immédiate systématique', 'De fracture', 'D\'allergie'],
    ["Les doses reçues par le personnel exposé sont :", 'Suivies régulièrement et soumises à des limites réglementaires', 'Sans limite', 'Jamais contrôlées', 'Mesurées une seule fois dans la carrière'],
  ],
  'Radiologie conventionnelle': [
    ["L'air apparaît sur une radiographie :", 'Noir (radio-transparent)', 'Blanc', 'Gris clair comme l\'os', 'Invisible'],
    ["Une radiographie de thorax « de profil » permet notamment :", 'De mieux localiser une lésion vue de face', 'De remplacer le scanner dans tous les cas', 'De mesurer la tension', 'D\'étudier les dents'],
    ["Avant une radiographie, le manipulateur vérifie :", "L'identité du patient, la prescription et la zone à radiographier", 'Uniquement la couleur des vêtements', 'Uniquement l\'âge', 'Rien'],
    ["Pour une radiographie du bassin chez une femme jeune, on interroge sur :", 'Une possible grossesse', 'Son groupe sanguin', 'Ses allergies alimentaires uniquement', 'Ses horaires de travail'],
    ["La radiographie au lit du patient (mobile) est utilisée :", "Quand le patient ne peut pas être déplacé (réanimation, soins intensifs)", 'Pour tous les patients ambulatoires', 'Jamais', 'Uniquement pour les dents'],
    ["Le flou cinétique sur une image est dû :", 'Aux mouvements du patient pendant l\'exposition', 'À une dose trop faible uniquement', 'À la couleur de la peau', 'À la température de la salle'],
    ["L'incidence « face » d'une main se réalise :", 'Main à plat, paume contre le détecteur', 'Poing fermé', 'Main dans le dos', 'Main en l\'air'],
    ["Les objets métalliques dans la zone examinée :", 'Sont retirés car ils masquent les structures', 'Améliorent l\'image', 'Sont obligatoires', 'N\'ont aucune influence'],
    ["La mammographie est un examen utilisant :", 'Des rayons X à faible énergie, avec compression du sein', 'Des ultrasons uniquement', 'Un champ magnétique', 'Aucune radiation'],
    ["Une radiographie de l'abdomen sans préparation (ASP) peut montrer :", 'Des niveaux hydro-aériques en cas d\'occlusion', 'Le fonctionnement du cerveau', 'La tension artérielle', 'La vision'],
    ["Le contrôle de qualité de l'image vérifie :", 'Le bon centrage, la bonne exposition et l\'absence d\'artéfact', 'La couleur de l\'écran uniquement', 'La signature du patient', 'Rien'],
    ["Le PACS est :", 'Le système d\'archivage et de transmission des images', 'Un produit de contraste', 'Un tablier plombé', 'Un type de scanner'],
    ["En traumatologie du rachis cervical, le manipulateur :", 'Mobilise le patient avec précaution, en maintenant l\'axe, sur avis médical', 'Fait tourner la tête du patient pour mieux voir', 'Retire le collier cervical sans avis', 'Fait asseoir le patient rapidement'],
    ["Une radiographie de thorax de face est réalisée de préférence :", 'En incidence postéro-antérieure (dos au tube)', 'Allongé sur le ventre', 'De dos au détecteur systématiquement', 'En expiration forcée'],
    ["Les clichés comparatifs (côté sain) sont parfois utiles :", 'Chez l\'enfant, pour interpréter les cartilages de croissance', 'Jamais', 'Pour la facturation', 'Pour remplacer l\'examen clinique'],
    ["L'identification de chaque image comprend :", 'Le nom du patient, la date et le repère droite/gauche', 'Uniquement le nom du manipulateur', 'Rien', 'Le prix de l\'examen'],
  ],
  'Scanner et IRM': [
    ["Avant une IRM, le patient doit retirer :", 'Tous les objets métalliques (bijoux, montre, cartes magnétiques, épingles)', 'Uniquement ses chaussures', 'Rien', 'Ses lunettes de vue uniquement'],
    ["Le questionnaire de sécurité avant IRM recherche notamment :", 'Pacemaker, implants, éclats métalliques, clips vasculaires', 'Les préférences alimentaires', 'Le groupe sanguin', 'Le niveau d\'études'],
    ["Le produit de contraste utilisé en IRM est le plus souvent :", 'À base de gadolinium', 'À base d\'iode', 'Du baryum', 'De l\'air'],
    ["Le bruit pendant une IRM impose de :", 'Fournir des protections auditives au patient', 'Augmenter le volume de la musique', 'Ne rien prévoir', 'Laisser la porte ouverte'],
    ["Un patient claustrophobe avant une IRM peut être aidé par :", 'Des explications, un contact verbal et parfois une prémédication prescrite', 'Une contention forcée', 'Un examen sans le prévenir', 'Le laisser seul sans information'],
    ["Un objet métallique ferromagnétique introduit en salle d'IRM peut :", 'Être violemment attiré par l\'aimant (effet projectile)', 'Améliorer les images', 'Être sans danger', 'Arrêter le champ magnétique'],
    ["Le champ magnétique d'une IRM est :", 'Toujours actif, même quand aucun examen n\'est en cours', 'Actif uniquement pendant l\'examen', 'Coupé la nuit', 'Inexistant'],
    ["Pour un scanner avec injection d'iode, on demande souvent :", 'Un bilan de la fonction rénale récent selon les facteurs de risque', 'Un électroencéphalogramme', 'Un test d\'effort', 'Un bilan ophtalmologique'],
    ["Une réaction allergique à l'iode pendant l'injection se manifeste par :", 'Urticaire, gêne respiratoire, chute de tension', 'Une faim soudaine', 'Une meilleure qualité d\'image', 'Une baisse de la fièvre'],
    ["Après une injection de produit de contraste iodé, on conseille en général :", 'De bien s\'hydrater', 'De jeûner 3 jours', 'De ne pas boire', 'De faire du sport intense immédiatement'],
    ["Une extravasation de produit de contraste au point d'injection impose :", 'D\'arrêter l\'injection, surélever le membre et prévenir le médecin', 'D\'augmenter le débit', 'De masser fortement', 'De ne rien faire'],
    ["Le scanner est particulièrement utile en urgence pour :", 'Rechercher un saignement intracrânien après un traumatisme', 'Étudier un fœtus en première intention', 'Remplacer l\'échographie cardiaque', 'Mesurer la glycémie'],
    ["Le coroscanner ou l'angioscanner nécessitent souvent :", 'Une voie veineuse de bon calibre pour l\'injection rapide', 'Aucune voie veineuse', 'Un jeûne de 48 heures', 'Une anesthésie générale systématique'],
    ["Les patients diabétiques sous metformine doivent signaler leur traitement avant :", 'Un examen avec injection d\'iode', 'Une radiographie du doigt', 'Une prise de tension', 'Une pesée'],
    ["Un implant « compatible IRM sous conditions » signifie :", 'Que l\'examen est possible en respectant les conditions du fabricant', 'Que tout examen est interdit', 'Que l\'implant doit être retiré', 'Qu\'il n\'y a aucune précaution'],
  ],
};
