/** Questions supplémentaires – soins infirmiers. Format : [énoncé, bonne réponse, 3 distracteurs]. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_INFIRMIER: Record<string, QuestionBrute[]> = {
  'Préparation et administration des médicaments': [
    ["Prescription : 1 g de paracétamol. Les comprimés sont dosés à 500 mg. Combien en donner ?", '2 comprimés', '1 comprimé', '4 comprimés', 'Un demi-comprimé'],
    ["Une ampoule de 10 mL contient 20 mg de produit. Quelle est la concentration ?", '2 mg/mL', '20 mg/mL', '0,5 mg/mL', '200 mg/mL'],
    ["Prescription : 250 mL en 2 heures à la seringue ou à la pompe. Quel débit programmer ?", '125 mL/h', '250 mL/h', '50 mL/h', '500 mL/h'],
    ["Combien de milligrammes y a-t-il dans 1 gramme ?", '1 000 mg', '100 mg', '10 mg', '10 000 mg'],
    ["La voie sous-cutanée (SC) correspond à une injection :", 'Dans le tissu sous la peau (ventre, cuisse, bras)', "Dans une veine superficielle de l'avant-bras ou de la main", 'Dans un muscle profond', "Dans l'épaisseur de la peau superficielle, en formant une petite papule"],
    ["L'injection intramusculaire chez l'adulte se fait de préférence :", 'Quadrant supéro-externe de la fesse ou face latérale de la cuisse', 'Dans le pli du coude, au niveau de la veine', 'Dans le quadrant inféro-interne de la fesse, plus charnu et moins douloureux', 'Dans la face interne du poignet'],
    ["Un médicament reconstitué doit être :", 'Étiqueté et utilisé dans le délai prévu', "Conservé sans étiquette jusqu'à la fin du flacon", 'Utilisé quelle que soit la date', "Conservé à température ambiante sans étiquette s'il est administré dans la journée par la même personne"],
    ["Les héparines de bas poids moléculaire s'injectent :", "En sous-cutané, sans purger la bulle d'air", 'Par voie intramusculaire, dans le muscle deltoïde', 'En intraveineuse lente, après avoir purgé la bulle', "En sous-cutané, après avoir soigneusement purgé la bulle d'air de la seringue"],
    ["Un patient sous anticoagulant présente des saignements de gencives et des hématomes. Vous :", 'Prévenez le médecin, car il peut s\'agir d\'un surdosage', 'Augmentez la dose', 'Appliquez une compresse froide et attendez le prochain bilan prévu dans un mois', 'Arrêtez tous les traitements sans avis'],
    ["L'insuline rapide doit être administrée :", 'Selon la prescription, en tenant compte de la glycémie et des repas', 'À heure fixe chaque matin, quelle que soit la glycémie ou la prise du repas', 'Uniquement la nuit', 'Toujours en intramusculaire'],
    ["Écraser un comprimé à libération prolongée est :", 'Déconseillé : cela modifie la libération du médicament', 'Recommandé pour tous les comprimés', 'Sans conséquence si le comprimé est ensuite mélangé à de la compote', 'Obligatoire chez la personne âgée'],
    ["La traçabilité de l'administration d'un médicament se fait :", "Immédiatement après l'administration, par la personne qui l'a administré", 'En fin de garde, de mémoire', "Par un collègue qui n'a pas vu le soin", "Elle n'est pas nécessaire pour les médicaments per os"],
    ["Un patient refuse son traitement. Le soignant :", 'Cherche la raison, informe, prévient le médecin, trace', "Le mélange discrètement à son repas pour qu'il le prenne sans s'en rendre compte", 'Le force à le prendre', 'Ne le note pas'],
    ["Morphine : quel effet indésirable surveiller en priorité ?", 'La dépression respiratoire', 'La chute de cheveux', "L'hypertension artérielle", 'La toux sèche'],
    ["La règle d'or face à une prescription orale non urgente est :", "Obtenir une prescription écrite avant d'administrer", 'Administrer et oublier', 'Faire confiance à sa mémoire', 'Demander à la famille de confirmer'],
  ],
  'Pose de perfusion': [
    ["Quel est le premier geste avant de préparer le matériel de pose de cathéter ?", 'Une friction hydro-alcoolique des mains', 'Poser le garrot', 'Piquer la veine', 'Mettre des gants stériles sans hygiène des mains'],
    ["Le cathéter veineux périphérique doit être réévalué :", "Chaque jour ; retiré dès qu'il n'est plus utile", 'Une fois par mois', 'Une fois par semaine', "Uniquement s'il tombe"],
    ["Le pansement d'un cathéter veineux périphérique doit être :", "Stérile, transparent, refait s'il est décollé", 'Remplacé par un sparadrap simple non stérile', 'Recouvert de coton', 'Retiré pour la toilette'],
    ["Quel signe impose de retirer un cathéter veineux périphérique ?", 'Douleur, rougeur ou écoulement au point de ponction', 'Un débit régulier', 'Un pansement propre', 'Un patient qui dort'],
    ["Où éviter de poser un cathéter veineux ?", "Membre paralysé, fistule de dialyse, côté d'un curage axillaire", "Sur l'avant-bras où est posée la perfusion, pour gagner du temps", 'Sur le dos de la main', 'Sur le membre non dominant, car il est moins mobile et le cathéter risque de se boucher plus vite'],
    ["Le calibre « 18 G » par rapport au « 22 G » est :", 'Plus gros', 'Plus fin', 'Identique', 'Réservé aux nourrissons'],
    ["Pour un remplissage rapide en urgence, on choisit un cathéter :", 'De gros calibre (14 à 18 G)', 'De très petit calibre (26 G)', 'Sous-cutané', 'Intramusculaire'],
    ["Avant de raccorder une perfusion, on vérifie :", 'Prescription, soluté, limpidité, péremption, identité', "Uniquement le nom du soluté et le débit, l'identité ayant été vérifiée à l'admission", 'Uniquement le nom du médecin', 'Uniquement le nom du médecin prescripteur et le service'],
    ["Le reflux de sang dans le cathéter lors de la pose indique :", 'Que le cathéter est bien dans la veine', 'Une infection', 'Une perforation de l\'artère obligatoirement', 'Un problème de pompe'],
    ["Une bulle d'air importante dans la tubulure doit être :", 'Évacuée avant qu\'elle n\'atteigne le patient', 'Laissée passer', 'Ignorée', 'Poussée rapidement dans la veine'],
    ["La ligne de perfusion (tubulure) d'un soluté standard se change en général :", "Selon le protocole de l'établissement (souvent tous les 4 jours) et après les produits sanguins ou lipidiques", 'Toutes les heures', 'Uniquement lors du changement du cathéter, quel que soit le produit perfusé entre-temps', 'Uniquement si elle est visiblement souillée ou coudée'],
    ["Une perfusion ne coule plus. Que vérifier en premier ?", 'Clamp, position du membre, tubulure, point de ponction', 'Changer immédiatement de veine sans vérifier', 'Rincer le cathéter en poussant fortement 10 mL de sérum physiologique pour le déboucher', 'Secouer la poche'],
    ["L'antisepsie de la peau avant la pose d'un cathéter se fait :", 'Avec un antiseptique alcoolique, en respectant le temps de séchage', 'Avec de l\'eau du robinet', "Avec de l'éther", 'Sans antisepsie'],
    ["Après la pose, on note dans le dossier :", 'La date, le site, le calibre et le nom du soignant', 'Uniquement l\'heure du repas', 'Rien', "Uniquement l'heure de pose, les autres informations figurant sur le cathéter lui-même"],
    ["Un patient perfusé présente frissons et fièvre brutale. Il faut suspecter :", 'Une infection liée au cathéter et prévenir le médecin', 'Une simple fatigue', 'Un effet de la météo', 'Un débit trop lent'],
  ],
  'Prélèvements sanguins': [
    ["Quel matériel est le plus adapté pour un prélèvement veineux multiple ?", 'Un système sous vide avec corps de pompe et tubes', 'Une seringue de 50 mL pour tous les tubes', 'Une lancette', 'Un cathéter de 14 G'],
    ["Le garrot pour une prise de sang se place :", 'À quelques centimètres au-dessus du point de ponction', 'Sur le poignet pour un prélèvement au coude', 'Juste au niveau du point de ponction, serré fort pour bien faire saillir la veine', 'Sur l\'autre bras'],
    ["Les tubes doivent être étiquetés :", 'Au lit du patient, immédiatement après le prélèvement', 'Le lendemain au laboratoire', 'Avant de voir le patient, pour gagner du temps, sans vérification', 'Par le coursier'],
    ["Après une prise de sang, on applique :", 'Une compression du point de ponction, bras tendu', 'Un massage énergique', 'Un pansement compressif serré pendant plusieurs heures, bras replié', 'Rien'],
    ["Le tube sec (bouchon rouge ou jaune avec gel) sert surtout à :", 'La biochimie sur sérum (ionogramme, bilan hépatique…)', 'La numération formule', "La numération formule sanguine et le bilan d'hémostase", 'Les hémocultures'],
    ["Le tube à bouchon gris (fluorure) est souvent utilisé pour :", 'La glycémie', 'La NFS', 'Le groupe sanguin', 'La CRP en urgence uniquement'],
    ["Les hémocultures se prélèvent idéalement :", 'Lors d\'un pic fébrile ou de frissons, avant toute antibiothérapie', 'Après plusieurs jours d\'antibiotiques', 'Uniquement le matin à jeun', 'Uniquement la nuit'],
    ["Pour les hémocultures, on remplit en général :", 'Un flacon aérobie et un flacon anaérobie', 'Un seul tube sec', 'Un tube EDTA et un tube citraté pour le laboratoire de bactériologie', 'Un tube citraté'],
    ["Un patient fait un malaise vagal pendant la prise de sang. Vous :", "Arrêtez, l'allongez jambes surélevées, surveillez", 'Continuez rapidement', 'Le faites asseoir et finissez rapidement le prélèvement pour éviter de devoir repiquer', 'Lui donnez un café pendant le prélèvement'],
    ["Le prélèvement de la gazométrie artérielle se fait habituellement :", "À l'artère radiale, après vérification de la circulation collatérale (test d'Allen)", 'À la veine du pli du coude', 'À la veine du pli du coude, avec une seringue héparinée et un garrot serré', 'À la veine jugulaire, sous échographie systématique'],
    ["La glycémie capillaire se fait de préférence :", 'Côté de la pulpe du doigt, mains propres et sèches', "Au centre du doigt avec de l'alcool encore humide", 'Au lobe de l\'oreille uniquement', 'Sur la paume'],
    ["Un hématome apparaît au point de ponction. La cause la plus fréquente est :", 'Une compression insuffisante après le prélèvement', "Un tube mal étiqueté par l'infirmier préleveur", 'Un patient à jeun depuis plus de 12 heures', "Un garrot trop lâche, qui laisse le sang s'échapper autour de l'aiguille pendant le prélèvement"],
    ["Pour un bilan lipidique (cholestérol, triglycérides), le patient doit en général être :", 'À jeun depuis environ 12 heures', 'Après un repas copieux et riche en graisses', 'À jeun depuis une heure, après un petit-déjeuner léger sans matières grasses', 'Sans précaution particulière, à toute heure'],
    ["Le transport des tubes vers le laboratoire doit se faire :", 'Rapidement, dans un sachet adapté, avec la demande d\'examen', 'Dans la poche de la blouse jusqu\'au lendemain', 'Au soleil', 'Sans demande d\'examen'],
    ["L'ordre de remplissage des tubes est important pour éviter :", 'La contamination par les additifs d\'un tube à l\'autre', 'Que le patient s\'ennuie', "Une erreur de facturation et un mauvais ordre d'analyse au laboratoire", 'Rien, il n\'a aucune importance'],
  ],
  'Surveillance des paramètres vitaux': [
    ["Une tension artérielle à 180/110 mmHg chez l'adulte est :", 'Élevée : il faut contrôler et prévenir le médecin selon le protocole', 'Normale', 'Basse', 'Normale chez une personne âgée, sans contrôle nécessaire avant la visite du lendemain'],
    ["Une tension artérielle systolique inférieure à 90 mmHg chez l'adulte évoque :", 'Une hypotension à signaler', 'Une hypertension', 'Une valeur normale chez tous', 'Une fièvre'],
    ["Pour mesurer la tension, le brassard doit être :", 'Adapté à la taille du bras, au niveau du cœur, patient au repos', 'Le plus petit possible', 'Posé sur les vêtements épais', 'Placé au poignet opposé'],
    ["La fréquence respiratoire se compte :", 'Pendant une minute entière, sans que le patient s\'en aperçoive si possible', 'Pendant 15 secondes en demandant au patient de respirer normalement, puis multipliée par 4', 'En demandant au patient de respirer fort', 'Uniquement la nuit'],
    ["Le score de Glasgow évalue :", "L'état de conscience (yeux, réponse verbale, réponse motrice)", 'La douleur', 'Le risque d\'escarre', 'Le risque de chute de la personne âgée hospitalisée'],
    ["Un score de Glasgow à 15 correspond à :", 'Un patient conscient et orienté', 'Un coma profond sans réaction à la douleur', 'Un patient agité et désorienté qui répond de façon inadaptée aux questions', 'Un patient en arrêt cardiaque'],
    ["La température normale du corps est d'environ :", '36,5 à 37,5 °C', '35 à 36 °C', '38 à 39 °C', '38 à 38,5 °C'],
    ["Une diurèse (urines) inférieure à environ 0,5 mL/kg/h chez l'adulte doit faire évoquer :", 'Une oligurie à signaler', 'Une diurèse normale', 'Une polyurie', 'Un diabète obligatoirement'],
    ["L'échelle numérique de la douleur va de :", '0 (pas de douleur) à 10 (douleur maximale imaginable)', '0 à 100 en degrés', 'De 1 (douleur légère) à 5 (douleur insupportable)', 'A à E'],
    ["Une fréquence cardiaque à 130/min au repos chez l'adulte s'appelle :", 'Une tachycardie', 'Une bradycardie', 'Une hypertension', 'Une fréquence normale'],
    ["Une fréquence cardiaque à 45/min chez un adulte non sportif s'appelle :", 'Une bradycardie', 'Une tachycardie', 'Une tachypnée', 'Une fréquence normale'],
    ["La saturation en oxygène (SpO2) normale chez un adulte sain est en général :", 'Entre 95 et 100 %', 'Entre 70 et 80 %', 'Entre 50 et 60 %', 'Toujours 85 %'],
    ["Quel facteur peut fausser la mesure de la SpO2 au doigt ?", 'Des extrémités froides ou du vernis à ongles foncé', 'La couleur des cheveux', 'La taille du patient', "La taille et le poids du patient, ainsi que l'heure de la journée"],
    ["Les scores d'alerte précoce (type NEWS) servent à :", "Repérer tôt l'aggravation d'un patient à partir de ses paramètres vitaux", 'Calculer les doses d\'antibiotiques', 'Évaluer l\'autonomie', "Calculer la durée prévisible de l'hospitalisation de chaque patient"],
  ],
  'Pansements et soins des plaies': [
    ["Une plaie chirurgicale propre et fermée est en général :", 'Protégée par un pansement sec et peu manipulée les premiers jours', 'Laissée à l\'air dès la sortie du bloc dans tous les cas', 'Désinfectée toutes les heures', 'Massée'],
    ["Un pansement hydrocolloïde est adapté :", 'Aux plaies peu exsudatives en phase de bourgeonnement ou d\'épidermisation', 'Aux plaies très infectées et purulentes', 'Aux brûlures étendues du troisième degré', 'Aux plaies très infectées et purulentes, avec un écoulement abondant et malodorant'],
    ["Un pansement à base d'alginate est surtout utilisé pour :", 'Les plaies très exsudatives ou qui saignent un peu', "Les plaies sèches, nécrotiques, qu'il faut réhumidifier", 'La peau saine autour de la plaie, en prévention', 'Les plaies de la cornée et des muqueuses'],
    ["La détersion d'une plaie consiste à :", 'Éliminer les tissus nécrosés et la fibrine', 'Refermer la plaie avec des points', 'Appliquer un antibiotique local systématiquement', 'Sécher la plaie avec un sèche-cheveux'],
    ["Les ablations de fils ou d'agrafes se font :", 'Sur prescription, selon le délai prévu, avec un matériel stérile', 'Dès le lendemain de l\'intervention dans tous les cas', 'Par le patient lui-même', 'Systématiquement au 2e jour, quelle que soit la localisation de la plaie'],
    ["Une escarre de stade 4 correspond à :", 'Une perte de substance profonde atteignant le muscle, le tendon ou l\'os', 'Une rougeur qui blanchit à la pression', 'Une ampoule (phlyctène) intacte, remplie de liquide clair, sur une peau rouge', 'Une simple sécheresse cutanée'],
    ["Le mot « exsudat » désigne :", 'Le liquide qui s\'écoule d\'une plaie', 'Un type de pansement', 'Un antiseptique', 'Un antiseptique utilisé pour nettoyer les plaies chroniques'],
    ["Pour un ulcère veineux de jambe, le traitement de base associe soins locaux et :", 'Contention ou compression veineuse prescrite', 'Immobilisation stricte au lit pendant des mois', 'Chaleur locale', 'Massages profonds de la plaie'],
    ["Le pied diabétique nécessite une surveillance attentive car :", "Une plaie peut passer inaperçue et s'infecter vite", "Les diabétiques ne font jamais de plaie au niveau des pieds, même s'ils marchent", 'La cicatrisation est toujours plus rapide', 'La douleur y est toujours très forte, ce qui pousse le patient à consulter trop souvent'],
    ["Avant de refaire un pansement douloureux, il est recommandé de :", "Anticiper la douleur avec l'antalgique prescrit", 'Faire le soin le plus vite possible sans prévenir', 'Ne rien dire au patient', "Faire le soin le plus vite possible, sans l'annoncer, pour éviter l'appréhension du patient"],
    ["Une plaie qui sent mauvais, avec un écoulement verdâtre, évoque :", 'Une infection possible, à signaler au médecin', 'Une cicatrisation normale', 'Une allergie au pansement uniquement', "Une réaction normale du pansement hydrocolloïde, sans signe d'alerte"],
    ["Le tissu de granulation (bourgeonnement) est :", 'Rouge, humide et granuleux : signe de cicatrisation', 'Noir et sec', 'Jaune et collant', 'Jaune, fibrineux et adhérent au fond de la plaie, signe de cicatrisation'],
    ["Un pansement doit être changé avec une technique :", 'Aseptique, du plus propre vers le plus sale', 'Sans gants ni hygiène des mains', 'Avec les mêmes compresses pour plusieurs patients', "Propre mais non stérile, du plus sale vers le plus propre pour éliminer d'abord les germes"],
    ["L'évaluation d'une plaie dans le dossier comprend :", 'Taille, aspect, exsudat, odeur, douleur, peau autour', 'Uniquement la date', 'Uniquement le nom du pansement', 'Rien si la plaie est petite'],
    ["Pour une brûlure superficielle peu étendue, on évite :", 'Corps gras, coton et percement des cloques', "Le refroidissement à l'eau tempérée pendant une vingtaine de minutes", 'Un pansement propre', 'L\'avis médical si la brûlure est au visage'],
  ],
};
