/** Questions supplémentaires – laboratoire de biologie médicale et PMA. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_LABORATOIRE: Record<string, QuestionBrute[]> = {
  'Phase pré-analytique': [
    ["La phase pré-analytique comprend :", "Tout ce qui précède l'analyse", 'Uniquement la validation des résultats', 'Uniquement la facturation', 'La validation biologique des résultats et la transmission du compte rendu'],
    ["La majorité des erreurs de laboratoire surviennent :", 'En pré-analytique', 'Pendant l\'analyse automatisée', "Pendant l'analyse automatisée, à cause des pannes et des réactifs", 'Jamais'],
    ["Un échantillon de sang pour bilan d'hémostase doit être acheminé :", 'Vite, à température ambiante', 'Congelé', 'Au soleil', 'Dans la glace pilée, avec une agitation régulière pendant le transport'],
    ["Un tube coagulé alors qu'il devait rester liquide (EDTA) est le plus souvent dû à :", 'Une homogénéisation insuffisante', 'Un patient à jeun', 'Un prélèvement réalisé chez un patient sous anticoagulant', 'Un tube trop rempli de façon correcte'],
    ["Pour un dosage de la kaliémie, un prélèvement fait avec un garrot prolongé et le poing serré peut :", 'Augmenter faussement la kaliémie', 'Diminuer faussement le potassium par dilution du sang', 'Diminuer faussement la glycémie du patient', "N'avoir aucun effet sur les résultats du bilan"],
    ["La recherche de sang dans les selles, les urines de 24 h ou certains dosages hormonaux nécessitent :", 'Des consignes précises de recueil', 'Aucune explication', 'Un prélèvement au hasard', 'Un jeûne de 3 jours'],
    ["Le recueil des urines de 24 heures commence :", 'Premières urines du matin jetées, puis tout recueillir 24 h', 'En gardant les urines du matin et en jetant les autres', 'En gardant les premières urines du matin et en jetant celles de la nuit suivante', 'Sur une seule miction, prélevée au milieu du jet, le matin à jeun'],
    ["Un prélèvement destiné à un dosage d'ammoniémie doit être :", 'Transporté rapidement dans la glace', 'Laissé à température ambiante plusieurs heures', 'Congelé à −20 °C sans délai', 'Agité fortement'],
    ["La feuille de demande d'examens doit comporter :", 'Identité, prescripteur, examens, date et heure', 'Uniquement le nom du préleveur', 'Uniquement le nom du patient et les examens, le reste étant noté par le laboratoire', 'Uniquement le nom du préleveur et le numéro du service demandeur'],
    ["Un échantillon lipémique (sérum laiteux) peut :", 'Interférer avec certaines analyses', 'Améliorer la précision', 'Être sans conséquence', 'Indiquer une hémolyse et une augmentation du potassium dans tous les cas'],
    ["Le délai entre prélèvement et centrifugation est important car :", 'Certains paramètres évoluent', 'Le tube change de couleur', 'Il n\'a aucune importance', 'La centrifugation doit attendre au moins 24 heures pour que le sérum se forme'],
    ["Le transport des prélèvements biologiques se fait :", 'En triple emballage', 'Dans la poche du coursier sans protection', 'Dans un sac plastique simple, fermé, avec les autres documents du service', 'Dans un sac poubelle'],
    ["Pour un dosage de médicament (taux résiduel), le prélèvement se fait :", 'Juste avant la prise suivante du médicament', 'Juste après la prise', 'À n\'importe quel moment', 'Deux heures après la prise du médicament'],
    ["Un échantillon non conforme (tube inadapté) est :", 'Traité selon la procédure', 'Toujours analysé, quelle que soit sa conformité', 'Jeté sans prévenir', "Analysé normalement, le résultat étant accompagné d'un commentaire du technicien"],
    ["Le prélèvement pour une sérologie nécessite en général :", 'Un tube sec (sérum)', 'Un tube citraté', 'Un flacon d\'hémoculture', 'Un pot à urine'],
  ],
  'Hématologie': [
    ["Le frottis sanguin permet de :", 'Observer au microscope la forme et la répartition des cellules sanguines', 'Doser le glucose et les électrolytes du sang', 'Mesurer la créatinine', 'Mettre en culture les bactéries présentes dans le sang'],
    ["La coloration la plus utilisée pour le frottis sanguin est :", 'May-Grünwald-Giemsa', 'Gram, après fixation à la chaleur', 'Ziehl-Neelsen', 'Encre de Chine'],
    ["Une polynucléose neutrophile évoque souvent :", 'Une infection bactérienne', 'Une carence en fer chronique', 'Une allergie ou une parasitose intestinale', 'Une déshydratation sévère'],
    ["Une hyperéosinophilie peut évoquer :", 'Une allergie ou une parasitose', 'Une infection virale banale uniquement', 'Une hémorragie', 'Un diabète'],
    ["Le taux de prothrombine (TP) explore :", 'La voie extrinsèque (AVK, INR)', 'Le nombre et la fonction des plaquettes sanguines', 'La glycémie', 'La fonction rénale'],
    ["Le TCA est utilisé notamment pour surveiller :", "L'héparine non fractionnée", 'Un traitement par insuline', 'Un traitement antibiotique', 'La grossesse'],
    ["Un INR cible entre 2 et 3 concerne en général :", 'Les patients sous AVK', 'Les patients sans traitement', 'Les patients sous héparine de bas poids moléculaire préventive', 'Les nouveau-nés'],
    ["Le groupage sanguin ABO repose sur :", 'Antigènes globulaires et anticorps plasmatiques', 'La mesure de l\'hémoglobine', 'La numération des plaquettes', "La mesure de l'hémoglobine et de l'hématocrite"],
    ["Le donneur universel de globules rouges est :", 'O Rhésus négatif', 'AB Rhésus positif', 'A Rhésus positif', 'B Rhésus négatif'],
    ["La recherche d'agglutinines irrégulières (RAI) est réalisée :", 'Avant transfusion et pendant la grossesse', 'Uniquement chez les patients déjà transfusés plusieurs fois', 'Pour doser le cholestérol', 'Pour mesurer la glycémie'],
    ["Les réticulocytes reflètent :", 'La production médullaire de globules rouges', 'La fonction du foie et des voies biliaires', 'La coagulation', 'Le taux de sucre'],
    ["La vitesse de sédimentation (VS) est un marqueur :", "D'inflammation", 'Spécifique des infections bactériennes, plus que la CRP', 'De grossesse', "D'allergie alimentaire"],
    ["Une thrombopénie sévère expose surtout à :", 'Un risque hémorragique', 'Une thrombose veineuse profonde', 'Un risque de thrombose veineuse profonde', 'Une hyperglycémie'],
    ["L'hématocrite correspond à :", 'Le % du volume occupé par les hématies', 'Le nombre de plaquettes par millimètre cube de sang', "La concentration d'hémoglobine dans chaque globule rouge", 'La quantité de plasma uniquement'],
    ["Les automates d'hématologie doivent être soumis à :", 'Des contrôles qualité réguliers', 'Aucun contrôle', "Un contrôle uniquement lors de l'installation de l'appareil", 'Un nettoyage annuel seulement, sans contrôle de qualité'],
  ],
  'Analyses biochimiques': [
    ["La CRP (protéine C réactive) est un marqueur :", "D'inflammation", 'De la fonction thyroïdienne', 'Du diabète', 'De la fonction du foie et des voies biliaires'],
    ["Les transaminases (ASAT, ALAT) explorent principalement :", 'Le foie', 'Les reins', 'Le cœur uniquement', 'Les os'],
    ["La troponine est dosée pour rechercher :", 'Une atteinte cardiaque', 'Une insuffisance hépatique', 'Une infection urinaire basse', 'Une atteinte du muscle squelettique après un effort intense'],
    ["L'urée et la créatinine augmentées évoquent :", 'Une insuffisance rénale', 'Une hépatite ou une atteinte des voies biliaires', 'Une anémie', 'Une allergie'],
    ["La bilirubine augmentée provoque :", 'Un ictère', 'Une coloration bleutée de la peau et des lèvres', 'Une toux', 'Une hypoglycémie'],
    ["La TSH est dosée pour explorer :", 'La thyroïde', 'Le pancréas', 'Le rein', 'La moelle osseuse'],
    ["La ferritine basse évoque :", 'Une carence en fer', 'Une infection', 'Un excès de vitamine C', 'Une hyperglycémie'],
    ["Le dosage des bêta-hCG sert notamment à :", 'Diagnostiquer une grossesse', 'Explorer le foie', 'Mesurer le cholestérol', 'Surveiller la fonction thyroïdienne pendant la grossesse'],
    ["La calcémie normale chez l'adulte est d'environ :", '2,2 à 2,6 mmol/L', '0,2 à 0,5 mmol/L', '5 à 10 mmol/L', '135 à 145 mmol/L'],
    ["Les lipases augmentées (plus de 3 fois la normale) avec douleur abdominale évoquent :", 'Une pancréatite aiguë', 'Une appendicite certaine', 'Une infection urinaire', 'Une fracture'],
    ["Le principe de la spectrophotométrie repose sur :", "La mesure de l'absorption de la lumière par une solution", 'La culture des bactéries', 'La coloration de Gram', 'La centrifugation des échantillons sanguins'],
    ["Un contrôle de qualité hors limites sur un automate impose :", 'De bloquer les résultats et chercher la cause', 'De rendre les résultats avec un commentaire, puis de refaire le contrôle le lendemain', "D'ignorer le contrôle si les patients vont bien", 'De rendre les résultats et refaire le contrôle demain'],
    ["Une hyperkaliémie importante est dangereuse car elle peut provoquer :", 'Des troubles du rythme', 'Une chute de cheveux importante', 'Une fièvre et des frissons', 'Des crampes musculaires bénignes sans autre conséquence'],
    ["Un résultat critique (valeur d'alerte) doit être :", 'Communiqué sans délai', 'Rendu le lendemain', 'Gardé pour la fin de la journée', "Rendu avec les autres résultats, en le surlignant pour qu'il soit remarqué"],
    ["La glycémie à jeun ≥ 1,26 g/L (7 mmol/L) à deux reprises définit :", 'Un diabète', 'Une hypoglycémie', 'Une valeur normale', 'Une anémie'],
  ],
  'Microbiologie': [
    ["Un ECBU est considéré comme évocateur d'infection urinaire en présence de :", 'Leucocyturie et bactériurie significatives, à interpréter selon le contexte', 'Uniquement de cristaux', 'Uniquement de mucus', 'De nombreux cristaux et du mucus, sans leucocytes ni bactéries'],
    ["L'antibiogramme permet de :", 'Tester la sensibilité aux antibiotiques', 'Compter les globules rouges et les plaquettes', "Doser le sucre et l'urée dans le sang", "Identifier l'espèce bactérienne responsable de l'infection"],
    ["Staphylococcus aureus est :", 'Un coque Gram positif en amas', 'Un bacille Gram négatif', 'Un champignon', 'Un parasite'],
    ["La coloration de Ziehl-Neelsen est utilisée pour rechercher :", 'Les mycobactéries', 'Les levures', 'Les streptocoques', 'Les streptocoques et les pneumocoques'],
    ["Candida albicans est :", 'Une levure', 'Une bactérie', 'Un virus', 'Une bactérie Gram positif de la flore cutanée'],
    ["Les prélèvements pour recherche de germes anaérobies doivent être :", "À l'abri de l'air, rapidement", 'Laissés à l\'air libre', 'Congelés immédiatement à −20 °C', "Laissés à l'air libre pour favoriser la croissance des bactéries"],
    ["Le poste de sécurité microbiologique (PSM) protège :", "Le manipulateur, l'échantillon, l'environnement", 'Uniquement contre le bruit', 'Contre l\'incendie', "Uniquement l'échantillon, le manipulateur devant porter un masque FFP2"],
    ["Une bactérie multirésistante (BMR) est :", 'Résistante à plusieurs antibiotiques', 'Sensible à tous les antibiotiques', 'Un virus', 'Un champignon'],
    ["Le milieu gélose au sang permet notamment d'observer :", "L'hémolyse bactérienne", 'Le groupe sanguin du patient', "La glycémie et l'urée", 'La sensibilité des bactéries aux antibiotiques'],
    ["Le résultat d'une hémoculture positive doit être :", 'Transmis rapidement au clinicien (examen direct, puis identification)', 'Rendu une semaine plus tard', 'Ignoré', 'Archivé avec les autres résultats'],
    ["La PCR est une technique :", "D'amplification génétique", 'De coloration', 'De culture sur gélose', 'De culture rapide des micro-organismes sur milieu enrichi'],
    ["Un prélèvement de gorge pour recherche de streptocoque se fait avec :", 'Un écouvillon sur les amygdales', 'Une seringue intraveineuse', 'Un tube EDTA', 'Un pot à selles'],
    ["La recherche de parasites dans les selles (examen parasitologique) nécessite souvent :", 'Plusieurs prélèvements espacés', 'Un seul prélèvement congelé', 'Du sang', 'Un jeûne de 48 heures'],
    ["Les déchets contaminés du laboratoire de microbiologie sont :", 'Éliminés en filière infectieuse', 'Jetés dans les ordures ménagères', 'Lavés et réutilisés', "Lavés à l'eau de Javel puis jetés avec les ordures ménagères"],
    ["Les cultures bactériennes sont en général incubées à :", '35 à 37 °C', '4 °C', 'À température ambiante, autour de 20 °C', '−20 °C'],
    ["La mise en évidence d'Escherichia coli dans une eau de boisson indique :", 'Une contamination fécale', 'Une eau parfaitement potable', 'Un excès de calcium', 'Une eau trop froide'],
  ],
  'Laboratoire de PMA': [
    ["La FIV « classique » consiste à :", 'Mettre ovocytes et spermatozoïdes en contact', "Injecter un spermatozoïde sélectionné directement dans l'ovocyte", 'Déposer les spermatozoïdes dans l\'utérus', 'Congeler l\'embryon sans fécondation'],
    ["L'insémination intra-utérine consiste à :", "Déposer du sperme préparé dans l'utérus", 'Prélever des ovocytes', 'Transférer un embryon', "Injecter un spermatozoïde dans l'ovocyte avant de le transférer"],
    ["La ponction ovocytaire se fait en général :", 'Sous échographie, par voie vaginale', 'Par chirurgie abdominale systématique, sous anesthésie générale', 'Par prise de sang', 'Sans aucune préparation'],
    ["Le signe d'une fécondation normale observé vers 16–20 heures est :", 'Deux pronucléi', "La présence d'un blastocyste avec une masse cellulaire interne", 'Un ovocyte sans changement', 'Trois cellules'],
    ["La vitrification est :", 'Une congélation ultra-rapide', 'Une technique de coloration', "Un milieu de culture utilisé pour le développement jusqu'au blastocyste", 'Une technique d\'échographie'],
    ["La préparation du sperme avant une AMP vise à :", 'Sélectionner les spermatozoïdes mobiles', 'Augmenter le volume de sperme et le nombre total de spermatozoïdes', 'Colorer les spermatozoïdes', 'Les congeler immédiatement'],
    ["Dans un spermogramme, la mobilité progressive est :", 'Le % de spermatozoïdes qui avancent', "Le volume total de l'éjaculat en millilitres", "Le pH de l'éjaculat", "Le nombre total de spermatozoïdes vivants par millilitre d'éjaculat"],
    ["La qualité de l'air dans un laboratoire de FIV est importante car :", 'Les embryons sont sensibles aux polluants', 'Elle n\'a aucune importance', 'Elle concerne seulement le confort et la température des biologistes', 'Elle sert à la congélation'],
    ["Le transfert embryonnaire est en général réalisé :", 'À J2–J3 ou J5–J6', 'Le jour de la ponction', 'À J15', 'Après au moins deux semaines de culture au laboratoire'],
    ["La traçabilité au laboratoire de PMA permet de relier :", 'Chaque gamète et embryon au bon couple', 'Les embryons à la facture', 'Les patients au parking', 'Rien de particulier'],
    ["Les cuves d'azote liquide nécessitent :", 'Une surveillance et des protections', 'Aucune surveillance', 'Un stockage au soleil', 'Une manipulation à mains nues pour plus de précision, sans surveillance'],
    ["Le risque principal lors de la manipulation de l'azote liquide est :", "Les brûlures par le froid et le risque d'asphyxie dans un local mal ventilé", "L'électrocution lors du remplissage de la cuve", "L'irradiation et la contamination radioactive des échantillons", 'L\'allergie alimentaire'],
    ["La culture embryonnaire nécessite un contrôle précis :", "De la température, du pH et de l'osmolarité des milieux", 'De la couleur des boîtes', 'De la luminosité maximale', 'Du bruit et des vibrations uniquement'],
    ["Le syndrome d'hyperstimulation ovarienne est :", 'Une complication de la stimulation', 'Une complication du transfert de sperme', "Un résultat normal, attendu, signe d'une bonne réponse au traitement", 'Une maladie du nouveau-né'],
  ],
};
