/** Questions supplémentaires – laboratoire de biologie médicale et PMA. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_LABORATOIRE: Record<string, QuestionBrute[]> = {
  'Phase pré-analytique': [
    ["La phase pré-analytique comprend :", "Tout ce qui précède l'analyse : prescription, préparation du patient, prélèvement, transport", 'Uniquement la validation des résultats', 'Uniquement la facturation', 'Le rendu du compte rendu'],
    ["La majorité des erreurs de laboratoire surviennent :", 'Pendant la phase pré-analytique', 'Pendant l\'analyse automatisée', 'Après le rendu des résultats', 'Jamais'],
    ["Un échantillon de sang pour bilan d'hémostase doit être acheminé :", 'Rapidement, à température ambiante, sans être agité', 'Congelé', 'Au soleil', 'Après 48 heures'],
    ["Un tube coagulé alors qu'il devait rester liquide (EDTA) est le plus souvent dû à :", "Une homogénéisation insuffisante après le prélèvement", 'Un patient à jeun', 'Une étiquette mal collée', 'Un tube trop rempli de façon correcte'],
    ["Pour un dosage de la kaliémie, un prélèvement fait avec un garrot prolongé et le poing serré peut :", 'Augmenter faussement le potassium', 'Diminuer le sodium', 'Fausser la couleur de l\'urine', 'N\'avoir aucun effet'],
    ["La recherche de sang dans les selles, les urines de 24 h ou certains dosages hormonaux nécessitent :", 'Des consignes de recueil précises remises au patient', 'Aucune explication', 'Un prélèvement au hasard', 'Un jeûne de 3 jours'],
    ["Le recueil des urines de 24 heures commence :", 'Après avoir jeté les premières urines du matin, puis tout recueillir jusqu\'au lendemain même heure', 'En gardant les urines du matin et en jetant les autres', 'Uniquement la nuit', 'Sur une seule miction'],
    ["Un prélèvement destiné à un dosage d'ammoniémie doit être :", 'Transporté rapidement dans la glace', 'Laissé à température ambiante plusieurs heures', 'Congelé à −20 °C sans délai', 'Agité fortement'],
    ["La feuille de demande d'examens doit comporter :", 'Identité du patient, prescripteur, examens demandés, date et heure de prélèvement', 'Uniquement le nom du préleveur', 'Uniquement le prix', 'Rien'],
    ["Un échantillon lipémique (sérum laiteux) peut :", 'Interférer avec certaines analyses', 'Améliorer la précision', 'Être sans conséquence', 'Indiquer une hémolyse'],
    ["Le délai entre prélèvement et centrifugation est important car :", 'Certains paramètres évoluent dans le tube (glucose, potassium…)', 'Le tube change de couleur', 'Il n\'a aucune importance', 'Le patient doit attendre'],
    ["Le transport des prélèvements biologiques se fait :", 'Dans un triple emballage adapté pour la sécurité', 'Dans la poche du coursier sans protection', 'Avec les repas', 'Dans un sac poubelle'],
    ["Pour un dosage de médicament (taux résiduel), le prélèvement se fait :", "Juste avant la prise suivante du médicament", 'Juste après la prise', 'À n\'importe quel moment', 'Le lendemain de l\'arrêt'],
    ["Un échantillon non conforme (tube inadapté) est :", 'Refusé ou traité selon la procédure, avec information du service', 'Toujours analysé', 'Jeté sans prévenir', 'Remplacé par un autre tube du même patient'],
    ["Le prélèvement pour une sérologie nécessite en général :", 'Un tube sec (sérum)', 'Un tube citraté', 'Un flacon d\'hémoculture', 'Un pot à urine'],
  ],
  'Hématologie': [
    ["Le frottis sanguin permet de :", 'Observer au microscope la forme et la répartition des cellules sanguines', 'Doser le glucose', 'Mesurer la créatinine', 'Faire une culture bactérienne'],
    ["La coloration la plus utilisée pour le frottis sanguin est :", 'May-Grünwald-Giemsa', 'Gram', 'Ziehl-Neelsen', 'Encre de Chine'],
    ["Une polynucléose neutrophile évoque souvent :", 'Une infection bactérienne', 'Une carence en fer', 'Une allergie uniquement', 'Une déshydratation'],
    ["Une hyperéosinophilie peut évoquer :", 'Une allergie ou une parasitose', 'Une infection virale banale uniquement', 'Une hémorragie', 'Un diabète'],
    ["Le taux de prothrombine (TP) explore :", 'La voie extrinsèque de la coagulation (surveillance des AVK via l\'INR)', 'Les plaquettes uniquement', 'La glycémie', 'La fonction rénale'],
    ["Le TCA est utilisé notamment pour surveiller :", "Un traitement par héparine non fractionnée", 'Un traitement par insuline', 'Un traitement antibiotique', 'La grossesse'],
    ["Un INR cible entre 2 et 3 concerne en général :", 'Les patients sous antivitamine K pour la plupart des indications', 'Les patients sans traitement', 'Les patients sous insuline', 'Les nouveau-nés'],
    ["Le groupage sanguin ABO repose sur :", 'La recherche des antigènes globulaires et des anticorps du plasma', 'La mesure de l\'hémoglobine', 'La numération des plaquettes', 'La culture du sang'],
    ["Le donneur universel de globules rouges est :", 'O Rhésus négatif', 'AB Rhésus positif', 'A Rhésus positif', 'B Rhésus négatif'],
    ["La recherche d'agglutinines irrégulières (RAI) est réalisée :", 'Avant une transfusion et pendant la grossesse', 'Uniquement après une fracture', 'Pour doser le cholestérol', 'Pour mesurer la glycémie'],
    ["Les réticulocytes reflètent :", 'La production de globules rouges par la moelle osseuse', 'La fonction du foie', 'La coagulation', 'Le taux de sucre'],
    ["La vitesse de sédimentation (VS) est un marqueur :", 'D\'inflammation, peu spécifique', 'Spécifique d\'un cancer', 'De grossesse', 'D\'allergie'],
    ["Une thrombopénie sévère expose surtout à :", 'Un risque hémorragique', 'Une thrombose', 'Une hypertension', 'Une hyperglycémie'],
    ["L'hématocrite correspond à :", 'Le pourcentage du volume sanguin occupé par les globules rouges', 'Le nombre de plaquettes', 'Le taux de fer', 'La quantité de plasma uniquement'],
    ["Les automates d'hématologie doivent être soumis à :", 'Des contrôles de qualité internes réguliers', 'Aucun contrôle', 'Un contrôle tous les dix ans', 'Un nettoyage annuel seulement'],
  ],
  'Analyses biochimiques': [
    ["La CRP (protéine C réactive) est un marqueur :", "D'inflammation, qui augmente rapidement en cas d'infection bactérienne", 'De la fonction thyroïdienne', 'Du diabète', 'De l\'anémie'],
    ["Les transaminases (ASAT, ALAT) explorent principalement :", 'Le foie', 'Les reins', 'Le cœur uniquement', 'Les os'],
    ["La troponine est dosée pour rechercher :", 'Une atteinte du muscle cardiaque (infarctus)', 'Une infection urinaire', 'Une grossesse', 'Une carence en fer'],
    ["L'urée et la créatinine augmentées évoquent :", 'Une insuffisance rénale', 'Une hépatite', 'Une anémie', 'Une allergie'],
    ["La bilirubine augmentée provoque :", 'Un ictère (jaunisse)', 'Une hypertension', 'Une toux', 'Une hypoglycémie'],
    ["La TSH est dosée pour explorer :", 'La thyroïde', 'Le pancréas', 'Le rein', 'La moelle osseuse'],
    ["La ferritine basse évoque :", 'Une carence en fer', 'Une infection', 'Un excès de vitamine C', 'Une hyperglycémie'],
    ["Le dosage des bêta-hCG sert notamment à :", 'Diagnostiquer et suivre une grossesse', 'Explorer le foie', 'Mesurer le cholestérol', 'Surveiller l\'insuline'],
    ["La calcémie normale chez l'adulte est d'environ :", '2,2 à 2,6 mmol/L', '0,2 à 0,5 mmol/L', '5 à 10 mmol/L', '135 à 145 mmol/L'],
    ["Les lipases augmentées (plus de 3 fois la normale) avec douleur abdominale évoquent :", 'Une pancréatite aiguë', 'Une appendicite certaine', 'Une infection urinaire', 'Une fracture'],
    ["Le principe de la spectrophotométrie repose sur :", "La mesure de l'absorption de la lumière par une solution", 'La culture des bactéries', 'La coloration de Gram', 'La centrifugation seule'],
    ["Un contrôle de qualité hors limites sur un automate impose :", 'De ne pas rendre les résultats et de rechercher la cause avant de reprendre', 'De rendre les résultats quand même', 'D\'ignorer le contrôle', 'De changer de patient'],
    ["Une hyperkaliémie importante est dangereuse car elle peut provoquer :", 'Des troubles du rythme cardiaque', 'Une chute de cheveux', 'Une fièvre', 'Une myopie'],
    ["Un résultat critique (valeur d'alerte) doit être :", 'Communiqué sans délai au médecin ou au service selon la procédure', 'Rendu le lendemain', 'Gardé pour la fin de la journée', 'Envoyé par courrier'],
    ["La glycémie à jeun ≥ 1,26 g/L (7 mmol/L) à deux reprises définit :", 'Un diabète', 'Une hypoglycémie', 'Une valeur normale', 'Une anémie'],
  ],
  'Microbiologie': [
    ["Un ECBU est considéré comme évocateur d'infection urinaire en présence de :", 'Leucocyturie et bactériurie significatives, à interpréter selon le contexte', 'Uniquement de cristaux', 'Uniquement de mucus', 'Urines limpides sans cellules'],
    ["L'antibiogramme permet de :", "Déterminer la sensibilité d'une bactérie aux antibiotiques", 'Compter les globules rouges', 'Doser le sucre', 'Identifier un virus'],
    ["Staphylococcus aureus est :", 'Un coque Gram positif en amas', 'Un bacille Gram négatif', 'Un champignon', 'Un parasite'],
    ["La coloration de Ziehl-Neelsen est utilisée pour rechercher :", 'Les mycobactéries (bacille de la tuberculose)', 'Les levures', 'Les streptocoques', 'Les virus'],
    ["Candida albicans est :", 'Une levure (champignon)', 'Une bactérie', 'Un virus', 'Un parasite intestinal'],
    ["Les prélèvements pour recherche de germes anaérobies doivent être :", "Protégés de l'air et acheminés rapidement", 'Laissés à l\'air libre', 'Congelés', 'Séchés'],
    ["Le poste de sécurité microbiologique (PSM) protège :", "Le manipulateur, l'échantillon et l'environnement selon sa classe", 'Uniquement contre le bruit', 'Contre l\'incendie', 'Contre les rayons X'],
    ["Une bactérie multirésistante (BMR) est :", 'Résistante à plusieurs familles d\'antibiotiques', 'Sensible à tous les antibiotiques', 'Un virus', 'Un champignon'],
    ["Le milieu gélose au sang permet notamment d'observer :", "L'hémolyse produite par certaines bactéries (streptocoques)", 'Le groupe sanguin', 'La glycémie', 'Les virus'],
    ["Le résultat d'une hémoculture positive doit être :", 'Transmis rapidement au clinicien (examen direct, puis identification)', 'Rendu une semaine plus tard', 'Ignoré', 'Envoyé uniquement par courrier'],
    ["La PCR est une technique :", "D'amplification génétique permettant de détecter un micro-organisme", 'De coloration', 'De culture sur gélose', 'De centrifugation'],
    ["Un prélèvement de gorge pour recherche de streptocoque se fait avec :", 'Un écouvillon frotté sur les amygdales', 'Une seringue intraveineuse', 'Un tube EDTA', 'Un pot à selles'],
    ["La recherche de parasites dans les selles (examen parasitologique) nécessite souvent :", 'Plusieurs prélèvements à quelques jours d\'intervalle', 'Un seul prélèvement congelé', 'Du sang', 'Un jeûne de 48 heures'],
    ["Les déchets contaminés du laboratoire de microbiologie sont :", 'Éliminés selon la filière des déchets infectieux, après inactivation si prévu', 'Jetés dans les ordures ménagères', 'Lavés et réutilisés', 'Versés dans l\'évier'],
    ["Les cultures bactériennes sont en général incubées à :", 'Environ 35 à 37 °C', '4 °C', '60 °C', '−20 °C'],
    ["La mise en évidence d'Escherichia coli dans une eau de boisson indique :", 'Une contamination fécale', 'Une eau parfaitement potable', 'Un excès de calcium', 'Une eau trop froide'],
  ],
  'Laboratoire de PMA': [
    ["La FIV « classique » consiste à :", 'Mettre en contact ovocytes et spermatozoïdes dans un milieu de culture', 'Injecter un spermatozoïde dans l\'ovocyte', 'Déposer les spermatozoïdes dans l\'utérus', 'Congeler l\'embryon sans fécondation'],
    ["L'insémination intra-utérine consiste à :", "Déposer des spermatozoïdes préparés dans la cavité utérine", 'Prélever des ovocytes', 'Transférer un embryon', 'Injecter un spermatozoïde dans l\'ovocyte'],
    ["La ponction ovocytaire se fait en général :", 'Sous échographie, par voie vaginale, après stimulation ovarienne', 'Par chirurgie abdominale systématique', 'Par prise de sang', 'Sans aucune préparation'],
    ["Le signe d'une fécondation normale observé vers 16–20 heures est :", 'La présence de deux pronucléi', 'La présence d\'un blastocyste', 'Un ovocyte sans changement', 'Trois cellules'],
    ["La vitrification est :", 'Une technique de congélation ultra-rapide des ovocytes et embryons', 'Une technique de coloration', 'Un milieu de culture', 'Une technique d\'échographie'],
    ["La préparation du sperme avant une AMP vise à :", 'Sélectionner les spermatozoïdes mobiles et éliminer le liquide séminal', 'Augmenter le volume de sperme', 'Colorer les spermatozoïdes', 'Les congeler immédiatement'],
    ["Dans un spermogramme, la mobilité progressive est :", 'Le pourcentage de spermatozoïdes qui avancent', 'Le volume de l\'éjaculat', 'Le pH', 'Le nombre de leucocytes'],
    ["La qualité de l'air dans un laboratoire de FIV est importante car :", 'Les embryons sont sensibles aux polluants et composés volatils', 'Elle n\'a aucune importance', 'Elle concerne seulement le confort', 'Elle sert à la congélation'],
    ["Le transfert embryonnaire est en général réalisé :", 'À J2–J3 ou au stade blastocyste (J5–J6)', 'Le jour de la ponction', 'À J15', 'Après un mois de culture'],
    ["La traçabilité au laboratoire de PMA permet de relier :", "Chaque gamète et embryon au couple concerné à chaque étape", 'Les embryons à la facture', 'Les patients au parking', 'Rien de particulier'],
    ["Les cuves d'azote liquide nécessitent :", 'Une surveillance du niveau et des alarmes, et des équipements de protection pour la manipulation', 'Aucune surveillance', 'Un stockage au soleil', 'Une manipulation à mains nues'],
    ["Le risque principal lors de la manipulation de l'azote liquide est :", 'Les brûlures par le froid et le risque d\'asphyxie dans un local mal ventilé', 'L\'électrocution', 'L\'irradiation', 'L\'allergie alimentaire'],
    ["La culture embryonnaire nécessite un contrôle précis :", 'De la température, du pH et de l\'osmolarité des milieux', 'De la couleur des boîtes', 'De la luminosité maximale', 'Du bruit uniquement'],
    ["Le syndrome d'hyperstimulation ovarienne est :", 'Une complication possible de la stimulation de l\'ovulation', 'Une complication du transfert de sperme', 'Un résultat normal attendu', 'Une maladie du nouveau-né'],
  ],
};
