/** Questions supplémentaires – pharmacie. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_PHARMACIE: Record<string, QuestionBrute[]> = {
  'Gestion des stocks pharmaceutiques': [
    ["Le point de commande correspond :", 'Au seuil de déclenchement de la commande', 'Au jour de l\'inventaire', 'Au prix d\'achat', 'À la quantité maximale que la pharmacie peut stocker'],
    ["Une rupture de stock d'un médicament essentiel doit être :", "Signalée, avec recherche d'une alternative", 'Gérée en attendant la prochaine livraison, sans prévenir les prescripteurs', 'Cachée au prescripteur pour ne pas retarder le traitement', 'Compensée par un médicament au hasard'],
    ["À la réception d'une commande, on vérifie :", "La conformité et l'état des colis", 'Uniquement le nombre de cartons', 'La couleur des boîtes et le nom du transporteur', 'Uniquement le nombre de colis, le contenu étant contrôlé lors du rangement'],
    ["Les médicaments de la chaîne du froid reçus en livraison doivent être :", 'Rangés immédiatement au réfrigérateur', 'Laissés dans le carton jusqu\'au lendemain', 'Mis au congélateur', 'Rangés sur l\'étagère ordinaire'],
    ["Les stupéfiants sont stockés :", 'Sous clé, avec un registre', 'Avec les autres médicaments', 'Dans le bureau de l\'accueil', 'Avec les autres médicaments, dans une zone réservée au personnel'],
    ["Le registre des stupéfiants permet :", 'De tracer entrées et sorties', 'De calculer les salaires', 'De noter les congés et les horaires du personnel', "De noter les prix d'achat et les fournisseurs des stupéfiants"],
    ["Un écart entre stock réel et stock informatique doit être :", 'Analysé et corrigé', 'Ignoré', 'Modifié sans explication', 'Corrigé directement dans le logiciel pour que les deux stocks correspondent'],
    ["La rotation des stocks permet notamment :", 'De limiter les périmés', 'D\'augmenter les pertes', 'De garder des produits plus longtemps', 'De garder plus longtemps les produits chers pour éviter les ruptures'],
    ["Le rangement d'une pharmacie se fait souvent :", 'Par ordre logique, dates courtes devant', 'Au hasard', 'Par couleur de boîte, les nouvelles livraisons devant', 'Par fournisseur, les livraisons les plus récentes étant placées devant'],
    ["Un médicament rappelé par le fabricant (rappel de lot) doit être :", 'Retiré et isolé', 'Délivré jusqu\'à épuisement', 'Remis en rayon', "Délivré jusqu'à la fin du stock, puis remplacé par un nouveau lot"],
    ["Le numéro de lot d'un médicament sert à :", 'Assurer la traçabilité', 'Indiquer le prix', 'Indiquer la posologie', 'Indiquer la date de fabrication et le dosage du médicament'],
    ["La consommation moyenne mensuelle sert à :", 'Calculer les besoins', 'Fixer les horaires', 'Déterminer les congés', 'Fixer le prix de vente des médicaments les plus utilisés'],
    ["Les produits inflammables (alcool, éther) sont stockés :", 'Dans une armoire adaptée, au frais', 'Près d\'un radiateur', 'Dans le réfrigérateur alimentaire', 'Dans le réfrigérateur à médicaments, pour éviter leur évaporation'],
    ["Les médicaments non utilisés rapportés par les patients sont :", 'Éliminés par la filière dédiée', 'Revendus', 'Remis en rayon', "Remis en stock après vérification de la date et de l'état de l'emballage"],
    ["Un inventaire tournant consiste à :", "Compter régulièrement une partie du stock tout au long de l'année", 'Tout compter une fois tous les dix ans', 'Ne jamais compter', 'Compter tout le stock en une seule fois, à la fin de chaque année'],
    ["La dotation d'un service hospitalier est :", 'La liste et les quantités de médicaments disponibles en permanence dans le service', 'Le budget du personnel', 'Le nombre de lits', 'La quantité de médicaments commandée pour chaque patient hospitalisé'],
  ],
  'Délivrance et conseil': [
    ["Une ordonnance dont la date de prescription est trop ancienne :", 'Doit être vérifiée avant toute délivrance', 'Peut toujours être délivrée', 'Peut être délivrée si le patient est connu de la pharmacie', 'Reste valable sans limite pour les traitements chroniques'],
    ["Un patient demande un antibiotique sans ordonnance. Vous :", 'Refusez et orientez-le vers un médecin', 'Délivrez la boîte la plus grande', 'Délivrez un antibiotique au hasard', 'Délivrez une petite boîte, en lui conseillant de consulter si cela ne passe pas'],
    ["« 1 cp matin et soir » signifie :", 'Un comprimé deux fois par jour', 'Deux comprimés le matin', 'Un comprimé par semaine', 'Un comprimé tous les deux jours'],
    ["Le conseil associé à un antibiotique comprend :", 'Respecter la durée prescrite', 'Arrêter dès qu\'on se sent mieux', 'Doubler la dose en cas d\'oubli', 'Arrêter dès que la fièvre a disparu, pour limiter les résistances'],
    ["Une interaction médicamenteuse est :", 'Un effet modifié par un autre médicament', 'Une erreur de prix', 'Une allergie alimentaire', 'Une réaction allergique à un médicament pris pour la première fois'],
    ["Chez la femme enceinte, avant de délivrer un médicament sans ordonnance :", 'On vérifie la compatibilité', 'On délivre comme pour tout le monde', 'On propose de l\'aspirine à forte dose', 'On délivre les médicaments à base de plantes, toujours sans danger pendant la grossesse'],
    ["Les anti-inflammatoires non stéroïdiens (ibuprofène) sont à éviter notamment :", 'En fin de grossesse, ulcère, insuffisance rénale', 'Chez tous les adultes en bonne santé', 'En cas de rhume simple uniquement', "Uniquement chez l'enfant de moins de 12 ans, en cas de fièvre élevée"],
    ["Le paracétamol en automédication chez l'adulte ne doit pas dépasser en général :", '3 à 4 g par jour', '6 à 8 g par jour, répartis en prises toutes les 4 heures', '500 mg par semaine', 'Il n\'y a pas de limite'],
    ["Une forme « gastro-résistante » :", 'Ne doit pas être croquée ni écrasée', 'Doit être dissoute dans l\'eau chaude', 'Se prend uniquement en suppositoire', 'Peut être coupée sans conséquence'],
    ["Un patient âgé polymédiqué présente un risque accru :", "D'interactions", 'De guérison plus rapide', 'D\'aucun effet', "De meilleure tolérance, l'organisme étant habitué aux médicaments"],
    ["Les collyres ouverts se conservent en général :", 'Peu de temps après ouverture (selon la notice)', 'Indéfiniment', "Jusqu'à la date de péremption imprimée sur la boîte, même après ouverture", 'Uniquement au congélateur'],
    ["Lors de la délivrance d'un inhalateur pour l'asthme, on explique :", 'La technique et le rinçage de la bouche', 'Qu\'il faut l\'avaler', 'Qu\'il s\'utilise une fois par mois', "Qu'il faut inspirer rapidement avant d'appuyer et ne jamais retenir sa respiration"],
    ["Un générique peut remplacer le médicament de référence :", 'Selon la réglementation, sauf mention contraire du prescripteur', 'Jamais sans accord écrit du médecin traitant', 'Uniquement pour les enfants', 'Uniquement si le patient paie plus'],
    ["Un sirop pour enfant se dose avec :", 'Le doseur fourni', 'Une cuillère à soupe de cuisine au hasard', 'Une cuillère à café de cuisine, qui correspond toujours à 5 mL', 'Le bouchon d\'une autre bouteille'],
    ["Un patient décrit une éruption cutanée après un nouveau médicament. Vous :", "L'orientez vers son médecin, signalez", 'Lui conseillez de doubler la dose', 'Lui conseillez une crème apaisante et de continuer le traitement normalement', 'Lui vendez un autre médicament au hasard'],
    ["Le secret professionnel au comptoir impose :", 'La discrétion sur les traitements', 'D\'annoncer les traitements à voix haute', 'De commenter l\'ordonnance devant les autres clients', "De vérifier l'identité à voix haute pour éviter toute erreur de délivrance"],
  ],
  'Conservation des médicaments': [
    ["La mention « à conserver à une température ne dépassant pas 25 °C » signifie :", "Un stockage à température ambiante contrôlée, à l'abri de la chaleur", 'Un stockage obligatoire au réfrigérateur entre +2 °C et +8 °C', 'Un stockage au congélateur', 'Aucune précaution, quelle que soit la saison de stockage'],
    ["Un vaccin congelé par erreur :", "N'est plus utilisable", 'Peut être utilisé après une décongélation lente au réfrigérateur', 'Est plus efficace', 'Peut être donné à moitié dose'],
    ["Un réfrigérateur à médicaments ne doit pas contenir :", 'Des aliments ou des boissons', 'Des vaccins', 'De l\'insuline non entamée', 'Un thermomètre, qui fausse le froid en ouvrant la porte'],
    ["En cas de panne du réfrigérateur à médicaments, il faut :", 'Transférer, noter durée et température, avertir le pharmacien', 'Ne rien dire', "Jeter immédiatement tous les produits sans demander d'avis", 'Mettre les produits au soleil'],
    ["Les médicaments photosensibles doivent être :", "À l'abri de la lumière", 'Exposés au soleil', 'Sortis de leur boîte et rangés dans des flacons transparents pour être reconnus', 'Mis sous une lampe'],
    ["Une solution buvable ouverte se conserve :", 'Selon la notice', "Jusqu'à la date de péremption imprimée sur le flacon", 'Toujours 24 heures', 'Indéfiniment'],
    ["Un médicament qui a changé d'aspect (couleur, odeur, dépôt) :", 'Ne doit pas être utilisé', 'Peut être utilisé normalement', 'Est plus actif', 'Doit être dilué'],
    ["Le relevé de température d'un réfrigérateur doit être :", 'Quotidien et enregistré', 'Fait une fois par semaine, sauf en cas de panne visible', 'Fait uniquement en été', 'Inutile'],
    ["L'humidité est néfaste pour :", 'Les comprimés et gélules', 'Aucun médicament', 'Uniquement les solutions buvables et les sirops', 'Les étiquettes uniquement'],
    ["Le transport de médicaments thermosensibles nécessite :", 'Une glacière avec contrôle de température', 'Un sac plastique ordinaire au soleil', 'Le coffre d\'une voiture chaude', 'Un sac isotherme simple, sans contrôle, si le trajet est court'],
    ["La date « EXP 06/2027 » signifie que le médicament :", "Est utilisable jusqu'à fin juin 2027", 'Est périmé depuis 2026', 'Doit être utilisé avant le début du mois de juin 2027', 'N\'a pas de date limite'],
    ["Les multidoses injectables entamées (flacons) doivent être :", 'Datées et utilisées dans le délai prévu', 'Utilisées sans limite de temps', "Utilisées jusqu'à la fin du flacon, quelle que soit la date d'ouverture", 'Partagées entre patients sans aucune précaution particulière'],
    ["Un stylo à insuline en cours d'utilisation se conserve en général :", "À température ambiante (sans dépasser environ 25–30 °C selon la notice), à l'abri de la lumière", 'Au congélateur, pour une conservation prolongée', 'Au soleil sur le tableau de bord', "Au réfrigérateur, avec l'aiguille en place pour la prochaine injection"],
    ["Les suppositoires se conservent :", 'Au frais', 'Près d\'un radiateur', 'Au soleil', 'Au congélateur, pour les durcir et faciliter leur administration'],
    ["La température d'une pièce de stockage des médicaments doit être :", 'Surveillée, surtout en été', 'Ignorée', 'La plus chaude possible', 'Toujours inférieure à 0 °C'],
    ["Les médicaments périmés d'un service sont :", 'Retournés à la pharmacie', 'Jetés à la poubelle ordinaire', 'Gardés pour l\'année suivante', "Utilisés en priorité s'ils sont périmés depuis moins de trois mois"],
  ],
};
