/** Questions supplémentaires – pharmacie. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_PHARMACIE: Record<string, QuestionBrute[]> = {
  'Gestion des stocks pharmaceutiques': [
    ["Le point de commande correspond :", 'Au niveau de stock à partir duquel il faut passer commande', 'Au jour de l\'inventaire', 'Au prix d\'achat', 'Au stock maximal'],
    ["Une rupture de stock d'un médicament essentiel doit être :", 'Signalée rapidement et une solution de remplacement recherchée avec le pharmacien', 'Ignorée', 'Cachée au prescripteur', 'Compensée par un médicament au hasard'],
    ["À la réception d'une commande, on vérifie :", 'La conformité (produits, quantités, lots, dates de péremption) et l\'état des colis', 'Uniquement le nombre de cartons', 'La couleur des boîtes', 'Rien'],
    ["Les médicaments de la chaîne du froid reçus en livraison doivent être :", 'Rangés immédiatement au réfrigérateur', 'Laissés dans le carton jusqu\'au lendemain', 'Mis au congélateur', 'Rangés sur l\'étagère ordinaire'],
    ["Les stupéfiants sont stockés :", 'Dans une armoire sécurisée fermée à clé, avec un registre', 'Avec les autres médicaments', 'Dans le bureau de l\'accueil', 'En libre accès'],
    ["Le registre des stupéfiants permet :", 'De tracer chaque entrée et sortie', 'De calculer les salaires', 'De noter les congés', 'Rien de particulier'],
    ["Un écart entre stock réel et stock informatique doit être :", 'Analysé et corrigé selon la procédure', 'Ignoré', 'Modifié sans explication', 'Caché'],
    ["La rotation des stocks permet notamment :", 'De limiter les périmés et l\'immobilisation financière', 'D\'augmenter les pertes', 'De garder des produits plus longtemps', 'D\'éviter les inventaires'],
    ["Le rangement d'une pharmacie se fait souvent :", 'Par ordre logique (alphabétique, forme galénique ou classe), avec les dates courtes devant', 'Au hasard', 'Par couleur de boîte', 'Par prix décroissant'],
    ["Un médicament rappelé par le fabricant (rappel de lot) doit être :", 'Retiré immédiatement des stocks et isolé', 'Délivré jusqu\'à épuisement', 'Remis en rayon', 'Donné au personnel'],
    ["Le numéro de lot d'un médicament sert à :", 'Assurer la traçabilité en cas de problème de qualité', 'Indiquer le prix', 'Indiquer la posologie', 'Rien'],
    ["La consommation moyenne mensuelle sert à :", 'Calculer les besoins et les quantités à commander', 'Fixer les horaires', 'Déterminer les congés', 'Choisir les fournisseurs au hasard'],
    ["Les produits inflammables (alcool, éther) sont stockés :", 'Dans un local ou une armoire adaptés, loin des sources de chaleur', 'Près d\'un radiateur', 'Dans le réfrigérateur alimentaire', 'Au soleil'],
    ["Les médicaments non utilisés rapportés par les patients sont :", 'Éliminés par la filière dédiée, jamais remis en stock', 'Revendus', 'Remis en rayon', 'Jetés dans l\'évier'],
    ["Un inventaire tournant consiste à :", 'Compter régulièrement une partie du stock tout au long de l\'année', 'Tout compter une fois tous les dix ans', 'Ne jamais compter', 'Compter uniquement les produits chers'],
    ["La dotation d'un service hospitalier est :", 'La liste et les quantités de médicaments disponibles en permanence dans le service', 'Le budget du personnel', 'Le nombre de lits', 'La liste des patients'],
  ],
  'Délivrance et conseil': [
    ["Une ordonnance dont la date de prescription est trop ancienne :", 'Doit être vérifiée selon la réglementation avant toute délivrance', 'Peut toujours être délivrée', 'Doit être déchirée', 'N\'a pas de durée de validité'],
    ["Un patient demande un antibiotique sans ordonnance. Vous :", "Refusez et l'orientez vers un médecin : les antibiotiques nécessitent une prescription", 'Délivrez la boîte la plus grande', 'Délivrez un antibiotique au hasard', 'Lui donnez les restes d\'un autre patient'],
    ["« 1 cp matin et soir » signifie :", 'Un comprimé deux fois par jour', 'Deux comprimés le matin', 'Un comprimé par semaine', 'Un comprimé tous les deux jours'],
    ["Le conseil associé à un antibiotique comprend :", 'Respecter la durée prescrite même si les symptômes disparaissent', 'Arrêter dès qu\'on se sent mieux', 'Doubler la dose en cas d\'oubli', 'Le partager avec la famille'],
    ["Une interaction médicamenteuse est :", "Une modification de l'effet d'un médicament par un autre", 'Une erreur de prix', 'Une allergie alimentaire', 'Un changement d\'emballage'],
    ["Chez la femme enceinte, avant de délivrer un médicament sans ordonnance :", 'On vérifie qu\'il est compatible avec la grossesse et on oriente si besoin', 'On délivre comme pour tout le monde', 'On propose de l\'aspirine à forte dose', 'On ne pose aucune question'],
    ["Les anti-inflammatoires non stéroïdiens (ibuprofène) sont à éviter notamment :", 'En fin de grossesse et en cas d\'ulcère ou d\'insuffisance rénale', 'Chez tous les adultes en bonne santé', 'En cas de rhume simple uniquement', 'Jamais'],
    ["Le paracétamol en automédication chez l'adulte ne doit pas dépasser en général :", '3 à 4 g par jour selon le poids et le terrain', '10 g par jour', '500 mg par semaine', 'Il n\'y a pas de limite'],
    ["Une forme « gastro-résistante » :", 'Ne doit pas être croquée ni écrasée', 'Doit être dissoute dans l\'eau chaude', 'Se prend uniquement en suppositoire', 'Peut être coupée sans conséquence'],
    ["Un patient âgé polymédiqué présente un risque accru :", "D'interactions et d'effets indésirables", 'De guérison plus rapide', 'D\'aucun effet', 'De meilleure tolérance'],
    ["Les collyres ouverts se conservent en général :", 'Pendant une durée limitée après ouverture (souvent 15 à 30 jours, selon la notice)', 'Indéfiniment', 'Un an après ouverture dans tous les cas', 'Uniquement au congélateur'],
    ["Lors de la délivrance d'un inhalateur pour l'asthme, on explique :", 'La technique d\'inhalation et le rinçage de la bouche pour les corticoïdes', 'Qu\'il faut l\'avaler', 'Qu\'il s\'utilise une fois par mois', 'Qu\'il ne faut jamais le secouer'],
    ["Un générique peut remplacer le médicament de référence :", "Selon la réglementation, sauf mention contraire du prescripteur", 'Jamais', 'Uniquement pour les enfants', 'Uniquement si le patient paie plus'],
    ["Un sirop pour enfant se dose avec :", 'Le dispositif doseur fourni avec le médicament', 'Une cuillère à soupe de cuisine au hasard', 'Un verre', 'Le bouchon d\'une autre bouteille'],
    ["Un patient décrit une éruption cutanée après un nouveau médicament. Vous :", "L'orientez vers son médecin et signalez l'effet indésirable", 'Lui conseillez de doubler la dose', 'Ignorez sa plainte', 'Lui vendez un autre médicament au hasard'],
    ["Le secret professionnel au comptoir impose :", 'De parler discrètement et de respecter la confidentialité des traitements', 'D\'annoncer les traitements à voix haute', 'De commenter l\'ordonnance devant les autres clients', 'De photocopier l\'ordonnance pour les voisins'],
  ],
  'Conservation des médicaments': [
    ["La mention « à conserver à une température ne dépassant pas 25 °C » signifie :", 'Un stockage à température ambiante contrôlée, à l\'abri de la chaleur', 'Un stockage au réfrigérateur obligatoire', 'Un stockage au congélateur', 'Aucune précaution'],
    ["Un vaccin congelé par erreur :", 'Ne doit pas être utilisé et doit être signalé', 'Peut être utilisé après décongélation', 'Est plus efficace', 'Peut être donné à moitié dose'],
    ["Un réfrigérateur à médicaments ne doit pas contenir :", 'De la nourriture ou des boissons', 'Des vaccins', 'De l\'insuline non entamée', 'Un thermomètre'],
    ["En cas de panne du réfrigérateur à médicaments, il faut :", 'Transférer les produits dans un autre réfrigérateur, noter la durée et la température, et demander l\'avis du pharmacien', 'Ne rien dire', 'Jeter tout sans évaluer', 'Mettre les produits au soleil'],
    ["Les médicaments photosensibles doivent être :", "Conservés à l'abri de la lumière, dans leur emballage", 'Exposés au soleil', 'Sortis de leur boîte', 'Mis sous une lampe'],
    ["Une solution buvable ouverte se conserve :", 'Selon la durée indiquée après ouverture sur la notice', 'Toujours un an', 'Toujours 24 heures', 'Indéfiniment'],
    ["Un médicament qui a changé d'aspect (couleur, odeur, dépôt) :", 'Ne doit pas être utilisé', 'Peut être utilisé normalement', 'Est plus actif', 'Doit être dilué'],
    ["Le relevé de température d'un réfrigérateur doit être :", 'Fait régulièrement (au moins quotidiennement) et enregistré', 'Fait une fois par an', 'Fait uniquement en été', 'Inutile'],
    ["L'humidité est néfaste pour :", 'Les comprimés et gélules (dégradation)', 'Aucun médicament', 'Uniquement les seringues', 'Les étiquettes uniquement'],
    ["Le transport de médicaments thermosensibles nécessite :", 'Une glacière adaptée avec contrôle de la température', 'Un sac plastique ordinaire au soleil', 'Le coffre d\'une voiture chaude', 'Aucune précaution'],
    ["La date « EXP 06/2027 » signifie que le médicament :", 'Peut être utilisé jusqu\'à la fin de juin 2027 s\'il est bien conservé', 'Est périmé depuis 2026', 'Est fabriqué en 2027', 'N\'a pas de date limite'],
    ["Les multidoses injectables entamées (flacons) doivent être :", 'Datées à l\'ouverture et utilisées selon le délai prévu, avec asepsie', 'Utilisées sans limite de temps', 'Gardées ouvertes à l\'air', 'Partagées sans précaution'],
    ["Un stylo à insuline en cours d'utilisation se conserve en général :", 'À température ambiante (sans dépasser environ 25–30 °C selon la notice), à l\'abri de la lumière', 'Au congélateur', 'Au soleil sur le tableau de bord', 'Dans l\'eau chaude'],
    ["Les suppositoires se conservent :", 'Au frais, à l\'abri de la chaleur pour éviter qu\'ils ne fondent', 'Près d\'un radiateur', 'Au soleil', 'Au congélateur obligatoirement'],
    ["La température d'une pièce de stockage des médicaments doit être :", 'Surveillée, surtout en été', 'Ignorée', 'La plus chaude possible', 'Toujours inférieure à 0 °C'],
    ["Les médicaments périmés d'un service sont :", 'Retournés à la pharmacie pour élimination selon la filière', 'Jetés à la poubelle ordinaire', 'Gardés pour l\'année suivante', 'Donnés aux patients'],
  ],
};
