/** Questions supplémentaires – rééducation et nutrition. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_REEDUCATION: Record<string, QuestionBrute[]> = {
  'Rééducation fonctionnelle': [
    ["Après une ligamentoplastie du genou, la rééducation précoce vise d'abord à :", 'Douleur, œdème, extension, quadriceps', 'Reprendre la course dès le 3e jour', 'Immobiliser strictement le genou plusieurs semaines avant toute mobilisation', 'Masser la cicatrice profondément le premier jour'],
    ["Une contraction isométrique est :", 'Une contraction sans mouvement', "Une contraction avec raccourcissement du muscle et mouvement de l'articulation", 'Un étirement passif réalisé par le thérapeute', 'Un massage profond du muscle'],
    ["La mobilisation passive est réalisée :", 'Par le thérapeute', 'Par le patient lui-même, sans aide, contre une résistance légère', 'Avec des poids lourds', 'Uniquement en piscine'],
    ["Un patient hémiplégique : pour l'aider à s'habiller, on commence par :", 'Le côté atteint', 'Le côté sain', 'Indifféremment', 'Les chaussures'],
    ["La rééducation de l'équilibre chez la personne âgée a pour objectif principal :", 'De prévenir les chutes', 'De faire maigrir le patient en surpoids', "D'augmenter la vitesse de marche, quel que soit le risque de chute", 'De traiter le diabète'],
    ["L'utilisation de béquilles pour monter un escalier : on monte d'abord :", 'La jambe saine', 'La jambe opérée et les béquilles ensemble, puis la jambe saine', 'Les béquilles seules', 'En sautant à pieds joints'],
    ["Une entorse grave du ligament croisé antérieur se teste notamment par :", 'Le test de Lachman', 'Le score de Glasgow', 'Le test d\'Allen', 'Le score d\'Apgar'],
    ["Le renforcement musculaire progressif repose sur :", 'Une progression graduelle', 'Des charges maximales dès la première séance', 'Des charges maximales dès la première séance, pour gagner du temps', 'Des étirements uniquement'],
    ["Une douleur qui augmente fortement et persiste après les séances doit faire :", 'Adapter et informer le médecin', 'Augmenter l\'intensité', 'Ignorer la douleur', 'Arrêter de boire'],
    ["Après une fracture du poignet plâtrée, on surveille :", 'Couleur, chaleur, sensibilité, mobilité des doigts', "L'état du plâtre uniquement, la circulation étant vérifiée par le médecin", 'La tension artérielle et la température du patient', "Uniquement l'état et la propreté du plâtre lui-même"],
    ["La cryothérapie (froid) est utilisée pour :", 'Réduire douleur et œdème', "Préparer les muscles avant l'effort et augmenter leur souplesse", 'Traiter une plaie infectée', 'Augmenter l\'inflammation'],
    ["L'ergothérapie vise surtout à :", "Favoriser l'autonomie au quotidien", 'Traiter les caries', 'Réaliser des radiographies', 'Rééduquer la parole et la déglutition après un AVC'],
    ["La lombalgie commune aiguë : la recommandation actuelle est :", 'Maintenir les activités autant que possible', "Un repos strict au lit pendant plusieurs semaines, jusqu'à disparition de la douleur", 'Une chirurgie immédiate', 'Le port permanent d\'un corset'],
    ["Le bilan articulaire d'un genou en extension complète correspond à :", '0°', '90°', '180°', '45°'],
    ["Un patient sous anticoagulants en rééducation : on évite :", 'Les techniques traumatisantes', 'La marche', 'Les exercices respiratoires', 'Toute mobilisation active, le risque de saignement étant trop important'],
  ],
  'Kinésithérapie respiratoire': [
    ["Le drainage bronchique chez le nourrisson est indiqué :", 'Selon la prescription, avec prudence', 'Systématiquement, pour toute bronchiolite, plusieurs fois par jour', 'Jamais sur prescription', 'Uniquement la nuit'],
    ["L'augmentation du flux expiratoire (AFE) vise à :", 'Mobiliser les sécrétions vers les grosses bronches', 'Bloquer la respiration', "Augmenter le volume d'air inspiré", 'Diminuer la saturation'],
    ["La toux dirigée sert à :", 'Évacuer les sécrétions proximales', 'Provoquer des vomissements', 'Mobiliser les sécrétions situées dans les petites bronches distales', 'Mesurer la saturation'],
    ["Après une chirurgie thoracique ou abdominale, la kinésithérapie respiratoire prévient :", 'Les atélectasies et les infections pulmonaires', 'Les fractures de côtes', "La phlébite et l'embolie pulmonaire uniquement", 'Les phlébites et les escarres'],
    ["La réhabilitation respiratoire chez le patient BPCO comprend :", 'Réentraînement, éducation, techniques respiratoires', 'Un repos prolongé et une oxygénothérapie continue, sans effort physique', 'Uniquement des antibiotiques', 'Une chirurgie systématique'],
    ["Avant une séance de désencombrement, il est préférable que le patient :", 'Ne vienne pas de manger', 'Ait mangé un repas copieux', 'Soit allongé à plat ventre sans surveillance', 'Ait arrêté son oxygène pour mieux tolérer les techniques'],
    ["Le débit expiratoire de pointe (peak-flow) est utile pour suivre :", "L'asthme", 'La glycémie', 'La fonction rénale', 'La vision'],
    ["La ventilation dirigée abdomino-diaphragmatique vise à :", "Améliorer l'efficacité de la respiration et diminuer l'essoufflement", 'Augmenter le travail respiratoire', 'Mobiliser surtout les muscles du cou et des épaules', 'Provoquer une apnée prolongée'],
    ["Un patient sous oxygène pendant la séance : on surveille :", 'Saturation, fréquence respiratoire, tolérance', 'Uniquement la température', 'Uniquement la tension', 'Uniquement la tension artérielle et la température'],
    ["Les signes de détresse respiratoire incluent :", 'Tirage, cyanose, polypnée', 'Une respiration calme et lente', 'Une respiration lente et ample avec une bonne coloration', 'Un sommeil paisible'],
    ["Les aérosols (nébulisations) prescrits avant la séance servent souvent à :", 'Fluidifier ou dilater les bronches', 'Endormir le patient', "Apporter de l'oxygène à la place de la séance de kinésithérapie", 'Mesurer la saturation'],
    ["Le spiromètre incitatif doit être utilisé :", 'Régulièrement, inspirations lentes', 'Une fois par semaine', "En soufflant le plus fort et le plus longtemps possible dans l'appareil", 'Uniquement en position couchée à plat'],
    ["Le positionnement du patient (drainage postural) utilise :", 'La gravité', 'Le froid', 'Le bruit', 'Les vibrations mécaniques appliquées sur le thorax'],
    ["Chez un patient atteint de mucoviscidose, la kinésithérapie respiratoire est :", 'Quotidienne et essentielle', 'Contre-indiquée', 'Inutile', 'Réservée aux adultes'],
    ["L'hygiène du matériel de kinésithérapie respiratoire (embouts, spiromètres) impose :", 'Usage individuel ou désinfection', 'Le partage sans nettoyage', "Un rinçage à l'eau du robinet entre deux patients, puis un séchage à l'air", "Aucune précaution, l'air expiré n'étant pas contaminant"],
    ["La saturation qui chute pendant l'effort chez un patient BPCO :", "Impose d'adapter l'effort et l'oxygène", 'Est sans importance si le patient ne se plaint pas', 'Est normale et ne justifie aucune adaptation de la séance', 'Doit être ignorée pendant la séance de réentraînement'],
  ],
  'Bilan et évaluation': [
    ["L'échelle de Berg ou le test « Timed Up and Go » évaluent :", "L'équilibre et le risque de chute", 'La fonction rénale', 'La mémoire uniquement', 'La douleur'],
    ["La mesure de Barthel évalue :", "L'autonomie au quotidien", 'La force de préhension seule', 'La saturation', "La mémoire et l'orientation dans le temps et l'espace"],
    ["Le périmètre de marche correspond à :", "La distance que le patient peut parcourir avant de devoir s'arrêter", 'Le tour de taille', 'La vitesse de marche mesurée sur un trajet de 10 mètres', 'La taille du couloir'],
    ["Un bilan de rééducation doit être :", 'Daté, chiffré, répété', 'Fait une seule fois', 'Réalisé une seule fois, en début de prise en charge', 'Fait par la famille'],
    ["L'œdème d'un membre peut se mesurer :", 'Par des mesures de périmètre (centimétriques) répétées aux mêmes repères', 'À l\'œil seulement', "Par une simple observation, en comparant à l'œil les deux membres", 'Avec un thermomètre'],
    ["Le test des 6 minutes de marche évalue :", "La capacité à l'effort", 'La vision', 'La mémoire', 'La vitesse maximale de course sur un tapis roulant'],
    ["La douleur chez une personne âgée non communicante peut être évaluée par :", "Une échelle d'hétéro-évaluation comportementale (type Algoplus, Doloplus)", 'Une échelle visuelle analogique, que le patient remplit lui-même', "Une auto-évaluation par l'EVA", 'Une échelle numérique de 0 à 10'],
    ["Le dynamomètre de préhension mesure :", 'La force de la main', 'La tension', 'La fréquence respiratoire', 'La température'],
    ["Les objectifs de rééducation sont fixés :", 'Avec le patient', 'Sans le patient', 'Par le thérapeute seul, selon les protocoles habituels du service', 'Au hasard'],
    ["Le bilan initial doit rechercher aussi :", 'Les contre-indications et précautions', 'Uniquement le nom du médecin et la date de la prescription', 'Les préférences musicales uniquement', 'Uniquement les préférences du patient concernant les horaires des séances'],
    ["Une évaluation de la spasticité peut utiliser :", "L'échelle d'Ashworth", "Le score d'Apgar du nouveau-né", "Le score de Glasgow de l'état de conscience", 'Le testing musculaire coté de 0 à 5'],
    ["Le bilan de sortie de rééducation sert à :", 'Comparer aux objectifs et transmettre', 'Facturer uniquement', 'Rien', "Remplacer le bilan initial, qui n'est plus utile en fin de traitement"],
    ["Une mesure fiable nécessite :", 'Les mêmes conditions et méthode', 'Un appareil différent à chaque fois', 'Des positions différentes', 'Des conditions différentes à chaque fois, pour tester toutes les situations'],
    ["Le testing musculaire coté 0 correspond à :", 'Aucune contraction perceptible', 'Une force normale', 'Un mouvement contre résistance', 'Un mouvement complet'],
    ["Le testing musculaire coté 5 correspond à :", 'Une force normale', 'Aucune contraction', 'Un mouvement sans pesanteur', 'Une contraction sans mouvement'],
    ["Le compte rendu de bilan est transmis :", 'Au prescripteur et au dossier', 'Uniquement à la famille', 'Sur les réseaux sociaux', 'À personne'],
  ],
  'Nutrition clinique': [
    ["Un aliment riche en protéines de bonne qualité :", 'Les œufs, le poisson, la viande, les produits laitiers', 'Le sucre blanc et les confiseries', 'Le pain blanc, les pâtes et le riz', 'Les huiles végétales et le beurre'],
    ["Les fibres alimentaires se trouvent surtout dans :", 'Les légumes, les fruits, les légumineuses et les céréales complètes', 'La viande, le poisson et les produits laitiers', "La viande et l'huile", 'Le sucre blanc'],
    ["L'albumine basse peut être un marqueur :", 'De dénutrition', 'D\'obésité certaine', 'De déshydratation uniquement', "D'un excès d'apport en protéines dans l'alimentation"],
    ["Les besoins hydriques d'un adulte sont en moyenne d'environ :", '1,5 à 2 L par jour', '0,2 litre par jour', "4 à 5 litres par jour, quel que soit l'âge ou le poids", 'Aucun besoin si on mange'],
    ["La nutrition entérale est :", 'Par sonde dans le tube digestif', 'Une alimentation par voie veineuse centrale', 'Une alimentation par la bouche uniquement', 'Un régime sans sel'],
    ["La nutrition parentérale est :", 'Par voie veineuse', "Une alimentation par sonde placée dans l'estomac ou l'intestin", 'Un régime riche en fibres', 'Une boisson enrichie'],
    ["Le syndrome de renutrition inappropriée survient surtout :", "Lors d'une réalimentation trop rapide chez un patient très dénutri", 'Chez un patient en surpoids', 'Après un repas normal chez un patient en bonne santé', "Lors d'un régime hypocalorique strict chez un patient obèse"],
    ["Un régime pauvre en sel est souvent prescrit en cas :", "D'hypertension", "D'anémie", 'De fracture', "D'hypoglycémie"],
    ["Chez l'insuffisant rénal chronique, on surveille souvent les apports en :", 'Potassium, phosphore, protéines', 'Vitamine C uniquement', 'Eau minérale uniquement', 'Uniquement la vitamine C et les fibres alimentaires'],
    ["Les compléments nutritionnels oraux sont utilisés :", 'En complément, chez les dénutris', 'Pour remplacer tous les repas d\'une personne en bonne santé', 'Pour remplacer tous les repas des patients hospitalisés', 'Uniquement chez l\'enfant'],
    ["Un patient âgé dénutri doit être pesé :", 'Régulièrement', 'Jamais', "Uniquement à l'entrée et à la sortie de l'hospitalisation", 'Uniquement à la sortie'],
    ["La maladie cœliaque nécessite un régime :", 'Sans gluten', 'Sans sucre', 'Sans protéines', 'Sans eau'],
    ["L'évaluation nutritionnelle comprend :", 'Poids, perte de poids, IMC, apports', 'Uniquement la taille', "Uniquement le dosage de l'albumine et de la glycémie à jeun", 'Uniquement la couleur de peau'],
    ["Les besoins énergétiques sont augmentés en cas :", "D'infection, brûlure, chirurgie", "De repos complet au lit et d'immobilisation", "De repos complet au lit et d'immobilisation prolongée", "De jeûne volontaire prolongé chez l'adulte sain"],
    ["Un régime adapté aux troubles de la déglutition utilise :", 'Des textures modifiées', 'Des aliments durs et secs', "Des liquides clairs uniquement, faciles à avaler, comme l'eau plate", 'Aucune adaptation'],
  ],
  'Prise en charge du diabète': [
    ["Le diabète de type 1 est principalement dû à :", 'Un déficit en insuline', "Une consommation excessive de sucre pendant l'enfance", 'Une infection urinaire', 'Une infection virale du pancréas'],
    ["Le diabète de type 2 est souvent associé à :", 'Le surpoids et la sédentarité', 'Une fracture', 'Une carence en vitamine C', "Une infection virale du pancréas chez l'enfant"],
    ["Les signes d'hyperglycémie importante :", 'Soif, urines abondantes, fatigue', 'Sueurs froides et tremblements', 'Fièvre isolée', 'Toux'],
    ["L'objectif d'HbA1c chez beaucoup de diabétiques de type 2 est souvent :", 'Autour de 7 %', 'Autour de 12 %, pour éviter toute hypoglycémie', '2 %', 'Il n\'y a pas d\'objectif'],
    ["L'éducation thérapeutique du patient diabétique porte notamment sur :", 'Autosurveillance, alimentation, activité, alertes', 'Uniquement le prix des médicaments', 'La couleur des stylos', "Uniquement la technique d'injection, le reste relevant du médecin"],
    ["Les sites d'injection d'insuline doivent être :", 'Alternés', 'Toujours au même endroit', 'Toujours au même endroit, pour une absorption régulière', 'Dans une veine'],
    ["Le resucrage d'une hypoglycémie est suivi :", "D'un contrôle 15 minutes après", "D'une injection d'insuline", 'D\'un jeûne', 'D\'aucune surveillance'],
    ["Les pieds d'un patient diabétique doivent être :", 'Examinés, lavés, séchés', "Trempés longuement dans l'eau chaude pour ramollir la peau", 'Laissés pieds nus en permanence', 'Coupés avec des ciseaux pointus sans précaution'],
    ["Les aliments à éviter en grande quantité chez le diabétique :", 'Les sucreries', 'Les légumes verts', 'L\'eau', 'Les légumes verts et les fibres, qui augmentent la glycémie'],
    ["L'acidocétose diabétique est :", 'Une complication grave', 'Une complication bénigne', 'Un régime alimentaire', 'Une hypoglycémie légère, corrigée par un apport de sucre'],
    ["Pendant le jeûne du Ramadan, un patient diabétique doit :", 'Consulter avant', 'Arrêter tous ses traitements sans avis', 'Prendre toutes ses doses habituelles au moment de la rupture du jeûne', 'Ne rien changer sans avis'],
    ["L'activité physique chez le diabétique traité par insuline peut provoquer :", 'Une hypoglycémie', 'Une hyperglycémie systématique', "Une hyperglycémie systématique, qui impose d'augmenter l'insuline", 'Une fracture'],
    ["Les complications chroniques du diabète touchent notamment :", 'Yeux, reins, nerfs, cœur, vaisseaux', 'Aucun organe en dehors du pancréas', 'Uniquement la peau et les cheveux, sans atteinte des organes', 'Uniquement la peau, les ongles et les cheveux'],
    ["Une alimentation équilibrée pour un diabétique répartit les glucides :", 'Sur les différents repas', 'En un seul repas par jour', 'Uniquement le soir', 'En supprimant les féculents et en les remplaçant par des fruits'],
    ["L'autosurveillance glycémique se note :", 'Dans un carnet ou une application', 'Nulle part', 'Uniquement lors des consultations, de mémoire', 'Uniquement de mémoire, entre deux consultations'],
    ["Le fond d'œil est recommandé chez le diabétique pour dépister :", 'La rétinopathie', 'La myopie uniquement', "Une myopie liée à l'hyperglycémie", 'La carie dentaire'],
  ],
};
