/** Questions supplémentaires – rééducation et nutrition. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_REEDUCATION: Record<string, QuestionBrute[]> = {
  'Rééducation fonctionnelle': [
    ["Après une ligamentoplastie du genou, la rééducation précoce vise d'abord à :", "Contrôler la douleur et l'œdème, récupérer l'extension et le verrouillage du quadriceps", 'Reprendre la course dès le 3e jour', 'Immobiliser le genou pendant 3 mois', 'Masser la cicatrice profondément le premier jour'],
    ["Une contraction isométrique est :", 'Une contraction sans mouvement de l\'articulation', 'Une contraction avec un grand mouvement', 'Un étirement passif', 'Un massage'],
    ["La mobilisation passive est réalisée :", 'Par le thérapeute, sans contraction active du patient', 'Par le patient seul contre résistance', 'Avec des poids lourds', 'Uniquement en piscine'],
    ["Un patient hémiplégique : pour l'aider à s'habiller, on commence par :", 'Le côté atteint (et on déshabille d\'abord le côté sain)', 'Le côté sain', 'Indifféremment', 'Les chaussures'],
    ["La rééducation de l'équilibre chez la personne âgée a pour objectif principal :", 'De prévenir les chutes', 'De faire maigrir', 'D\'améliorer la vue', 'De traiter le diabète'],
    ["L'utilisation de béquilles pour monter un escalier : on monte d'abord :", 'La jambe saine, puis les béquilles et la jambe opérée', 'La jambe opérée', 'Les béquilles seules', 'En sautant à pieds joints'],
    ["Une entorse grave du ligament croisé antérieur se teste notamment par :", 'Le test de Lachman', 'Le score de Glasgow', 'Le test d\'Allen', 'Le score d\'Apgar'],
    ["Le renforcement musculaire progressif repose sur :", 'Une augmentation graduelle de la charge et des répétitions', 'Des charges maximales dès la première séance', 'Le repos complet', 'Des étirements uniquement'],
    ["Une douleur qui augmente fortement et persiste après les séances doit faire :", 'Adapter le programme et en informer le médecin', 'Augmenter l\'intensité', 'Ignorer la douleur', 'Arrêter de boire'],
    ["Après une fracture du poignet plâtrée, on surveille :", 'La couleur, la chaleur, la sensibilité et la mobilité des doigts', 'Uniquement la couleur du plâtre', 'La tension artérielle seule', 'Rien'],
    ["La cryothérapie (froid) est utilisée pour :", 'Diminuer la douleur et l\'œdème en phase aiguë', 'Réchauffer les muscles avant l\'effort', 'Traiter une plaie infectée', 'Augmenter l\'inflammation'],
    ["L'ergothérapie vise surtout à :", "Favoriser l'autonomie dans les activités de la vie quotidienne", 'Traiter les caries', 'Réaliser des radiographies', 'Prescrire des médicaments'],
    ["La lombalgie commune aiguë : la recommandation actuelle est :", 'De maintenir les activités autant que possible, le repos strict prolongé étant déconseillé', 'Un repos strict au lit pendant 3 semaines', 'Une chirurgie immédiate', 'Le port permanent d\'un corset'],
    ["Le bilan articulaire d'un genou en extension complète correspond à :", '0°', '90°', '180°', '45°'],
    ["Un patient sous anticoagulants en rééducation : on évite :", 'Les techniques traumatisantes (massages profonds intenses) sans avis', 'La marche', 'Les exercices respiratoires', 'Les explications'],
  ],
  'Kinésithérapie respiratoire': [
    ["Le drainage bronchique chez le nourrisson est indiqué :", 'Selon la prescription et les recommandations en vigueur, avec prudence', 'Systématiquement pour toute toux', 'Jamais sur prescription', 'Uniquement la nuit'],
    ["L'augmentation du flux expiratoire (AFE) vise à :", 'Mobiliser les sécrétions vers les grosses bronches', 'Bloquer la respiration', 'Augmenter la tension', 'Diminuer la saturation'],
    ["La toux dirigée sert à :", 'Évacuer les sécrétions arrivées dans les voies proximales', 'Provoquer des vomissements', 'Calmer la douleur', 'Mesurer la saturation'],
    ["Après une chirurgie thoracique ou abdominale, la kinésithérapie respiratoire prévient :", 'Les atélectasies et les infections pulmonaires', 'Les fractures', 'Le diabète', 'Les allergies'],
    ["La réhabilitation respiratoire chez le patient BPCO comprend :", "Réentraînement à l'effort, éducation et techniques respiratoires", 'Uniquement du repos', 'Uniquement des antibiotiques', 'Une chirurgie systématique'],
    ["Avant une séance de désencombrement, il est préférable que le patient :", 'Ne vienne pas de manger (risque de vomissement)', 'Ait mangé un repas copieux', 'Soit allongé à plat ventre sans surveillance', 'Ait arrêté son oxygène'],
    ["Le débit expiratoire de pointe (peak-flow) est utile pour suivre :", "L'asthme", 'La glycémie', 'La fonction rénale', 'La vision'],
    ["La ventilation dirigée abdomino-diaphragmatique vise à :", 'Améliorer l\'efficacité de la respiration et diminuer l\'essoufflement', 'Augmenter le travail respiratoire', 'Bloquer le diaphragme', 'Provoquer une apnée'],
    ["Un patient sous oxygène pendant la séance : on surveille :", 'La saturation, la fréquence respiratoire et la tolérance', 'Uniquement la température', 'Uniquement la tension', 'Rien'],
    ["Les signes de détresse respiratoire incluent :", "Tirage, battement des ailes du nez, cyanose, polypnée", 'Une respiration calme et lente', 'Une bonne coloration', 'Un sommeil paisible'],
    ["Les aérosols (nébulisations) prescrits avant la séance servent souvent à :", 'Fluidifier ou dilater les bronches pour faciliter le désencombrement', 'Endormir le patient', 'Remplacer l\'oxygène', 'Mesurer la saturation'],
    ["Le spiromètre incitatif doit être utilisé :", 'Régulièrement, avec des inspirations lentes et profondes', 'Une fois par semaine', 'En soufflant le plus fort possible dedans', 'Uniquement en position couchée à plat'],
    ["Le positionnement du patient (drainage postural) utilise :", 'La gravité pour aider à drainer certains segments pulmonaires', 'Le froid', 'Le bruit', 'La lumière'],
    ["Chez un patient atteint de mucoviscidose, la kinésithérapie respiratoire est :", 'Quotidienne et essentielle au traitement', 'Contre-indiquée', 'Inutile', 'Réservée aux adultes'],
    ["L'hygiène du matériel de kinésithérapie respiratoire (embouts, spiromètres) impose :", 'Un usage individuel ou une désinfection adaptée entre deux patients', 'Le partage sans nettoyage', 'Un rinçage à l\'eau seule entre patients', 'Aucune précaution'],
    ["La saturation qui chute pendant l'effort chez un patient BPCO :", "Impose d'adapter l'intensité et l'oxygène selon la prescription", 'Est sans importance', 'Justifie d\'augmenter l\'effort', 'Doit être ignorée'],
  ],
  'Bilan et évaluation': [
    ["L'échelle de Berg ou le test « Timed Up and Go » évaluent :", "L'équilibre et le risque de chute", 'La fonction rénale', 'La mémoire uniquement', 'La douleur'],
    ["La mesure de Barthel évalue :", "L'autonomie dans les activités de la vie quotidienne", 'La force de préhension seule', 'La saturation', 'La vision'],
    ["Le périmètre de marche correspond à :", 'La distance que le patient peut parcourir avant de devoir s\'arrêter', 'Le tour de taille', 'La longueur des jambes', 'La taille du couloir'],
    ["Un bilan de rééducation doit être :", 'Daté, chiffré et répété pour suivre l\'évolution', 'Fait une seule fois', 'Uniquement oral', 'Fait par la famille'],
    ["L'œdème d'un membre peut se mesurer :", 'Par des mesures de périmètre (centimétriques) répétées aux mêmes repères', 'À l\'œil seulement', 'Avec une balance', 'Avec un thermomètre'],
    ["Le test des 6 minutes de marche évalue :", "La capacité fonctionnelle à l'effort", 'La vision', 'La mémoire', 'L\'équilibre assis'],
    ["La douleur chez une personne âgée non communicante peut être évaluée par :", "Une échelle d'hétéro-évaluation comportementale (type Algoplus, Doloplus)", 'Une échelle visuelle analogique uniquement', 'Aucune échelle', 'Le poids'],
    ["Le dynamomètre de préhension mesure :", 'La force de la main', 'La tension', 'La fréquence respiratoire', 'La température'],
    ["Les objectifs de rééducation sont fixés :", 'Avec le patient, en tenant compte de son projet de vie', 'Sans le patient', 'Par l\'administration', 'Au hasard'],
    ["Le bilan initial doit rechercher aussi :", 'Les contre-indications et les précautions (fractures, anticoagulants, cardiopathie…)', 'Uniquement le nom du médecin', 'Les préférences musicales uniquement', 'Rien d\'autre'],
    ["Une évaluation de la spasticité peut utiliser :", "L'échelle d'Ashworth modifiée", 'Le score d\'Apgar', 'Le score de Glasgow', 'L\'IMC'],
    ["Le bilan de sortie de rééducation sert à :", 'Comparer les résultats aux objectifs et transmettre les informations utiles', 'Facturer uniquement', 'Rien', 'Remplacer le bilan initial'],
    ["Une mesure fiable nécessite :", 'Les mêmes conditions et la même méthode à chaque évaluation', 'Un appareil différent à chaque fois', 'Des positions différentes', 'L\'avis du patient seul'],
    ["Le testing musculaire coté 0 correspond à :", 'Aucune contraction perceptible', 'Une force normale', 'Un mouvement contre résistance', 'Un mouvement complet'],
    ["Le testing musculaire coté 5 correspond à :", 'Une force normale', 'Aucune contraction', 'Un mouvement sans pesanteur', 'Une contraction sans mouvement'],
    ["Le compte rendu de bilan est transmis :", 'Au médecin prescripteur et dans le dossier du patient', 'Uniquement à la famille', 'Sur les réseaux sociaux', 'À personne'],
  ],
  'Nutrition clinique': [
    ["Un aliment riche en protéines de bonne qualité :", 'Les œufs, le poisson, la viande, les produits laitiers', 'Le sucre blanc', 'L\'huile', 'Les boissons sucrées'],
    ["Les fibres alimentaires se trouvent surtout dans :", 'Les légumes, les fruits, les légumineuses et les céréales complètes', 'La viande', 'L\'huile', 'Le sucre'],
    ["L'albumine basse peut être un marqueur :", 'De dénutrition (à interpréter selon l\'inflammation)', 'D\'obésité certaine', 'De déshydratation uniquement', 'De diabète'],
    ["Les besoins hydriques d'un adulte sont en moyenne d'environ :", '1,5 à 2 litres de boisson par jour, à adapter', '0,2 litre par jour', '6 litres par jour pour tous', 'Aucun besoin si on mange'],
    ["La nutrition entérale est :", 'Une alimentation par sonde dans le tube digestif', 'Une alimentation par voie veineuse', 'Une alimentation par la bouche uniquement', 'Un régime sans sel'],
    ["La nutrition parentérale est :", 'Une alimentation administrée par voie veineuse', 'Une alimentation par sonde gastrique', 'Un régime riche en fibres', 'Une boisson enrichie'],
    ["Le syndrome de renutrition inappropriée survient surtout :", 'Lors d\'une réalimentation trop rapide chez un patient très dénutri', 'Chez un patient en surpoids', 'Après un repas normal', 'Chez le sportif'],
    ["Un régime pauvre en sel est souvent prescrit en cas :", "D'hypertension ou d'insuffisance cardiaque", 'D\'anémie', 'De fracture', 'De rhume'],
    ["Chez l'insuffisant rénal chronique, on surveille souvent les apports en :", 'Potassium, phosphore et protéines selon le stade', 'Vitamine C uniquement', 'Eau minérale uniquement', 'Rien'],
    ["Les compléments nutritionnels oraux sont utilisés :", 'Chez les patients dénutris ou à risque, en complément des repas', 'Pour remplacer tous les repas d\'une personne en bonne santé', 'Pour maigrir', 'Uniquement chez l\'enfant'],
    ["Un patient âgé dénutri doit être pesé :", 'Régulièrement (au moins à l\'entrée puis chaque semaine selon le protocole)', 'Jamais', 'Une fois par an', 'Uniquement à la sortie'],
    ["La maladie cœliaque nécessite un régime :", 'Sans gluten', 'Sans sucre', 'Sans protéines', 'Sans eau'],
    ["L'évaluation nutritionnelle comprend :", 'Poids, perte de poids, IMC, apports alimentaires et parfois des dosages biologiques', 'Uniquement la taille', 'Uniquement la tension', 'Uniquement la couleur de peau'],
    ["Les besoins énergétiques sont augmentés en cas :", 'D\'infection, de brûlure étendue ou de chirurgie lourde', 'De repos complet', 'De sommeil', 'De jeûne volontaire'],
    ["Un régime adapté aux troubles de la déglutition utilise :", 'Des textures modifiées (mixée, hachée) et des boissons épaissies selon l\'évaluation', 'Des aliments durs et secs', 'De l\'eau plate rapidement', 'Aucune adaptation'],
  ],
  'Prise en charge du diabète': [
    ["Le diabète de type 1 est principalement dû à :", "Une absence de production d'insuline par le pancréas", 'Un excès de sucre uniquement', 'Une infection urinaire', 'Une allergie'],
    ["Le diabète de type 2 est souvent associé à :", 'Le surpoids, la sédentarité et l\'hérédité', 'Une fracture', 'Une carence en vitamine C', 'Une grippe'],
    ["Les signes d'hyperglycémie importante :", 'Soif intense, urines abondantes, fatigue, amaigrissement', 'Sueurs froides et tremblements', 'Fièvre isolée', 'Toux'],
    ["L'objectif d'HbA1c chez beaucoup de diabétiques de type 2 est souvent :", 'Autour de 7 %, à individualiser', '15 %', '2 %', 'Il n\'y a pas d\'objectif'],
    ["L'éducation thérapeutique du patient diabétique porte notamment sur :", 'L\'autosurveillance, l\'alimentation, l\'activité physique et les signes d\'alerte', 'Uniquement le prix des médicaments', 'La couleur des stylos', 'Rien'],
    ["Les sites d'injection d'insuline doivent être :", 'Alternés pour éviter les lipodystrophies', 'Toujours au même endroit', 'Dans le muscle', 'Dans une veine'],
    ["Le resucrage d'une hypoglycémie est suivi :", "D'un contrôle de glycémie environ 15 minutes après", 'D\'une injection d\'insuline', 'D\'un jeûne', 'D\'aucune surveillance'],
    ["Les pieds d'un patient diabétique doivent être :", 'Examinés régulièrement, lavés, séchés et protégés', 'Trempés longuement dans l\'eau chaude', 'Laissés pieds nus en permanence', 'Coupés avec des ciseaux pointus sans précaution'],
    ["Les aliments à éviter en grande quantité chez le diabétique :", 'Les boissons sucrées et les sucreries', 'Les légumes verts', 'L\'eau', 'Les fibres'],
    ["L'acidocétose diabétique est :", 'Une complication grave, surtout du diabète de type 1, nécessitant une prise en charge urgente', 'Une complication bénigne', 'Un régime alimentaire', 'Une hypoglycémie légère'],
    ["Pendant le jeûne du Ramadan, un patient diabétique doit :", 'Consulter avant pour adapter son traitement et sa surveillance', 'Arrêter tous ses traitements sans avis', 'Doubler ses doses', 'Ne rien changer sans avis'],
    ["L'activité physique chez le diabétique traité par insuline peut provoquer :", 'Une hypoglycémie : il faut adapter les apports ou les doses', 'Une hyperglycémie systématique', 'Aucun effet', 'Une fracture'],
    ["Les complications chroniques du diabète touchent notamment :", 'Les yeux, les reins, les nerfs, le cœur et les vaisseaux', 'Uniquement les cheveux', 'Uniquement la peau', 'Aucun organe'],
    ["Une alimentation équilibrée pour un diabétique répartit les glucides :", 'Sur les différents repas, en privilégiant les féculents complets', 'En un seul repas par jour', 'Uniquement le soir', 'En supprimant tous les glucides'],
    ["L'autosurveillance glycémique se note :", 'Dans un carnet ou une application, pour adapter le traitement', 'Nulle part', 'Uniquement de mémoire', 'Sur les murs'],
    ["Le fond d'œil est recommandé chez le diabétique pour dépister :", 'La rétinopathie diabétique', 'La myopie uniquement', 'L\'otite', 'La carie dentaire'],
  ],
};
