/** Questions supplémentaires – sage-femme. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_SAGEFEMME: Record<string, QuestionBrute[]> = {
  'Suivi de grossesse': [
    ["La date présumée d'accouchement se calcule habituellement à partir :", 'Du premier jour des dernières règles', 'Du dernier jour des dernières règles, en ajoutant neuf mois exacts', 'De la date du mariage', 'Du poids de la mère'],
    ["L'échographie du premier trimestre (vers 11–14 SA) permet notamment :", 'De dater la grossesse, clarté nucale', 'De connaître le poids de naissance exact', 'De déclencher l\'accouchement', "De confirmer le sexe du fœtus et d'estimer le poids de naissance"],
    ["Quel signe doit faire consulter en urgence pendant la grossesse ?", 'Saignements ou baisse des mouvements du bébé', 'Une envie fréquente d\'uriner au premier trimestre', 'Des nausées le matin', "Une envie fréquente d'uriner et des nausées le matin au premier trimestre"],
    ["Les signes de prééclampsie peuvent associer :", 'Maux de tête, troubles visuels, douleur en barre épigastrique, œdèmes brutaux', 'Uniquement des démangeaisons', 'Une faim excessive et une prise de poids rapide au 1er trimestre', 'Des démangeaisons des mains et des pieds, surtout la nuit, sans autre signe'],
    ["La hauteur utérine mesurée en consultation sert à :", 'Surveiller la croissance du fœtus', "Estimer la date d'accouchement et la position exacte du placenta", 'Calculer la glycémie', 'Prévoir le sexe du bébé et la date exacte'],
    ["La toxoplasmose est surveillée chez la femme enceinte non immunisée car :", 'Elle peut atteindre le fœtus', 'Elle provoque toujours l\'accouchement', 'Elle est sans danger', 'Elle protège le fœtus'],
    ["Conseil hygiéno-diététique à une femme enceinte non immunisée contre la toxoplasmose :", 'Bien cuire la viande et laver soigneusement fruits et légumes', 'Manger la viande saignante', 'Toucher la litière du chat sans gants', 'Éviter les légumes crus et privilégier la viande peu cuite, plus riche en fer'],
    ["L'alcool pendant la grossesse :", 'Est à éviter totalement', 'Est autorisé en petite quantité chaque jour', 'Est recommandé au troisième trimestre', 'Est sans risque pour le fœtus'],
    ["Une femme Rhésus négatif avec un conjoint Rhésus positif nécessite :", 'Une prévention par immunoglobulines anti-D', 'Aucune surveillance', 'Une transfusion de sang Rhésus positif à la mère en fin de grossesse, par précaution', 'Un arrêt de la grossesse'],
    ["Les mouvements actifs du fœtus sont en général perçus par la mère :", 'Entre 16 et 22 SA environ', 'Dès la 4e SA', 'Seulement après 38 SA', 'Jamais avant l\'accouchement'],
    ["Le diabète gestationnel expose surtout à :", 'Une macrosomie fœtale', 'Un retard de croissance du bébé et une prématurité systématique', 'Aucune complication', 'Une myopie maternelle'],
    ["Une menace d'accouchement prématuré se manifeste par :", 'Contractions et modifications du col avant 37 SA', 'Des nausées au premier trimestre', 'Des contractions irrégulières et indolores après un effort, sans modification du col', 'Des mouvements fœtaux actifs'],
    ["La supplémentation en fer pendant la grossesse vise à prévenir :", "L'anémie", 'La prééclampsie de façon certaine', 'Le diabète', 'L\'hypertension'],
    ["L'entretien prénatal précoce permet surtout :", "D'identifier les besoins, les difficultés et de préparer la naissance", 'De réaliser l\'accouchement', "De programmer la date de l'accouchement et de choisir la maternité", 'De prescrire des antibiotiques préventifs'],
    ["Une femme enceinte se plaint de brûlures en urinant. Il faut :", 'Rechercher une infection urinaire (ECBU)', 'Attendre l\'accouchement', "Lui conseiller de boire moins pour réduire les brûlures en attendant l'accouchement", 'Ne rien faire, c\'est normal'],
  ],
  'Accouchement eutocique': [
    ["Le premier stade du travail correspond à :", 'La dilatation du col', 'L\'expulsion du bébé', "La descente et l'expulsion du bébé après dilatation complète", 'La surveillance du post-partum'],
    ["Le deuxième stade du travail correspond à :", "L'expulsion du fœtus", 'La dilatation du col', 'La délivrance', 'La consultation prénatale'],
    ["Un liquide amniotique teinté (méconial) doit faire :", "Surveiller le cœur fœtal, prévenir l'équipe", "Ignorer l'information si la mère se sent bien", 'Faire marcher la patiente pour accélérer le travail sans modifier la surveillance', 'Arrêter la surveillance du rythme cardiaque fœtal'],
    ["Le rythme cardiaque fœtal normal se situe en général entre :", '110 et 160 battements/min', '60 et 90 battements/min', '180 et 220 battements/min', '40 et 60 battements/min'],
    ["Le partogramme sert à :", 'Suivre graphiquement le travail', 'Calculer le prix de l\'accouchement', 'Noter le menu de la patiente', "Prévoir la date de sortie et organiser le suivi de la mère après l'accouchement"],
    ["Pendant le travail, une position verticale ou la mobilité de la patiente :", 'Peut faciliter la descente du bébé', 'Est toujours interdite', 'Provoque systématiquement une hémorragie', 'Est déconseillée car elle empêche toute surveillance du rythme cardiaque du bébé'],
    ["Après la naissance, le clampage du cordon :", "Peut être retardé d'environ une minute", 'Doit toujours être fait avant la sortie de la tête', 'Doit toujours être immédiat, dans les secondes qui suivent la naissance', 'Se fait au bout d\'une heure obligatoirement'],
    ["L'examen du placenta après la délivrance vérifie :", "Qu'il est complet", 'Sa couleur uniquement', 'Sa couleur et son odeur, pour dépister une infection maternelle', 'Rien'],
    ["Un globe utérin bien formé après la délivrance signifie :", 'Un utérus bien rétracté', 'Une hémorragie en cours', 'Un placenta retenu certain', 'Une rétention de placenta nécessitant une révision utérine'],
    ["La surveillance en salle de naissance après l'accouchement dure en général :", 'Environ 2 heures', 'Une quinzaine de minutes, le temps de vérifier le globe utérin', '24 heures en salle de naissance', 'Aucune surveillance'],
    ["L'épisiotomie :", "N'est pas systématique", 'Est obligatoire à chaque accouchement', 'Est recommandée chez toutes les femmes qui accouchent de leur premier enfant', 'Se fait avant le début du travail'],
    ["Une procidence du cordon (cordon devant la présentation) est :", 'Une urgence obstétricale', 'Une situation normale', 'Une complication sans gravité', 'Un signe de fin de travail normale'],
    ["Une rupture des membranes sans contractions à terme impose :", 'Une consultation à la maternité', 'D\'attendre une semaine à domicile', "D'attendre les contractions à domicile pendant plusieurs jours, sans consulter", 'Aucune surveillance'],
    ["Une déchirure périnéale après l'accouchement :", 'Est examinée et suturée si nécessaire', 'Est toujours laissée sans soin', 'Est une contre-indication à l\'allaitement', 'Nécessite une césarienne'],
    ["Le peau-à-peau à la naissance favorise :", 'La régulation thermique du bébé, le lien mère-enfant et la première tétée', "Le risque d'hypothermie, ce qui impose de le limiter à quelques secondes", 'Les infections', 'Le retard de l\'allaitement'],
  ],
  'Soins néonataux': [
    ["Le poids de naissance moyen d'un nouveau-né à terme est d'environ :", '2 à 2,5 kg en moyenne', '1 kg', '6 kg', '500 g'],
    ["La perte de poids physiologique des premiers jours est en général :", 'Inférieure à 10 % du poids de naissance, récupéré vers 10–15 jours', "Jusqu'à 20 % du poids de naissance, récupérée au bout de deux mois", 'Inexistante', 'Définitive, sans récupération attendue avant 2 mois'],
    ["Un ictère (jaunisse) apparaissant dans les 24 premières heures de vie est :", 'Anormal, à signaler vite', 'Physiologique, il disparaît spontanément en quelques jours', "Un signe de bonne santé et d'appétit", 'Sans aucune importance chez le nouveau-né'],
    ["La fréquence respiratoire normale d'un nouveau-né est d'environ :", '40 à 60 cycles/min', '10 à 15 cycles/min', '80 à 100 cycles/min', '20 cycles/min exactement'],
    ["Les soins du cordon ombilical reposent sur :", 'Une hygiène simple : garder le cordon propre et sec', 'L\'application de poudre ou de produits traditionnels', 'Le recouvrir d\'un pansement serré et humide', 'Tirer dessus pour qu\'il tombe vite'],
    ["Le cordon ombilical tombe en général :", 'Entre 5 et 15 jours', 'Le jour de la naissance', 'Entre 1 et 2 mois après la naissance, quand le nombril est cicatrisé', 'Jamais'],
    ["Le dépistage néonatal par prélèvement de sang au talon permet de repérer :", "Certaines maladies rares (comme l'hypothyroïdie congénitale) selon le programme du pays", "Le groupe sanguin et le risque d'allergie alimentaire du nouveau-né", 'La taille adulte', 'Le groupe scolaire'],
    ["Un nouveau-né à risque d'hypoglycémie (mère diabétique, petit poids) nécessite :", 'Glycémie et alimentation précoce', 'Un jeûne de 12 heures', 'Un bain froid', 'Aucune surveillance'],
    ["Les premières selles du nouveau-né, noires et collantes, s'appellent :", 'Le méconium', 'Le colostrum', 'Le vernix', 'Le lanugo'],
    ["Le vernix caseosa est :", 'Un enduit blanchâtre qui protège la peau du nouveau-né', 'Une infection de la peau', 'Une infection cutanée bénigne du nouveau-né', 'Une infection de la peau à traiter par un antiseptique'],
    ["La température idéale d'une salle de naissance pour accueillir un nouveau-né est d'environ :", '18 à 20 °C, comme une chambre', '15 °C', '35 °C', '10 °C'],
    ["Un nouveau-né qui ne respire pas à la naissance après séchage et stimulation nécessite :", "Une ventilation au masque immédiatement selon l'algorithme de réanimation néonatale", 'Un bain', 'Une aspiration prolongée de la bouche et du nez avant tout autre geste', 'Une mise au sein immédiate pour le stimuler'],
    ["La vaccination à la naissance en Tunisie comprend notamment :", "Le BCG et l'hépatite B (1re dose)", 'Aucun vaccin', 'Le vaccin contre la rougeole et la poliomyélite injectable, dès la salle de naissance', 'Le vaccin contre la rougeole et les oreillons'],
    ["Le couchage recommandé du nouveau-né :", 'Sur le dos, sans oreiller ni tour de lit', 'Sur le ventre, la tête tournée sur le côté pour éviter les régurgitations', 'Avec plusieurs couvertures épaisses', 'Dans le lit des parents entre deux oreillers'],
    ["Un nouveau-né fébrile (température ≥ 38 °C) doit :", 'Être examiné rapidement par un médecin', 'Être simplement déshabillé et surveillé une semaine', 'Recevoir de l\'aspirine', 'Être baigné à l\'eau froide'],
  ],
  'Allaitement maternel': [
    ["Pendant les premières semaines, un nouveau-né allaité tète en général :", 'Au moins 8 fois par 24 heures, à la demande', 'Deux fois par jour, à heures fixes, matin et soir', 'Toutes les 4 heures exactement, en le réveillant si nécessaire', 'Toutes les 6 heures, en réveillant le bébé si besoin'],
    ["Un signe que le bébé reçoit suffisamment de lait :", 'Couches bien mouillées, prise de poids régulière', 'Il pleure tout le temps', 'Il dort de longues périodes sans réclamer, même la nuit, dès les premiers jours', 'Ses urines sont très foncées'],
    ["Des crevasses du mamelon sont le plus souvent dues à :", 'Une mauvaise prise du sein', 'Un lait de mauvaise qualité', 'Une alimentation trop salée', 'Des tétées trop fréquentes, qui fatiguent la peau du mamelon'],
    ["Un engorgement mammaire se soulage par :", 'Des tétées fréquentes et efficaces, éventuellement de la chaleur avant et du froid après', 'L\'arrêt brutal de l\'allaitement', 'Une restriction des boissons chez la mère allaitante', 'Un espacement des tétées et un bandage serré des seins pendant quelques jours'],
    ["Une mastite se manifeste par :", 'Une zone rouge, chaude, douloureuse, avec fièvre', 'Une simple fatigue', 'Un lait plus sucré', 'Une perte de cheveux'],
    ["En cas de mastite, l'allaitement :", 'Peut en général être poursuivi', "Doit être suspendu du côté atteint jusqu'à la fin du traitement antibiotique", 'Est dangereux pour le bébé dans tous les cas', 'Doit être remplacé par de l\'eau sucrée'],
    ["Les compléments d'eau ou de lait artificiel chez un nouveau-né allaité en bonne santé :", 'Ne sont pas nécessaires', 'Sont obligatoires chaque jour', 'Sont conseillés la nuit pour laisser la mère se reposer pendant les premières semaines', 'Remplacent le colostrum'],
    ["La montée de lait survient généralement :", 'Entre le 2e et le 4e jour', 'Le jour de l\'accouchement', 'Dès la première heure, au moment de la première tétée en salle de naissance', 'Pendant la grossesse uniquement'],
    ["Le lait maternel exprimé peut être conservé au réfrigérateur (environ 4 °C) :", 'Environ 48 heures', '1 heure seulement', "Une semaine, dans la porte du réfrigérateur pour qu'il soit facile d'accès", 'Indéfiniment'],
    ["Pour décongeler du lait maternel, on évite :", 'Le four à micro-ondes', 'Un chauffe-biberon électrique', 'Le réfrigérateur, car la décongélation y est trop lente pour garder ses qualités', "Le bain-marie à l'eau tiède"],
    ["Quel médicament prendre pendant l'allaitement ?", 'Ceux validés comme compatibles par un professionnel', 'N\'importe lequel sans avis', "Aucun traitement n'est jamais possible pendant toute la durée de l'allaitement", 'Les mêmes que pendant la grossesse sans vérifier'],
    ["La position « ballon de rugby » est utile notamment :", 'Après une césarienne', 'Pour les bébés qui régurgitent beaucoup, afin de les garder en position allongée sur le dos', 'Uniquement pour les biberons', 'Pour les bébés de plus de 2 ans'],
    ["Le réflexe d'éjection du lait est favorisé par :", "L'ocytocine", "L'insuline rapide", 'La prolactine seule, stimulée par le stress et la fatigue de la mère', 'La progestérone'],
    ["Les avantages de l'allaitement pour le bébé incluent :", 'Une protection contre certaines infections', 'Une absence totale de maladies', 'Une croissance plus rapide que la normale', 'Aucun avantage'],
    ["Une mère qui reprend le travail et veut poursuivre l'allaitement peut :", 'Tirer et conserver son lait', "Arrêter l'allaitement deux semaines avant la reprise pour habituer le bébé au biberon", 'Donner du lait non conservé au froid', 'Allaiter seulement une fois par semaine'],
    ["Les signes d'une bonne succion au sein :", 'Succions amples, déglutitions audibles', 'Bruits de claquement de langue', 'Des succions rapides et superficielles, joues creusées, avec des bruits de claquement', 'Douleur intense de la mère pendant toute la tétée'],
  ],
};
