/** Questions supplémentaires – sage-femme. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_SAGEFEMME: Record<string, QuestionBrute[]> = {
  'Suivi de grossesse': [
    ["La date présumée d'accouchement se calcule habituellement à partir :", 'Du premier jour des dernières règles (ou de l\'échographie de datation)', 'Du dernier jour des règles', 'De la date du mariage', 'Du poids de la mère'],
    ["L'échographie du premier trimestre (vers 11–14 SA) permet notamment :", 'De dater la grossesse et de mesurer la clarté nucale', 'De connaître le poids de naissance exact', 'De déclencher l\'accouchement', 'De diagnostiquer le diabète gestationnel'],
    ["Quel signe doit faire consulter en urgence pendant la grossesse ?", 'Des saignements vaginaux ou une diminution des mouvements du bébé', 'Une envie fréquente d\'uriner au premier trimestre', 'Des nausées le matin', 'Une légère fatigue'],
    ["Les signes de prééclampsie peuvent associer :", 'Maux de tête, troubles visuels, douleur en barre épigastrique, œdèmes brutaux', 'Uniquement des démangeaisons', 'Une faim excessive', 'Une toux'],
    ["La hauteur utérine mesurée en consultation sert à :", 'Surveiller la croissance du fœtus', 'Mesurer la tension', 'Calculer la glycémie', 'Prévoir le sexe du bébé'],
    ["La toxoplasmose est surveillée chez la femme enceinte non immunisée car :", 'Elle peut atteindre le fœtus', 'Elle provoque toujours l\'accouchement', 'Elle est sans danger', 'Elle protège le fœtus'],
    ["Conseil hygiéno-diététique à une femme enceinte non immunisée contre la toxoplasmose :", 'Bien cuire la viande et laver soigneusement fruits et légumes', 'Manger la viande saignante', 'Toucher la litière du chat sans gants', 'Éviter de se laver les mains'],
    ["L'alcool pendant la grossesse :", 'Est à éviter totalement', 'Est autorisé en petite quantité chaque jour', 'Est recommandé au troisième trimestre', 'Est sans risque pour le fœtus'],
    ["Une femme Rhésus négatif avec un conjoint Rhésus positif nécessite :", 'Une prévention de l\'allo-immunisation (immunoglobulines anti-D selon le protocole)', 'Aucune surveillance', 'Une transfusion systématique', 'Un arrêt de la grossesse'],
    ["Les mouvements actifs du fœtus sont en général perçus par la mère :", 'Entre 16 et 22 SA environ', 'Dès la 4e SA', 'Seulement après 38 SA', 'Jamais avant l\'accouchement'],
    ["Le diabète gestationnel expose surtout à :", 'Une macrosomie fœtale et des complications à l\'accouchement', 'Une petite taille du bébé uniquement', 'Aucune complication', 'Une myopie maternelle'],
    ["Une menace d'accouchement prématuré se manifeste par :", 'Des contractions régulières et des modifications du col avant 37 SA', 'Des nausées au premier trimestre', 'Une prise de poids régulière', 'Des mouvements fœtaux actifs'],
    ["La supplémentation en fer pendant la grossesse vise à prévenir :", "L'anémie", 'La prééclampsie de façon certaine', 'Le diabète', 'L\'hypertension'],
    ["L'entretien prénatal précoce permet surtout :", 'D\'identifier les besoins, les difficultés et de préparer la naissance', 'De réaliser l\'accouchement', 'De choisir le prénom', 'De prescrire des antibiotiques'],
    ["Une femme enceinte se plaint de brûlures en urinant. Il faut :", 'Rechercher une infection urinaire (ECBU) car elle peut favoriser une prématurité', 'Attendre l\'accouchement', 'Lui conseiller de boire moins', 'Ne rien faire, c\'est normal'],
  ],
  'Accouchement eutocique': [
    ["Le premier stade du travail correspond à :", 'La dilatation du col jusqu\'à dilatation complète', 'L\'expulsion du bébé', 'La délivrance du placenta', 'La surveillance du post-partum'],
    ["Le deuxième stade du travail correspond à :", "L'expulsion du fœtus", 'La dilatation du col', 'La délivrance', 'La consultation prénatale'],
    ["Un liquide amniotique teinté (méconial) doit faire :", 'Renforcer la surveillance du rythme cardiaque fœtal et prévenir l\'équipe', 'Ignorer l\'information', 'Faire marcher la patiente', 'Arrêter la surveillance'],
    ["Le rythme cardiaque fœtal normal se situe en général entre :", '110 et 160 battements/min', '60 et 90 battements/min', '180 et 220 battements/min', '40 et 60 battements/min'],
    ["Le partogramme sert à :", "Suivre graphiquement l'évolution du travail et repérer les anomalies", 'Calculer le prix de l\'accouchement', 'Noter le menu de la patiente', 'Prévoir la date de sortie'],
    ["Pendant le travail, une position verticale ou la mobilité de la patiente :", 'Peut faciliter la descente du bébé et le confort', 'Est toujours interdite', 'Provoque systématiquement une hémorragie', 'Empêche la surveillance'],
    ["Après la naissance, le clampage du cordon :", 'Peut être retardé d\'environ une minute chez un nouveau-né qui va bien', 'Doit toujours être fait avant la sortie de la tête', 'Est inutile', 'Se fait au bout d\'une heure obligatoirement'],
    ["L'examen du placenta après la délivrance vérifie :", "Qu'il est complet (cotylédons et membranes)", 'Sa couleur uniquement', 'Son poids pour la facture', 'Rien'],
    ["Un globe utérin bien formé après la délivrance signifie :", 'Que l\'utérus est bien rétracté, ce qui limite le saignement', 'Une hémorragie en cours', 'Un placenta retenu certain', 'Une infection'],
    ["La surveillance en salle de naissance après l'accouchement dure en général :", 'Environ 2 heures (saignements, tension, globe utérin)', '5 minutes', '24 heures en salle de naissance', 'Aucune surveillance'],
    ["L'épisiotomie :", "N'est pas systématique ; elle se décide selon la situation", 'Est obligatoire à chaque accouchement', 'Est interdite', 'Se fait avant le début du travail'],
    ["Une procidence du cordon (cordon devant la présentation) est :", 'Une urgence obstétricale', 'Une situation normale', 'Une complication sans gravité', 'Un signe de fin de travail normale'],
    ["Une rupture des membranes sans contractions à terme impose :", 'Une consultation à la maternité pour évaluation', 'D\'attendre une semaine à domicile', 'Un bain chaud prolongé', 'Aucune surveillance'],
    ["Une déchirure périnéale après l'accouchement :", 'Est examinée et suturée si nécessaire', 'Est toujours laissée sans soin', 'Est une contre-indication à l\'allaitement', 'Nécessite une césarienne'],
    ["Le peau-à-peau à la naissance favorise :", 'La régulation thermique du bébé, le lien mère-enfant et la première tétée', 'L\'hypothermie', 'Les infections', 'Le retard de l\'allaitement'],
  ],
  'Soins néonataux': [
    ["Le poids de naissance moyen d'un nouveau-né à terme est d'environ :", '3 à 3,5 kg', '1 kg', '6 kg', '500 g'],
    ["La perte de poids physiologique des premiers jours est en général :", 'Inférieure à 10 % du poids de naissance, récupéré vers 10–15 jours', 'Supérieure à 20 %', 'Inexistante', 'Définitive'],
    ["Un ictère (jaunisse) apparaissant dans les 24 premières heures de vie est :", 'Anormal et doit être signalé rapidement', 'Toujours normal', 'Un signe de bonne santé', 'Sans aucune importance'],
    ["La fréquence respiratoire normale d'un nouveau-né est d'environ :", '40 à 60 cycles/min', '10 à 15 cycles/min', '80 à 100 cycles/min', '20 cycles/min exactement'],
    ["Les soins du cordon ombilical reposent sur :", 'Une hygiène simple : garder le cordon propre et sec', 'L\'application de poudre ou de produits traditionnels', 'Le recouvrir d\'un pansement serré et humide', 'Tirer dessus pour qu\'il tombe vite'],
    ["Le cordon ombilical tombe en général :", 'Entre 5 et 15 jours après la naissance', 'Le jour de la naissance', 'Après 2 mois', 'Jamais'],
    ["Le dépistage néonatal par prélèvement de sang au talon permet de repérer :", 'Certaines maladies rares (comme l\'hypothyroïdie congénitale) selon le programme du pays', 'La couleur des yeux', 'La taille adulte', 'Le groupe scolaire'],
    ["Un nouveau-né à risque d'hypoglycémie (mère diabétique, petit poids) nécessite :", 'Une surveillance de la glycémie et une alimentation précoce', 'Un jeûne de 12 heures', 'Un bain froid', 'Aucune surveillance'],
    ["Les premières selles du nouveau-né, noires et collantes, s'appellent :", 'Le méconium', 'Le colostrum', 'Le vernix', 'Le lanugo'],
    ["Le vernix caseosa est :", 'Un enduit blanchâtre qui protège la peau du nouveau-né', 'Une infection de la peau', 'Une maladie du sang', 'Un médicament'],
    ["La température idéale d'une salle de naissance pour accueillir un nouveau-né est d'environ :", '23 à 25 °C', '15 °C', '35 °C', '10 °C'],
    ["Un nouveau-né qui ne respire pas à la naissance après séchage et stimulation nécessite :", 'Une ventilation au masque immédiatement selon l\'algorithme de réanimation néonatale', 'Un bain', 'Une pesée', 'Une tétée'],
    ["La vaccination à la naissance en Tunisie comprend notamment :", 'Le BCG et la première dose contre l\'hépatite B, selon le calendrier national', 'Aucun vaccin', 'Le vaccin contre la grippe uniquement', 'Le vaccin contre la rage'],
    ["Le couchage recommandé du nouveau-né :", 'Sur le dos, dans un lit sans oreiller ni tour de lit', 'Sur le ventre', 'Avec plusieurs couvertures épaisses', 'Dans le lit des parents entre deux oreillers'],
    ["Un nouveau-né fébrile (température ≥ 38 °C) doit :", 'Être examiné rapidement par un médecin', 'Être simplement déshabillé et surveillé une semaine', 'Recevoir de l\'aspirine', 'Être baigné à l\'eau froide'],
  ],
  'Allaitement maternel': [
    ["Pendant les premières semaines, un nouveau-né allaité tète en général :", 'Au moins 8 fois par 24 heures, à la demande', 'Deux fois par jour', 'Toutes les 6 heures exactement', 'Uniquement la nuit'],
    ["Un signe que le bébé reçoit suffisamment de lait :", 'Plusieurs couches mouillées par jour et une prise de poids régulière', 'Il pleure tout le temps', 'Il dort 12 heures sans téter', 'Ses urines sont très foncées'],
    ["Des crevasses du mamelon sont le plus souvent dues à :", 'Une mauvaise position ou une mauvaise prise du sein', 'Un lait de mauvaise qualité', 'Une alimentation trop salée', 'Un excès de tétées'],
    ["Un engorgement mammaire se soulage par :", 'Des tétées fréquentes et efficaces, éventuellement de la chaleur avant et du froid après', 'L\'arrêt brutal de l\'allaitement', 'Un jeûne de la mère', 'Un bandage serré des seins'],
    ["Une mastite se manifeste par :", 'Une zone du sein rouge, chaude, douloureuse, souvent avec de la fièvre', 'Une simple fatigue', 'Un lait plus sucré', 'Une perte de cheveux'],
    ["En cas de mastite, l'allaitement :", 'Peut en général être poursuivi, avec un avis médical', 'Doit toujours être arrêté définitivement', 'Est dangereux pour le bébé dans tous les cas', 'Doit être remplacé par de l\'eau sucrée'],
    ["Les compléments d'eau ou de lait artificiel chez un nouveau-né allaité en bonne santé :", 'Ne sont pas nécessaires sans indication médicale', 'Sont obligatoires chaque jour', 'Augmentent la lactation', 'Remplacent le colostrum'],
    ["La montée de lait survient généralement :", 'Entre le 2e et le 4e jour après l\'accouchement', 'Le jour de l\'accouchement', 'Après un mois', 'Pendant la grossesse uniquement'],
    ["Le lait maternel exprimé peut être conservé au réfrigérateur (environ 4 °C) :", 'Environ 48 heures selon les recommandations courantes', '1 heure seulement', '1 mois', 'Indéfiniment'],
    ["Pour décongeler du lait maternel, on évite :", 'Le four à micro-ondes', 'Le réfrigérateur', 'Le bain-marie tiède', 'L\'eau tiède'],
    ["Quel médicament prendre pendant l'allaitement ?", "Uniquement ceux validés par un médecin ou un pharmacien comme compatibles", 'N\'importe lequel sans avis', 'Aucun traitement n\'est jamais possible', 'Les mêmes que pendant la grossesse sans vérifier'],
    ["La position « ballon de rugby » est utile notamment :", 'Après une césarienne ou pour des jumeaux', 'Pour faire dormir la mère', 'Uniquement pour les biberons', 'Pour les bébés de plus de 2 ans'],
    ["Le réflexe d'éjection du lait est favorisé par :", "L'ocytocine, stimulée par la succion et la détente de la mère", "L'insuline", 'Le stress', 'Le froid'],
    ["Les avantages de l'allaitement pour le bébé incluent :", 'Une protection contre certaines infections', 'Une absence totale de maladies', 'Une croissance plus rapide que la normale', 'Aucun avantage'],
    ["Une mère qui reprend le travail et veut poursuivre l'allaitement peut :", 'Tirer son lait et le conserver selon les règles d\'hygiène', 'Arrêter forcément l\'allaitement', 'Donner du lait non conservé au froid', 'Allaiter seulement une fois par semaine'],
    ["Les signes d'une bonne succion au sein :", 'Succions lentes et profondes avec des déglutitions audibles', 'Bruits de claquement de langue', 'Joues creusées', 'Douleur intense de la mère pendant toute la tétée'],
  ],
};
