/** Questions supplémentaires – pédiatrie et encadrement des soins. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_SPECIALITES: Record<string, QuestionBrute[]> = {
  'Soins pédiatriques': [
    ["La fréquence respiratoire normale d'un enfant de 1 à 5 ans est d'environ :", '20 à 30 cycles/min', '5 à 10 cycles/min', '60 à 80 cycles/min', '100 cycles/min'],
    ["Le calcul d'une dose pédiatrique : 15 mg/kg pour un enfant de 12 kg donne :", '180 mg', '15 mg', '120 mg', '1 800 mg'],
    ["La bronchiolite du nourrisson est le plus souvent due :", 'À un virus (souvent le VRS)', 'À une bactérie systématiquement', 'À une allergie', 'À une carence en fer'],
    ["Les signes de gravité d'une bronchiolite incluent :", "Difficulté à s'alimenter, signes de lutte respiratoire, pauses respiratoires", 'Un simple nez qui coule', 'Une toux légère et un nez qui coule depuis quelques jours', 'Un bon appétit et un sommeil calme et réparateur'],
    ["Pour réhydrater un enfant atteint de diarrhée sans signe de gravité, on utilise :", 'Un SRO en petites quantités', "De l'eau très sucrée à volonté", 'Des boissons gazeuses sucrées, bues en grandes quantités', 'Un jeûne complet de 24 heures'],
    ["La douleur chez l'enfant de moins de 4 ans s'évalue avec :", 'Une échelle comportementale', "Une échelle numérique de 0 à 10 qu'il remplit seul avec ses parents", 'Aucune échelle', 'La tension artérielle seule'],
    ["Le calendrier vaccinal de l'enfant doit être :", 'Vérifié à chaque occasion', 'Ignoré à l\'hôpital', 'Rempli par la famille seule', "Vérifié uniquement par le médecin traitant, jamais à l'hôpital"],
    ["La présence des parents lors des soins chez l'enfant :", 'Est en général favorable', 'Augmente toujours son anxiété', "Augmente systématiquement l'anxiété et la douleur de l'enfant", "N'a aucun intérêt pour l'enfant hospitalisé"],
    ["Une fièvre chez un nourrisson de moins de 3 mois :", 'Impose un avis médical rapide', 'Est toujours bénigne', 'Se traite par un bain froid', 'Ne nécessite aucune surveillance'],
    ["La déshydratation sévère chez l'enfant se manifeste par :", 'Une somnolence, des yeux creux, une peau qui garde le pli et une diminution des urines', 'Une agitation joyeuse', 'Une prise de poids et des urines claires', 'Une agitation, des urines abondantes et claires et une prise de poids'],
    ["La sécurité d'un enfant hospitalisé impose notamment :", 'Barrières relevées, rien à portée', 'De le laisser seul sans surveillance', 'De lui laisser des petits objets', "De laisser ses médicaments sur la table de nuit pour qu'il les prenne seul"],
    ["Pour un enfant, les explications avant un soin doivent être :", 'Adaptées à son âge, honnêtes et rassurantes', 'Absentes pour ne pas l\'effrayer', 'Fausses (« ça ne fera rien ») systématiquement', 'Données uniquement aux parents'],
    ["La crème anesthésiante locale avant une ponction veineuse chez l'enfant :", 'Est appliquée assez longtemps avant', 'Agit immédiatement et peut donc être appliquée juste avant la piqûre', 'Est contre-indiquée chez tous les enfants', 'S\'applique après la ponction'],
    ["Les signes d'une détresse respiratoire chez le nourrisson incluent :", 'Tirage, geignement, teint gris', 'Un sommeil calme et une respiration régulière', 'Une bonne prise des biberons et un teint rosé', 'Une respiration lente et régulière avec une bonne prise des biberons'],
  ],
  'Encadrement et organisation des soins': [
    ["La fiche de poste d'un soignant décrit :", 'Missions, responsabilités, hiérarchie', 'Son salaire, ses primes et ses horaires de travail uniquement', 'Ses congés', 'Sa vie privée'],
    ["L'entretien annuel d'évaluation sert à :", "Faire le bilan de l'année, fixer des objectifs et identifier les besoins de formation", "Sanctionner les erreurs de l'année et décider des augmentations", 'Fixer les vacances uniquement', "Remplacer les transmissions écrites de l'année"],
    ["Un absentéisme élevé dans une équipe doit faire rechercher :", 'Des causes organisationnelles', 'Uniquement la paresse', 'Rien', 'Un coupable unique, pour le sanctionner et dissuader les autres'],
    ["La délégation efficace suppose :", 'Une tâche claire, suivie', "De tout déléguer sans contrôle, par confiance envers l'équipe", 'De ne jamais déléguer', 'De déléguer uniquement les tâches pénibles sans explication'],
    ["Une réunion de service efficace comprend :", 'Ordre du jour, durée, compte rendu', 'Aucune préparation', 'Uniquement des reproches sur les erreurs de la semaine', "Une durée illimitée, pour que chacun puisse s'exprimer librement"],
    ["Lors d'un pic d'activité imprévu, le surveillant :", 'Réorganise les priorités, mobilise des renforts si possible et informe sa hiérarchie', "Ne change rien et demande à l'équipe de faire des heures supplémentaires", "Demande à l'équipe de rester sans limite", "Ne change rien à l'organisation"],
    ["La charge en soins d'un service se mesure notamment avec :", "Des outils d'évaluation de la dépendance et de la gravité des patients", 'Le nombre de fenêtres', "Le nombre de visiteurs et d'appels téléphoniques reçus par jour", 'Le budget de la cafétéria'],
    ["Le plan de formation d'un service doit :", 'Répondre aux besoins identifiés', 'Concerner uniquement le surveillant', 'Être fixé au hasard', "Être identique chaque année, pour garantir l'équité entre les agents"],
    ["Un conflit entre un soignant et un médecin doit être géré :", 'Par un échange en privé, factuel, centré sur le patient, avec médiation si nécessaire', "Devant l'équipe", "Par un mail adressé à toute l'équipe, pour que chacun soit informé", "En ignorant le problème jusqu'à ce qu'il se règle seul"],
    ["Le tutorat d'un étudiant en stage comprend :", 'Accueil, objectifs, suivi, évaluation', 'Le laisser seul en autonomie totale dès le premier jour pour le former', 'Lui confier uniquement des tâches de ménage', "Aucun suivi, l'école se chargeant de tout"],
    ["La gestion du stock et du matériel du service relève :", "De l'organisation du surveillant, en lien avec la pharmacie et les services techniques", 'Uniquement des patients', 'Uniquement de la pharmacie, sans participation du service', "Uniquement des services techniques de l'établissement"],
    ["La motivation d'une équipe est favorisée par :", 'Reconnaissance et participation', 'Les reproches publics, qui incitent chacun à faire mieux', 'L\'absence de communication', 'Les changements de planning sans prévenir'],
    ["Un nouveau protocole de soins est mis en place. Le surveillant :", "Forme l'équipe et vérifie", "L'affiche en salle de soins et laisse chacun l'appliquer à sa façon", 'Le garde dans son bureau', 'Laisse chacun l\'interpréter'],
    ["Le surveillant de nuit est notamment responsable :", 'De la sécurité des soins la nuit', 'Uniquement de la fermeture des portes', 'De la cuisine', 'Uniquement des admissions administratives et de la fermeture des portes'],
    ["Pour prévenir l'épuisement d'une équipe, l'encadrant peut :", 'Équilibrer les plannings, écouter', 'Augmenter les heures supplémentaires pour réduire la charge de chacun', 'Supprimer les pauses', 'Ignorer les signes de fatigue'],
  ],
  'Qualité et gestion des risques': [
    ["La démarche qualité repose sur le cycle :", 'Planifier, faire, vérifier, améliorer', 'Commencer, abandonner, oublier', 'Punir, contrôler, sanctionner', 'Acheter, stocker, jeter'],
    ["Un indicateur qualité sert à :", "Mesurer pour suivre l'évolution", 'Remplacer les soins', 'Décorer le service', 'Fixer les salaires et les primes de chaque soignant du service'],
    ["L'analyse des causes d'un événement indésirable cherche :", 'Les causes profondes', "Uniquement l'erreur individuelle, pour identifier le soignant en faute", 'À cacher l\'événement', 'À désigner le soignant fautif rapidement'],
    ["La méthode des « 5 pourquoi » sert à :", "Remonter progressivement aux causes profondes d'un problème", 'Compter les patients', 'Évaluer la satisfaction des patients en cinq questions', 'Calculer une dose de médicament'],
    ["Un audit clinique consiste à :", 'Comparer les pratiques réelles à un référentiel pour les améliorer', 'Contrôler les vestiaires', "Faire l'inventaire de la pharmacie et du matériel du service", 'Évaluer les repas uniquement'],
    ["La certification d'un établissement de santé vise à :", 'Évaluer qualité et sécurité', 'Fixer les tarifs des consultations et des hospitalisations', 'Recruter du personnel', 'Construire de nouveaux bâtiments'],
    ["Un questionnaire de satisfaction des patients permet :", 'De recueillir leur avis', 'De sanctionner les patients', 'De remplacer les soins', "D'évaluer individuellement chaque soignant pour le calcul des primes"],
    ["La cartographie des risques d'un service identifie :", 'Les risques, leur fréquence, leur gravité', 'L\'emplacement des fenêtres', 'Les congés et la répartition géographique des soignants dans le service', 'Le menu de la semaine'],
    ["Un protocole de soins validé doit être :", 'Daté, connu, révisé', 'Gardé secret', 'Valable sans limite de temps une fois signé par le chef de service', 'Écrit à la main sans validation'],
    ["Le signalement d'un événement indésirable doit être encouragé grâce :", 'À une culture de sécurité non punitive', 'À la menace de sanctions', 'À l\'anonymat des fautes graves sans analyse', 'Au silence'],
    ["L'identitovigilance, l'hygiène des mains et la check-list du bloc sont :", 'Des pratiques de sécurité', 'Des tâches administratives inutiles', 'Facultatives', 'Des obligations réservées aux médecins et aux chirurgiens du bloc'],
    ["Après un événement grave, l'équipe peut bénéficier :", "D'un débriefing et d'un soutien", 'D\'aucun soutien', 'D\'une sanction collective', "D'un changement de service immédiat de tous les soignants impliqués"],
    ["Le plan d'actions qualité comprend :", 'Actions, responsables, échéances', "Uniquement des idées d'amélioration, sans date ni responsable désigné", 'Uniquement des idées', 'Des actions sans responsable désigné'],
    ["La gestion des plaintes et réclamations des patients :", 'Est une source d\'amélioration et doit être analysée', 'Doit être ignorée', 'Sert à sanctionner le patient', 'Est réservée au service juridique sans retour au service'],
    ["L'évaluation des pratiques professionnelles (EPP) a pour but :", "D'améliorer la qualité des soins", 'De noter individuellement les soignants pour le calcul de leur paie', 'De remplacer la formation initiale', 'De réduire le nombre de soignants'],
  ],
};
