/** Questions supplémentaires – pédiatrie et encadrement des soins. */
import type { QuestionBrute } from '../qcm-banque';

export const SUITE_SPECIALITES: Record<string, QuestionBrute[]> = {
  'Soins pédiatriques': [
    ["La fréquence respiratoire normale d'un enfant de 1 à 5 ans est d'environ :", '20 à 30 cycles/min', '5 à 10 cycles/min', '60 à 80 cycles/min', '100 cycles/min'],
    ["Le calcul d'une dose pédiatrique : 15 mg/kg pour un enfant de 12 kg donne :", '180 mg', '15 mg', '120 mg', '1 800 mg'],
    ["La bronchiolite du nourrisson est le plus souvent due :", 'À un virus (souvent le VRS)', 'À une bactérie systématiquement', 'À une allergie', 'À une carence en fer'],
    ["Les signes de gravité d'une bronchiolite incluent :", 'Difficulté à s\'alimenter, signes de lutte respiratoire, pauses respiratoires', 'Un simple nez qui coule', 'Une toux légère sans gêne', 'Un bon appétit'],
    ["Pour réhydrater un enfant atteint de diarrhée sans signe de gravité, on utilise :", 'Une solution de réhydratation orale (SRO), par petites quantités fréquentes', 'De l\'eau très sucrée', 'Des boissons gazeuses', 'Un jeûne complet'],
    ["La douleur chez l'enfant de moins de 4 ans s'évalue avec :", 'Une échelle comportementale adaptée à l\'âge (type FLACC, EVENDOL)', 'Une échelle numérique de 0 à 10 qu\'il remplit seul', 'Aucune échelle', 'La tension artérielle seule'],
    ["Le calendrier vaccinal de l'enfant doit être :", 'Vérifié à chaque consultation ou hospitalisation', 'Ignoré à l\'hôpital', 'Rempli par la famille seule', 'Vérifié uniquement à 18 ans'],
    ["La présence des parents lors des soins chez l'enfant :", 'Est en général favorable et rassurante pour l\'enfant', 'Est toujours interdite', 'Augmente systématiquement la douleur', 'N\'a aucun intérêt'],
    ["Une fièvre chez un nourrisson de moins de 3 mois :", 'Impose un avis médical rapide', 'Est toujours bénigne', 'Se traite par un bain froid', 'Ne nécessite aucune surveillance'],
    ["La déshydratation sévère chez l'enfant se manifeste par :", 'Une somnolence, des yeux creux, une peau qui garde le pli et une diminution des urines', 'Une agitation joyeuse', 'Une prise de poids', 'Des urines abondantes et claires'],
    ["La sécurité d'un enfant hospitalisé impose notamment :", 'Barrières de lit relevées et aucun médicament à sa portée', 'De le laisser seul sans surveillance', 'De lui laisser des petits objets', 'De laisser les fenêtres grandes ouvertes'],
    ["Pour un enfant, les explications avant un soin doivent être :", 'Adaptées à son âge, honnêtes et rassurantes', 'Absentes pour ne pas l\'effrayer', 'Fausses (« ça ne fera rien ») systématiquement', 'Données uniquement aux parents'],
    ["La crème anesthésiante locale avant une ponction veineuse chez l'enfant :", 'Doit être appliquée suffisamment longtemps avant le soin selon la notice', 'Agit immédiatement', 'Est contre-indiquée chez tous les enfants', 'S\'applique après la ponction'],
    ["Les signes d'une détresse respiratoire chez le nourrisson incluent :", 'Battement des ailes du nez, tirage, geignement, coloration grise', 'Un sommeil calme', 'Une bonne prise des biberons', 'Une respiration lente et régulière'],
  ],
  'Encadrement et organisation des soins': [
    ["La fiche de poste d'un soignant décrit :", 'Ses missions, ses responsabilités et ses liens hiérarchiques', 'Son salaire uniquement', 'Ses congés', 'Sa vie privée'],
    ["L'entretien annuel d'évaluation sert à :", 'Faire le bilan de l\'année, fixer des objectifs et identifier les besoins de formation', 'Sanctionner', 'Fixer les vacances uniquement', 'Remplacer les transmissions'],
    ["Un absentéisme élevé dans une équipe doit faire rechercher :", 'Des causes liées aux conditions de travail, à la charge ou au climat d\'équipe', 'Uniquement la paresse', 'Rien', 'Un coupable unique'],
    ["La délégation efficace suppose :", 'De confier une tâche claire à une personne compétente et d\'en assurer le suivi', 'De tout déléguer sans contrôle', 'De ne jamais déléguer', 'De déléguer uniquement les tâches pénibles sans explication'],
    ["Une réunion de service efficace comprend :", 'Un ordre du jour, une durée maîtrisée et un compte rendu', 'Aucune préparation', 'Uniquement des reproches', 'Une durée illimitée'],
    ["Lors d'un pic d'activité imprévu, le surveillant :", 'Réorganise les priorités, mobilise des renforts si possible et informe sa hiérarchie', 'Ne change rien', 'Ferme le service', 'Rentre chez lui'],
    ["La charge en soins d'un service se mesure notamment avec :", 'Des outils d\'évaluation de la dépendance et de la gravité des patients', 'Le nombre de fenêtres', 'Le nombre de visiteurs', 'Le budget de la cafétéria'],
    ["Le plan de formation d'un service doit :", 'Répondre aux besoins des patients, des protocoles et des agents', 'Concerner uniquement le surveillant', 'Être fixé au hasard', 'Être identique chaque année sans réflexion'],
    ["Un conflit entre un soignant et un médecin doit être géré :", 'Par un échange en privé, factuel, centré sur le patient, avec médiation si nécessaire', 'Devant les patients', 'Par mail collectif', 'En ignorant le problème'],
    ["Le tutorat d'un étudiant en stage comprend :", 'L\'accueil, des objectifs, l\'accompagnement et l\'évaluation', 'Le laisser seul en autonomie totale dès le 1er jour', 'Lui confier uniquement le ménage', 'Aucun suivi'],
    ["La gestion du stock et du matériel du service relève :", "De l'organisation du surveillant, en lien avec la pharmacie et les services techniques", 'Uniquement des patients', 'De personne', 'Des visiteurs'],
    ["La motivation d'une équipe est favorisée par :", 'La reconnaissance, la participation aux décisions et des objectifs clairs', 'Les reproches publics', 'L\'absence de communication', 'Les changements de planning sans prévenir'],
    ["Un nouveau protocole de soins est mis en place. Le surveillant :", 'Informe, forme l\'équipe et vérifie son application', 'L\'affiche sans explication', 'Le garde dans son bureau', 'Laisse chacun l\'interpréter'],
    ["Le surveillant de nuit est notamment responsable :", 'De la continuité et de la sécurité des soins dans les services pendant la nuit', 'Uniquement de la fermeture des portes', 'De la cuisine', 'Des admissions administratives uniquement'],
    ["Pour prévenir l'épuisement d'une équipe, l'encadrant peut :", 'Équilibrer les plannings, être à l\'écoute et organiser des temps d\'échange', 'Augmenter les heures supplémentaires sans limite', 'Supprimer les pauses', 'Ignorer les signes de fatigue'],
  ],
  'Qualité et gestion des risques': [
    ["La démarche qualité repose sur le cycle :", 'Planifier, faire, vérifier, améliorer (roue de Deming)', 'Commencer, abandonner, oublier', 'Punir, contrôler, sanctionner', 'Acheter, stocker, jeter'],
    ["Un indicateur qualité sert à :", 'Mesurer un résultat ou une pratique pour suivre son évolution', 'Remplacer les soins', 'Décorer le service', 'Fixer les salaires'],
    ["L'analyse des causes d'un événement indésirable cherche :", 'Les causes profondes liées à l\'organisation, et pas seulement l\'erreur individuelle', 'Uniquement un coupable', 'À cacher l\'événement', 'À accuser le patient'],
    ["La méthode des « 5 pourquoi » sert à :", "Remonter progressivement aux causes profondes d'un problème", 'Compter les patients', 'Évaluer la douleur', 'Calculer une dose'],
    ["Un audit clinique consiste à :", 'Comparer les pratiques réelles à un référentiel pour les améliorer', 'Contrôler les vestiaires', 'Faire un inventaire de la pharmacie', 'Évaluer les repas uniquement'],
    ["La certification d'un établissement de santé vise à :", 'Évaluer la qualité et la sécurité des soins selon un référentiel', 'Fixer les prix des consultations', 'Recruter du personnel', 'Construire de nouveaux bâtiments'],
    ["Un questionnaire de satisfaction des patients permet :", 'De recueillir leur avis pour améliorer la prise en charge', 'De sanctionner les patients', 'De remplacer les soins', 'D\'évaluer les salaires'],
    ["La cartographie des risques d'un service identifie :", 'Les risques principaux, leur fréquence et leur gravité, pour prioriser les actions', 'L\'emplacement des fenêtres', 'Les congés', 'Le menu de la semaine'],
    ["Un protocole de soins validé doit être :", 'Daté, accessible, connu de l\'équipe et révisé régulièrement', 'Gardé secret', 'Valable sans limite de temps', 'Écrit à la main sans validation'],
    ["Le signalement d'un événement indésirable doit être encouragé grâce :", 'À une culture de sécurité non punitive', 'À la menace de sanctions', 'À l\'anonymat des fautes graves sans analyse', 'Au silence'],
    ["L'identitovigilance, l'hygiène des mains et la check-list du bloc sont :", 'Des pratiques de sécurité des soins à évaluer régulièrement', 'Des tâches administratives inutiles', 'Facultatives', 'Réservées aux médecins'],
    ["Après un événement grave, l'équipe peut bénéficier :", "D'un débriefing et d'un soutien (« seconde victime »)", 'D\'aucun soutien', 'D\'une sanction collective', 'D\'un changement de service immédiat'],
    ["Le plan d'actions qualité comprend :", 'Des actions, des responsables, des échéances et un suivi', 'Uniquement des idées', 'Aucune date', 'Des actions sans responsable'],
    ["La gestion des plaintes et réclamations des patients :", 'Est une source d\'amélioration et doit être analysée', 'Doit être ignorée', 'Sert à sanctionner le patient', 'Est réservée au service juridique sans retour au service'],
    ["L'évaluation des pratiques professionnelles (EPP) a pour but :", "D'améliorer la qualité des soins à partir de l'analyse des pratiques", 'De noter les soignants pour la paie', 'De remplacer la formation initiale', 'De réduire le nombre de soignants'],
  ],
};
